### PR TITLE
Gtk input2

### PR DESCRIPTION
**Pull request by andreasb242**
Moved input handling to a Strategy pattern, currently there are two methods available: the X11 crash fix, and the standard GTK input as it was on GTK2.

Planed is to handle all like in the GTK3 example, but this is a really big change, so need to merge even if the new features are not implemented.

### CODE REVIEW

**Comment by luco5826** [comment]
What a work!

**Comment by andreasb242** [comment]
@luco5826 Did you review it?

**Comment by luco5826** [comment]
No no, I just saw the massive quantity of work you kept up, that's great! I'm gonna study it asap

**Comment by andreasb242** [comment]
DO NOT MERGE YET, on one device I get crashes... Have to look at this first...

**Pull request closed without merging**
