### PR TITLE
Travis compatible and added Slackin invitation plugin in README

### PR DESCRIPTION
**Pull request by MarPiRK**

### CODE REVIEW

**Comment by MarPiRK** [comment]
- Travis compatible (look at https://travis-ci.org/MarPiRK/xournalpp) – not all features are enabled for now, but it just works
- some CMakeLists.txt cleanup
- no target_compile_features, so it's compatible with CMake 2.8.8
- possibility to build and link statically boost
- possibility to link pre-built glibmm lib
- CMake variables README
- libraries and linking cleanup
- possibility to compile with gcov support

**Comment by wbrenna** [comment]
This compiles on my system now. The README.md should be updated with cmake instructions (including mathtex support with -DENABLE_MATHTEX=ON).

**Comment by MarPiRK** [comment]
Don't merge it for now. It seems like free OpenShift cartridge idles after 24h, so it has to be started manually. Instead I'll try to run IRC bot on free AWS instance.

**Comment by MarPiRK** [comment]
OK, whatever. For now it runs on my private server, as it's not that CPU hungry. Until I'm paying for it, it'll work as a charm. Of course it's not perfect solution in long term, so maybe some time in future I'll tinker with AWS or some other free services to get it working and independent from me.
So if everything is ok with this pull request please push it, so I can start working on some other things with clear mind.

**Comment by andreasb242** [comment]
For me it looks good, not tested yet.
Translation is made, Build system (CMake) and README.
Other meanings?

**Comment by MarPiRK** [comment]
There are mostly non-code changes, but I recon that there was some kind of problem with image background, which I fixed.

**Pull request merged**
