### PR TITLE
New input system

### LINKED ISSUE #940: Secondary stylus button only works when there is no contact
I have a Thinkpad X380 Yoga and when I use Button 2 with the e.g. the eraser tool, it only works when I don't touch the screen. As soon as I touch the screen it reverts back to the drawing tool.

### LINKED ISSUE #1007: Crash when using middle mouse button and drag out of window
When:
  Using the middle mouse button as hand tool ( but not when selecting the hand tool and using left mouse button ).
  Drag the mouse out of the window. Crash

** (xournalpp:25537): WARNING **: XojTypeCheck failed: NULL xournalpp/src/gui/inputdevices/NewGtkInputDevice.cpp:64
*** Program received signal SIGSEGV (Segmentation fault) ***

Tested on Linux Mint.

### PR DESCRIPTION
**Pull request by LittleHuba**
This is the new input system, mentioned in various issues (especially #940).

There are currently a lot of open issues, which need to be adressed:

- ~~Device continues drawing when it leaves the widget area (it should scroll the view when possible but definitely not continue to draw on the page)~~
- ~~Scrolling in the TouchWorkaround-mode is not yet implemented~~
- ~~Providing the old system behind a setting flag would be nice if there are any big issues with the new system~~ -> New system is marked experimental (enable in settings)
- ~~Gesture handling is still done by GTK and continues to fail in the most fabulous ways (Best would be to do this manually)~~
- ~~Disable GTK scrolling when stylus or mouse input is detected~~ -> will be handled in new hand recognition - seperate PR
- ~~Some dubious bug when touch drawing is enabled and a pen hovers over the screen while one draws with a finger~~
- ~~Some information asked for is not yet provided in position data sent to views (I did not forget @JJones780 :wink: )~~
- Fixes #940, fixes #1007 
- ...

I'm on holiday for the next week so if anybody wants to work on one of the issues, feel free to do so.

### CODE REVIEW

**Comment by LittleHuba** [comment]
Ohh one more thing:
If anybody works on gesture handling and touch input please use the class TouchInputHandler for all things concerning touch that is not drawing.

**Comment by LittleHuba** [comment]
For my reference and everybody else willing to work on this:
Check the Travis build as it outlines some more issues

**Comment by Peetz0r** [comment]
Hey! I'm not a c++ dev, but I might be able to help with testing. My device is a Thinkpad Yoga 370 with the stylus with 2 buttons.

Please let my know if I can help :)

**Comment by LittleHuba** [comment]
> Hey! I'm not a c++ dev, but I might be able to help with testing. My device is a Thinkpad Yoga 370 with the stylus with 2 buttons.
> 
> Please let my know if I can help :)

What OS are you using on your Laptop?

**Comment by Peetz0r** [comment]
I just upgraded from Fedora 29 to 30 (therefore Gnome 3.32)

**Comment by LittleHuba** [comment]
@andreasb242 The new input system is hidden behind a checkbox in the settings. The default system is still the old one. Please also try it on some of your release devices and check if the input behaves correctly. Especially Windows could not be tested by myself.

**Comment by michaelschufi** [comment]
I have a Windows 10 Notebook with a Wacom Intuos CTH-480 and could help you with testing.

**Comment by Peetz0r** [comment]
Maybe I could try Windows 10 in a VM (with the wacom device passed trough, and the vm fullscreen). Not sure if I have the disk space for it, but I am planning a disk upgrade in a few weeks.

**Comment by LittleHuba** [comment]
@michaelschufi you are more than welcome to check it out! 
Windows is currently a big unknown for me as I have no device to check how they handle input devices. If you find anything that is not as expected leave a comment here or create an issue. 

@Peetz0r even with Linux you are welcome to test the system as different hardware can lead to different bugs.

**Comment by Peetz0r** [comment]
At first glance it seems to indeed work as promised. It's much more usable compared to the old input system. I'll let you know whenever I find something that does not work as expected.

Haven't yet tried anything else than my main laptop with Fedora. Setting up a Windows VM takes more time than I expected. Also I might be able to test a (non-pen) tablet (also with Fedora) tomorrow.

**Comment by Technius** [comment]
I have a Windows installation. I'll try it out on my Wacom Intuos tablet when I have time tomorrow.

**Comment by Technius** [comment]
On Windows, I'm getting a strange issue (that is also present on the latest stable release; I'll probably open an issue once I learn more about the problem) that isn't letting me test the PR properly. I'll try again with a different computer.

**Comment by LittleHuba** [comment]
> On Windows, I'm getting a strange issue (that is also present on the latest stable release; I'll probably open an issue once I learn more about the problem) that isn't letting me test the PR properly. I'll try again with a different computer.

Could you elaborate on that?

**Comment by Rmano** [comment]
I am just checking this, and it seems **great**. No more spurious points. My device is a Intuos CTH-480.
Small points:
- once I had the cursor go crazy on me, moving alone (I was playing with the zoom while resizing the windows). Switched focus away and back, all ok, I am unable to reproduce. 
- My tablet has a switch to enable touch recognition for hand scrolling. If I switch this on, with both the TabletPCButton on or off, I have dots appearing sometime again. 
- When choosing pressure sensitivity, the drawing width is still too thin (I have to press a lot to have decent sizes)... I think it should be a settable thing...

Thanks!

**Comment by Rmano** [comment]
> Could you elaborate on how the cursor went "crazy" on you?

It started moving alone across all the screen --- exiting from one side and wrapping to the other side. I tried to reproduce it without success.

**Comment by Rmano** [comment]
> Could you please create another bug report and attach the input logs as described in the bug report template?

I'll try this afternoon at home, I am in a rush now

**Comment by LittleHuba** [comment]
> > Could you elaborate on how the cursor went "crazy" on you?
> 
> It started moving alone across all the screen --- exiting from one side and wrapping to the other side. I tried to reproduce it without success.

Sounds like a driver issue to me as I do never influence the cursor position in any part of the code.

**Pull request merged**
