### PR TITLE
Add Ubuntu 24.04 to builds

### LINKED ISSUE #5782: xournalpp for Linux Mint 22 / Ubuntu 24.04
### Operating System

Linux

### (Linux only) Distribution

ubuntu / Linux Mint

### (Linux only) Desktop Environment

xfce

### (Linux Only) Display Server

X.Org

### Installation Method

official release

### Xournal++ Version

1.2.3+dev

### libgtk Version

libgtk-3 and libgtk-4 (-bin and -dev for both)

### Bug Description

I just did a clean install of Linux Mint 22 xfce (which is based on (x)ubuntu 24.04), and then I tried to install the official xournalpp 1.2.3+dev.  But there is no file for LM22, and when I tried to install the most recent one (ubuntu jammy jellyfish) I got this error message:

   depends:  liblua5.3-0  but it is not installed
   depends:  libportaudiocpp0 (>=12)   but it is not installed

I tried  apt --fixed broken  first and then install xournalpp, which was successful, but when I run it I go the error message

  xournalpp: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory

I am not sure how to proceed from here.  Xournalpp does work on LM 21.2.

### Expected Behaviour

run apt dpkg -i (xournalpp).deb to install the latest release.

### Steps to Reproduce

1.  sudo apt dpkg -i (xournalpp 1.2.3-dev).deb
2.  sudo apt --fix-broken install
3. sudo apt dpkg -i (xournalpp 1.2.3-dev).deb
4.  run xournalpp and go the "No such file or directory" error for libzip.so.5

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rolandlo**
Closes #5782

### CODE REVIEW

**Comment by rolandlo** [comment]
I'm confused. The Ubuntu 24.04 image should be available as a beta version, see https://github.com/actions/runner-images/issues/9848. However the 24.04 version is not built due to an error:
```shell
##[error]No config name or imagelabel provided in request
```
grafik

I don't see an error in the `create-installers.yml`. 

On https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml where Ubuntu 24.04 is not yet listed. Maybe we must wait.

**Comment by rolandlo** [comment]
> The azure pipeline we use is not the same as Github actions. We should probably migrate from Azure to github actions.

That would have some advantages indeed. For example Github actions also have MacOS ARM runners.
On the other hand the Ubuntu 24.04 image should also be available on Azure, since in the announcement it is explicitly written: `Ubuntu 24.04 is now available for all GitHub Actions and Azure DevOps users.`

**Comment by rolandlo** [comment]
I think I should rebase this on release-1.2, so we can have a 1.2.4 release with Ubuntu 24.04 included.

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMzEzNzEvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMzEzNzEvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMzEzNzEvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMzEzNzEvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 22.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMzEzNzEvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMi4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Pull request merged**
