### PR TITLE
Debain packaging working

### PR DESCRIPTION
**Pull request by andreasb242**
#143

### CODE REVIEW

**Comment by JonasDralle** [comment]
Can't locate the debian package...

**Comment by LittleHuba** [comment]
See https://github.com/xournalpp/xournalpp#ubuntu-and-derivates

**Comment by JonasDralle** [comment]
installing PPAs under Debian is [considered unsafe](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian)

**Comment by LittleHuba** [comment]
That would mean we have to support multiple debian packages independently on our own. See #959 for further details why we will not do it on our own.

**Comment by JonasDralle** [comment]
installing PPAs under Debian is [considered unsafe](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian)

**Pull request merged**
