### PR TITLE
Update appdata, desktop files, readme and package descriptions

### PR DESCRIPTION
**Pull request by rolandlo**
This is PR #3605 by @ovari rebased on current master and squashed into one commit.

### CODE REVIEW

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised.

**Comment by ovari** [comment]
Can you please merge the Hungarian translations from Crowdin? They should be at 100%. Thank you

**Comment by rolandlo** [comment]
> Can you please merge the Hungarian translations from Crowdin? They should be at 100%. Thank you

I can merge the Crowdin updates (into the master branch). Long time since we done that last time. They will be available in the nightly release. Thanks for the reminder.

**Comment by ovari** [comment]
Thanks for the post; however, will wait for the next release. Do you know when the next release is expected? Thank you

**Comment by rolandlo** [comment]
> Thanks for the post; however, will wait for the next release. Do you know when the next release is expected? Thank you

No, I don't. Version 1.1.1 should be released this weekend, but that's only a bugfix release and won't contain updated translations. The master branch (containing new features) will probably take a couple of months until it is released.

What distro do you use? Can't you test the nightly release?

**Comment by ovari** [comment]
> What distro do you use?

Our device is too low-spec to build from source.

>  Can't you test the nightly release?

Don't want to cause problems on our system.

> The translation updated have been merged now.

Thank you very much. Can you please merge the translations again just before the release?

> Merging in 24 hours if no objections are raised.

If no objections have been raised, can this patch please be merged?

Thank you once again.

**Comment by rolandlo** [comment]
> > Can't you test the nightly release?
> 
> Don't want to cause problems on our system.

You could test out the AppImage from the nightly release. That's just one file, that you can download and execute, which does not require making any changes to the system. Just make it executable and run it.

**Comment by rolandlo** [comment]
> Thank you very much. Can you please merge the translations again just before the release?

Sure, that's definitely on the agenda.
> 
> > Merging in 24 hours if no objections are raised.
> 
> If no objections have been raised, can this patch please be merged?

Thanks for the reminder!

**Comment by ovari** [comment]
Do you have a `Release Checklist` for each release? You might like to use the [Octave](https://www.octave.org) one as a template so you don't miss anything: https://wiki.octave.org/7.1_Release_Checklist

Plan to test when available using `xournalpp-1.1.1+dev-nightly.20220215-x86_64.AppImage` or later from https://github.com/xournalpp/xournalpp/releases/tag/nightly. If this is incorrect, please advise the correct location and file.

Thank you

**Comment by rolandlo** [comment]
@ovari Yes, that is the correct AppImage. It should work, see here:
grafik

**Pull request merged**
