### PR TITLE
Format source files with clang-format

### PR DESCRIPTION
**Pull request by createyourpersonalaccount**
The command used at the root directory was

    find src/                                 \
         -regex '.*\.\(h\|hpp\|c\|cpp\)'      \
         -execdir clang-format -i             \
                               -style=file {} \;

### CODE REVIEW

**Comment by eldipa** [comment]
I like the idea of automating the formatting of the code but as you can see, adding a commit that modifies 85 files may break `git blame`. Worst, as I understand, this was a command that you ran manually: this means that it is a matter of time for the code eventually drifts from the formatted version. 

A safer approach would be:
 - add a `pre-commit` hook that call `clang-format -i` on each commit, so any developer will stick to the formatting
 - add a call to `clang-format` (without `-i`) in the CI system and if a file does not stick to the expected format, fail the build.
 - one of the developers with push access should run `clang-format -i` on all the files and do a commit. Then, write a `.git-blame-ignore-revs` file in the root directory with the full hash of the commit that contains the reformatting. Each developer can configure his/her `git` to read that file and ignore that commit when doing a `git blame`.

**Comment by createyourpersonalaccount** [comment]
> Worst, as I understand, this was a command that you ran manually: this means that it is a matter of time for the code eventually drifts from the formatted version.

The code style is automatically checked by the CI system, I believe I was just formatting old files. Git blame can be fixed by ignoring the commit with [.git-blame-ignore-revs](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).

**Comment by Febbe** [comment]
There is also the problem, that all merge requests will face conflicts, when they modify the same unformatted section. This is btw. the reason, why we never fixed the format for all files.

**Comment by eldipa** [comment]
> There is also the problem, that all merge requests will face conflicts, when they modify the same unformatted section. This is btw. the reason, why we never fixed the format for all files.

Good point.

**Comment by rolandlo** [comment]
This PR is out of sync and contested. Closing therefore.

**Pull request closed without merging**
