### PR TITLE
fix edge panning crash and add warnings

### LINKED ISSUE #3618: Frequent crash at saving xopp file
Hi. I'm encountering random and frequent crashes (shut down) when I save the xopp file by pressing ctrl+s.
I use large paper format as width 60, height 60 with a lot of attached screenshot images on those large papers.
Can this large paper with a lot of attached images cause the crash?

I'm using 1.1.0+dev, built on Nov 23 2021 on Ubuntu 20.04.3 LTS

Error log is as following

```
Date: Thu Nov 25 08:42:05 2021
Error: signal 11
[bt]: (0) xournalpp(+0xbb300) [0x5644b18b4300]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1a9c3d2210]
[bt]: (2) xournalpp(_ZN11XojPageView10getXournalEv+0x4) [0x5644b1977274]
[bt]: (3) xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x37) [0x5644b195fb47]
[bt]: (4) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7f1a9ca98be8]
[bt]: (5) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f1a9ca9804e]
[bt]: (6) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7f1a9ca98400]
[bt]: (7) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f1a9ca984a3]
[bt]: (8) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f1a9ccdbfe5]
[bt]: (9) xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x5644b18b5261]
[bt]: (10) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1a9c3b30b3]
[bt]: (11) xournalpp(_start+0x2e) [0x5644b18b3bee]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0xbb79c) [0x5644b18b479c]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1a9c3d2210]
??:0
[bt] #3 xournalpp(_ZN11XojPageView10getXournalEv+0x4) [0x5644b1977274]
??:0
[bt] #4 xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x37) [0x5644b195fb47]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7f1a9ca98be8]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f1a9ca9804e]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7f1a9ca98400]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f1a9ca984a3]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f1a9ccdbfe5]
??:0
[bt] #10 xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x5644b18b5261]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1a9c3b30b3]
??:0
[bt] #12 xournalpp(_start+0x2e) [0x5644b18b3bee]
??:0
```

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #3618. Warnings have been included to detect the problem.

### CODE REVIEW

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1NzYvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1NzYvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1NzYvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 18.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1NzYvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0xOC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1NzYvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by rolandlo** [comment]
@youngminpark2559 Would you please try out the installer and run from terminal? You should see some warnings instead of a crash (hopefully). Please report them back.

**Comment by youngminpark2559** [comment]
@rolandlo Sure. I'll update the version from 1.1.0 and run xournalpp in terminal to see crash warnings

**Comment by rolandlo** [comment]
> @rolandlo Sure. I'll update the version from 1.1.0 and run xournalpp in terminal to see crash warnings

Just to make clear:You will have to use the installer provided above (in [this comment](https://github.com/xournalpp/xournalpp/pull/3704#issuecomment-1007174452)).

**Comment by youngminpark2559** [comment]
@rolandlo Yes, I installed the app through above link installer Ubuntu 20.04
image
and running on the terminal
image

**Comment by youngminpark2559** [comment]
@rolandlo I'm not sure if this warning message is related to crash error, I saw this warning
image

I tried to reproduce crash error with the file which has a lot of screenshot images but crash warning message (edge panning) strangely didn't occur yet in terminal

**Comment by rolandlo** [comment]
> @rolandlo I'm not sure if this warning message is related to crash error, I saw this warning image
> 
> I tried to reproduce crash error with the file which has a lot of screenshot images but crash warning message (edge panning) strangely didn't occur yet in terminal

These warnings (`DocumentView::drawStroke empty stroke...`) are harmless, I think, and are certainly unrelated to the crash. Did you get a crash though? If so, please include the error message again. Otherwise please continue testing until you either get a crash or see one of the warnings `Selection does not exist anymore while handling edge panning` or `View does not exist anymore while handling edge panning`. As long as you don't see any of these warnings, the app behaves exactly like before.

**Comment by youngminpark2559** [comment]
@rolandlo I haven't met crash warnings (Selection does not... or View does not ...) or crash even if I tried to run the app on the same files and environment where I encountered the crash.

The other day, I updated xournalpp through Ubuntu's automatic update and I performed apt-get purge xournalpp to install the app through above linked installer.

I'll report the edge panning warnings if I encounter them on terminal or icon execution

**Comment by youngminpark2559** [comment]
@rolandlo I got the edge panning error message. Hope this helps.

image

And the log file contents (/home/young/.cache/xournalpp/errorlogs/errorlog.20220112-170604.log)
```
Date: Wed Jan 12 17:06:04 2022
Error: signal 11
[bt]: (0) xournalpp(+0x1ee264) [0x555f7f87f264]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7ff850d06210]
[bt]: (2) xournalpp(_ZN11XournalView10getControlEv+0x4) [0x555f7f80ae14]
[bt]: (3) xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x51) [0x555f7f7c41e1]
[bt]: (4) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7ff852268be8]
[bt]: (5) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7ff85226804e]
[bt]: (6) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7ff852268400]
[bt]: (7) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7ff8522684a3]
[bt]: (8) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7ff8516b3fe5]
[bt]: (9) xournalpp(_ZN11XournalMain3runEiPPc+0x4af) [0x555f7f774b7f]
[bt]: (10) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff850ce70b3]
[bt]: (11) xournalpp(_start+0x2e) [0x555f7f7528be]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0x1ee739) [0x555f7f87f739]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7ff850d06210]
??:0
[bt] #3 xournalpp(_ZN11XournalView10getControlEv+0x4) [0x555f7f80ae14]
??:0
[bt] #4 xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x51) [0x555f7f7c41e1]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7ff852268be8]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7ff85226804e]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7ff852268400]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7ff8522684a3]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7ff8516b3fe5]
??:0
[bt] #10 xournalpp(_ZN11XournalMain3runEiPPc+0x4af) [0x555f7f774b7f]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff850ce70b3]
??:0
[bt] #12 xournalpp(_start+0x2e) [0x555f7f7528be]
??:0

```

**Comment by rolandlo** [comment]
> @rolandlo I got the edge panning error message. And the app crashed as well as warning message. Hope this helps.
> 
Thanks for the testing, the warning message and the crash log. 
The warning shows that some crashes are already prevented through this PR. The crash that happened later. With the latest commit that I pushed that crash also cannot occur anymore. Please use the new installer (when it has finished building) and see, if you still get a crash sometimes.

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1ODgvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1ODgvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1ODgvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 18.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1ODgvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0xOC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc1ODgvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by youngminpark2559** [comment]
@rolandlo I installed through above installer
image

And I got the crash but the warning message didn't appear
image

For a potential hint for debugging, I maximally zoomed out and I pasted screenshot on to xournalpp paper and moved screenshot by mouse drag, and it seems like this situation easily creates crash.

The log is as following
```
Date: Thu Jan 13 18:22:14 2022
Error: signal 11
[bt]: (0) xournalpp(+0x1ee244) [0x55cca4d01244]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7feb0b799210]
[bt]: (2) xournalpp(_ZN11XojPageView10getXournalEv+0x4) [0x55cca4c808d4]
[bt]: (3) xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x49) [0x55cca4c461d9]
[bt]: (4) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7feb0ccfbbe8]
[bt]: (5) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7feb0ccfb04e]
[bt]: (6) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7feb0ccfb400]
[bt]: (7) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7feb0ccfb4a3]
[bt]: (8) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7feb0c146fe5]
[bt]: (9) xournalpp(_ZN11XournalMain3runEiPPc+0x4af) [0x55cca4bf6b7f]
[bt]: (10) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7feb0b77a0b3]
[bt]: (11) xournalpp(_start+0x2e) [0x55cca4bd48be]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0x1ee719) [0x55cca4d01719]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7feb0b799210]
??:0
[bt] #3 xournalpp(_ZN11XojPageView10getXournalEv+0x4) [0x55cca4c808d4]
??:0
[bt] #4 xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x49) [0x55cca4c461d9]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7feb0ccfbbe8]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7feb0ccfb04e]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7feb0ccfb400]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7feb0ccfb4a3]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7feb0c146fe5]
??:0
[bt] #10 xournalpp(_ZN11XournalMain3runEiPPc+0x4af) [0x55cca4bf6b7f]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7feb0b77a0b3]
??:0
[bt] #12 xournalpp(_start+0x2e) [0x55cca4bd48be]
??:0

```

**Comment by youngminpark2559** [comment]
@rolandlo And I observed additional situation where the warning message of edge panning shows and no crash
image

**Comment by rolandlo** [comment]
> @rolandlo And I observed additional situation where the warning message of edge panning shows and no crash It seems like this edge panning warning appeared when I started the xournalpp "file/path/name.xopp" image

You got that message almost two minutes after starting `xournalpp` from the terminal. It looks unrelated to me.

**Comment by youngminpark2559** [comment]
@rolandlo Yes, but above message (https://github.com/xournalpp/xournalpp/pull/3704#issuecomment-1011952706) is the situation where I encountered the crash without edge panning warning on the new installed xournalpp. Since the crash was not captured by edge panning exception, could that crash have occured regardless of edge panning? Hope that report helps.

**Comment by rolandlo** [comment]
@LittleHuba @bhennion Does anyone of you understand why `handleEdgePan` can still segfault on `self->view->getXournal()`, although I added the check that `self->view` is not null? Is this a multithreading issue?

**Comment by bhennion** [comment]
I have only given this a glance, but yes, it could definitely be a data race issue (`handleEdgePan` being a timer callback function, we do not know which thread is calling it).

I imagine it could be triggered by

https://github.com/xournalpp/xournalpp/blob/484b5cb680c2162c1f654b26d2e5f5d2e20e74d7/src/control/tools/EditSelection.cpp#L158-L174

The `view` pointer is set to `nullptr` before killing the timer, and without ensuring the callback function is not running.

Also I don't really understand how the crash is triggered. Do we have an identified reproducible input sequence that (even only sometimes) leads to the crash?

**Comment by youngminpark2559** [comment]
@bhennion I don't know when the crash exactly happen. Following is the environment and task where I get the crash

1. I use large paper size like 60cm x 60cm
2. I capture image into clipboard and paste it onto xournalpp page.
3. I generally maximally zoom out to arrange screen captures
4. I move already selected screen capture from the pasting by using mouse drag with selected capture image
5. I do "2." multiple times, upto using 3 or 4 xournalpp pages like following


6. When I move selected image, or when I click other area to unselect image, or when I press ctrl+p to use pen, or when I press ctrl+s to save the state, it seems like the crash (termination of the app) happen at those moments

**Comment by LittleHuba** [comment]
Add a check for Nullpointer into the respective function and attach a debugger to the positive path of the check. Then try to trigger the bug. The backtrack in the debugger will tell you what constellation of threads causes it.

**Comment by Technius** [comment]
To identify the issue, I think we should insert some debug prints in the destructor and `setEdgePan`, so we get a console log like
```
created handler (setEdgePan)
callback
callback
callback
removed handler (setEdgePan)
created handler (setEdgePan)
callback
callback
removed handler (destructor)
```

If we end up with a sequence like
```
created handler (setEdgePan)
callback
removed handler (destructor)
callback
```
this would help a lot towards identifying the cause.

Also, I think there is an issue in `setEdgePan`:
https://github.com/xournalpp/xournalpp/blob/484b5cb680c2162c1f654b26d2e5f5d2e20e74d7/src/control/tools/EditSelection.cpp#L727-L730
should also insert `g_source_destroy` before the unref to cancel the source in the glib main loop ([see this link](https://sigquit.wordpress.com/2010/01/05/g_source_unref-and-g_source_destroy-are-your-friends/)).

**Comment by Technius** [comment]
This is blocking the 1.1.1 release, so for now, I will (in a few days) create a separate PR that allows edge panning to be disabled in the settings (and also incorporate the fix for the issue I identified above). Hopefully that will allow @youngminpark2559 and other people to work around the issue in the meantime.

**Comment by rolandlo** [comment]
Closing in favor of #3776.

**Pull request closed without merging**
