### PR TITLE
Fix orientation of new page item in vertical toolbars

### LINKED ISSUE #5145: InsertNewPageIcon and BackGroundSelectButon remain horizontal even in vertical toolbar.
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

no DE

### (Linux Only) Display Server

X.Org

### Installation Method

Built from source.

### Xournal++ Version

Master ( 86eeda5afd1f0a7bcbe9fbe960794011cd388c76 or after )

### libgtk Version

3.24.38

### Bug Description

InsertNewPageIcon and BackgroundSelectButon should be laid out  vertically in vertical toolbar.
But since 86eeda5afd1f0a7bcbe9fbe960794011cd388c76 , it is laid out horizontally.

### Expected Behaviour

InsertNewPageIcon and BackgroundSelectButon should be laid out  vertically in vertical toolbar.

### Steps to Reproduce

1. Create a left toolbar or a right toolbar.
2. Put InsertNewPage icon on that toolbar.

### Additional Context
HorizontalIcons

### PR DESCRIPTION
**Pull request by bhennion**
Fix #5145 
Merging in 24 hours unless an objection is raised.

### CODE REVIEW

**Comment by tattsan** [comment]
Thanks for the quick fix!
In vertical toolbars, the orientation was fixed. But now in horizontal toolbars, the orientation is wrong.

**Comment by tattsan** [comment]
"SELECT" and "DRAW' indicators are broken.

BrokenIcons

**Comment by bhennion** [comment]
Ok. Here is a better fix (both code-wise and functionally).

**Comment by tattsan** [comment]
It works fine! Thank you so much!!

**Comment by bhennion** [comment]
Thanks for testing @tattsan!
Merging in 24 hours unless an objection is raised.

**Pull request merged**
