### PR TITLE
Fix build against poppler 0.64.0

### PR DESCRIPTION
**Pull request by golvok**
for #264 

just some const correctness changes

### CODE REVIEW

**Comment by golvok** [comment]
hmm... this breaks compat with previous poppler versions due to const member functions not existing.

Travis is testing with 0.61.0

**Comment by golvok** [comment]
It seems that libopenjp2 dosen't come with a pkg-config file on Trusty, so then the Cmake PkgConfig in poppler 0.64.0 cannot find it (checked with `pkg-config --list-all`). Therefore the poppler build fails. I'm not sure what the best way to deal with this is. We can:
- (as part of the test setup?) download or provide a working libopenjp2.pc and trick `pkg-config` via `PKG_CONFIG_PATH`
- manually specify the right variables in the poppler build to cause the pkg-config search to be skipped (note: https://bugs.freedesktop.org/show_bug.cgi?id=106329 about poppler's FindLIBOPENJPEG.cmake)
- switch to Xenial and use the libopenjp2-7 package, which provides libopenjp2.pc. Travis does not properly support Xenial, however.

My favourite one at the moment is the first (ie. `PKG_CONFIG_PATH` based) one, though maybe dropping support for Trusty wouldn't be so bad (it's only supported for another year)... to bad Travis doesn't support it properly.

**Comment by macxcool** [comment]
I'm the xournalpp-git package maintainer for Archlinux. Can I help test this at all?

**Comment by jaykijay** [comment]
Just change the Source and Url to golvok's repo: https://github.com/golvok/xournalpp
And it will compile like before, as long as this pull request isn't merged in the main repo (here)

**Comment by macxcool** [comment]
Well. This seems to compile and run just fine for me on Archlinux with poppler up-to-date. Thanks for doing this @golvok

**Comment by JuniorJPDJ** [comment]
@macxcool have you changed PKGBUILD in AUR?
Still can't build it.

**Comment by JuniorJPDJ** [comment]
@macxcool ok, keep it, I just modified PKGBUILD locally and installed temporary version from @gelvok 's repo
I'm still waiting for fixed version in master, thanks

**Comment by swiftgeek** [comment]
Or add https://github.com/xournalpp/xournalpp/commit/4be5b5a1eab4c1ac873db237bc13c1be783081a7.patch

**Comment by max-te** [comment]
This fails to build for me with poppler 0.64.0 and boost 1.67.0 with
```
In file included from /usr/include/poppler/Object.h:46,
                 from /usr/include/poppler/Catalog.h:44,
                 from /home/max/Coding/xournalpp-git/src/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/max/Coding/xournalpp-git/src/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/max/Coding/xournalpp-git/src/xournalpp/src/model/Document.h:20,
                 from /home/max/Coding/xournalpp-git/src/xournalpp/src/control/Control.h:28,
                 from /home/max/Coding/xournalpp-git/src/xournalpp/src/control/Control.cpp:1:
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected unqualified-id before 'const'
     static bool likely(const string_type& str)
                 ^~~~~~
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected ')' before 'const'
/usr/include/boost/date_time/special_values_parser.hpp:105:17: note: to match this '('
     static bool likely(const string_type& str)
                 ^~~~~~
/usr/include/boost/date_time/time_parsing.hpp: In function 'time_type boost::date_time::parse_iso_time(const string&, char)':
/usr/include/boost/date_time/time_parsing.hpp:312:19: error: expected unqualified-id before '(' token
     if (svp_type::likely(s)) {
                   ^~~~~~
```

**Comment by macxcool** [comment]
I'm getting the same thing as max-te now.

**Comment by max-te** [comment]
Apparently poppler 0.64 is incompatible with boost 1.67.
In particular poppler defines macros `likely` and `unlikely` in `goo/GooLikely.h` which mess with boost trying to define `likely` in `special_values_parser.hpp`.

**Comment by max-te** [comment]
Would that be a poppler bug? Then it should probably be reported upstream.

**Comment by swiftgeek** [comment]
Made something similar in https://github.com/golvok/xournalpp/commit/12a409c8afc3c3ea8c8afebb67377c29e3d90035.patch

**Comment by peetCreative** [comment]
I tried @swiftgeek workaround but it failed, with the error of max-te . So is there a way to build xournalpp with recent poppler, does anybody know? I have a bit of time now to find a workaround and look for a starting point. Maybe what westernmagic proposed.

**Comment by jaykijay** [comment]
Did you tried changing the Line:
+#include "../../pdf/popplerdirect/workaround/poppler-0.64.0/goo/GooLikely.h"
to
+#include "../../pdf/popplerdirect/workaround/poppler-0.67.0/goo/GooLikely.h"

in @swiftgeek s Patch?
This worked for me ;)

**Comment by siliconninja** [comment]
This workaround doesn't work as of the newest version, 0.70.1.
The error was:
````
[ 14%] Building CXX object src/CMakeFiles/xournalpp-core.dir/control/Control.cpp.o
In file included from /home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/Control.cpp:30:
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/settings/MetadataManager.h:29:10: fatal error: ../../pdf/popplerdirect/workaround/poppler-0.64.0/goo/GooLikely.h: No such file or directory
 #include "../../pdf/popplerdirect/workaround/poppler-0.64.0/goo/GooLikely.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:89: src/CMakeFiles/xournalpp-core.dir/control/Control.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
````

I applied swiftgeek's patch by adding the 3 lines in `src/control/settings/MetadataManager.h` and changing the version number to read:
`#include "../src/pdf/popplerdirect/workaround/poppler-0.70.1/goo/GooLikely.h"`

But this didn't work for me. I am not using a PKGBUILD, I am compiling from source.

The error is:
````
In file included from /home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/settings/MetadataManager.h:23,
                 from /home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/Control.cpp:30:
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected unqualified-id before ‘const’
     static bool likely(const string_type& str)
                 ^~~~~~
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected ‘)’ before ‘const’
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/settings/../../pdf/popplerdirect/workaround/poppler-0.70.1/goo/GooLikely.h:18:25: note: to match this ‘(’
 # define likely(x)      (x)
                         ^
/usr/include/boost/date_time/time_parsing.hpp: In function ‘time_type boost::date_time::parse_iso_time(const string&, char)’:
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/settings/../../pdf/popplerdirect/workaround/poppler-0.70.1/goo/GooLikely.h:18:25: error: expected unqualified-id before ‘(’ token
 # define likely(x)      (x)
                         ^
In file included from /home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/control/Control.cpp:47:
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/util/serializing/ObjectInputStream.h: At global scope:
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/util/serializing/ObjectInputStream.h:27:39: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  bool read(const char* data, int len) throw (InputStreamException);

[a bunch of dynamic exception specifications (-Wdeprecated) in ObjectInputStream.h occurred]

then...

make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:89: src/CMakeFiles/xournalpp-core.dir/control/Control.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
````

I tried building from @morrolinux's xournalpp fork, https://github.com/morrolinux/xournalpp/commits/master, that had some bugfixes for the app applied to it. I know this isn't the official code, but I wanted to see what would happen with those fixes applied. Interestingly, with the bug fixes for most of the program in place (not directly relating to poppler, except for the workaround), I was able to get it mostly built, but with one error.

At 97% when I execute the "make" step, the error is:
````
[ 96%] Built target xournalpp-core
Scanning dependencies of target xournalpp
[ 97%] Building CXX object src/CMakeFiles/xournalpp.dir/Xournalpp.cpp.o
[ 97%] Linking CXX executable xournalpp
/usr/bin/ld: CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/poppler/XojPopplerDocument.cpp.o: in function `_IntPopplerDocument::_IntPopplerDocument(PDFDoc*)':
/home/siliconninja/Documents/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.cpp:27: undefined reference to `CairoOutputDev::CairoOutputDev()'
/usr/bin/ld: /home/siliconninja/Documents/Linux Compiled Programs/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.cpp:28: undefined reference to `CairoOutputDev::startDoc(PDFDoc*, CairoFontEngine*)'
/usr/bin/ld: CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/poppler/XojPopplerPage.cpp.o: in function `XojPopplerPage::render(_cairo*, bool)':
/home/siliconninja/Documents/Linux Compiled Programs/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:96: undefined reference to `CairoOutputDev::setCairo(_cairo*)'
/usr/bin/ld: /home/siliconninja/Documents/Linux Compiled Programs/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:106: undefined reference to `CairoOutputDev::setTextPage(TextPage*)'
/usr/bin/ld: /home/siliconninja/Documents/Linux Compiled Programs/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:125: undefined reference to `CairoOutputDev::setCairo(_cairo*)'
/usr/bin/ld: /home/siliconninja/Documents/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:126: undefined reference to `CairoOutputDev::setTextPage(TextPage*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/xournalpp.dir/build.make:481: src/xournalpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:392: src/CMakeFiles/xournalpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
````

This information might be helpful for the maintainer(s) of the xournalpp-git AUR package (https://aur.archlinux.org/packages/xournalpp-git/). Reverting to poppler-0.67.0 worked for macxcool.

I tried doing the same using these commands to resolve the 2 other dependencies on poppler and revert:
````
cd /var/cache/pacman/pkg
sudo pacman -U poppler-0.67.0-1-x86_64.pkg.tar.xz poppler-glib-0.67.0-1-x86_64.pkg.tar.xz poppler-qt5-0.67.0-1-x86_64.pkg.tar.xz 
loading packages...
warning: downgrading package poppler (0.70.1-1 => 0.67.0-1)
warning: downgrading package poppler-glib (0.70.1-1 => 0.67.0-1)
warning: downgrading package poppler-qt5 (0.70.1-1 => 0.67.0-1)
resolving dependencies...
looking for conflicting packages...

Packages (3) poppler-0.67.0-1  poppler-glib-0.67.0-1  poppler-qt5-0.67.0-1

Total Installed Size:   7.22 MiB
Net Upgrade Size:      -0.24 MiB

:: Proceed with installation? [Y/n] Y

:: Proceed with installation? [Y/n] y
(3/3) checking keys in keyring                          [------------------------------] 100%
(3/3) checking package integrity                        [------------------------------] 100%
(3/3) loading package files                             [------------------------------] 100%
(3/3) checking for file conflicts                       [------------------------------] 100%
(3/3) checking available disk space                     [------------------------------] 100%
:: Processing package changes...
(1/3) downgrading poppler                               [------------------------------] 100%
(2/3) downgrading poppler-glib                          [------------------------------] 100%
(3/3) downgrading poppler-qt5                           [------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
````

If you haven't already downloaded a copy of these 3 packages on your system (pacman keeps them as cache), you'll need to build them yourself from the packages page on the Arch Linux site at https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/poppler&id=14c4ea4e6fc4a2fcf31c87724560a6ed1877716d using makepkg from the PKGBUILD file and pacman -U (.tar.gz file that was created from makepkg). I'm not uploading mine because they come from a different Linux distro, Manjaro (not Arch), and I want to avoid possible issues with the way that everyone else's Linux distro is set up (.BUILDINFO inside of these packages contains other information about which packages are installed, and needs to be generated manually). (https://bbs.archlinux.org/viewtopic.php?id=226667)

I don't recommend this as a long term solution as there are some security issues and memory leaks fixed in the latest version of poppler (from 0.67.0->0.70.1) (https://poppler.freedesktop.org/releases.html).

I could only compile morrolinux's fork of this app but not the official version of this app, both with swiftgeek's patch applied (except by using the version number 0.67.0 instead of 0.64.0 in ("#include "../../pdf/popplerdirect/workaround/poppler-0.64.0/goo/GooLikely.h") and by having poppler-0.67.0 installed. I think more testing is needed to get a full workaround for 0.67.0 which would help for getting another workaround for 0.70.1.

The error when I run make on the official app is:
````
[ 90%] Building CXX object src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfObjectWriter.cpp.o
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/pdf/popplerdirect/PdfObjectWriter.cpp: In member function ‘void PdfObjectWriter::writeObject(Object*, XojPopplerDocument)’:
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/pdf/popplerdirect/PdfObjectWriter.cpp:88:35: error: invalid conversion from ‘const GooString*’ to ‘GooString*’ [-fpermissive]
   this->writeString(obj->getString());
                     ~~~~~~~~~~~~~~^~
In file included from /home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/pdf/popplerdirect/PdfObjectWriter.cpp:1:
/home/siliconninja/Documents/Linux Compiled Programs/official_xournalpp/xournalpp/src/pdf/popplerdirect/PdfObjectWriter.h:28:30: note:   initializing argument 1 of ‘void PdfObjectWriter::writeString(GooString*)’
  void writeString(GooString* s);
                   ~~~~~~~~~~~^
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:2312: src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfObjectWriter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
````

**Comment by morrolinux** [comment]
I've noticed that building against ´poppler-0.70.1´ won't work, but building against ´poppler-0.67´ and  ´poppler-glib-0.67.0-1´ is no problem

**Comment by andreasb242** [comment]
Hi
I know the problems with the internal Poppler API (but for me it was the only solution to get the PDF export working within a limited time).
The only thing to solve this problem would be to add an official API to poppler, which supports the PDF editing as we need it official. Did you check already if they maybe would accept such a pull request?
(I mailed them sometimes, but this is now 7 Years ago...)
Or the other alternative, create subfolders for different poppler versions (or maybe only defines within the files), and include always the right version. But this would mean to duplicate the code.

Maybe not the right place to discuss, but here I can reach you.

ps. I'm now try to merge the GTK3 Stuff into master, but I don't touch the PDF part.

**Comment by morrolinux** [comment]
@andreasb242 that'd be amazing!

**Comment by andreasb242** [comment]
I use now the standard GLib APi, and export the PDF with Cairo.
The old implementation will still be available with -DADVANCED_PDF_EXPORT_POPPLER=ON
Currently Bookmarks are not exported, but with Cairo 1.16 it will also be possible.
So this should solve a lot of problems I hope.

**I Copy this texts to all related tickets **

**Pull request closed without merging**
