### PR TITLE
Merge release 1.1.2 commits

### PR DESCRIPTION
**Pull request by Technius**
This merges the 1.1.2 version changes (adjusted for master branch).

### CODE REVIEW

**Comment by rolandlo** [comment]
I think you can drop commits 0dce5801fd929b53e6088205300b95a3dcf1ec86, 4b23e88a7c0edde489c8541b735f084c92a5b4eb and ec183123d4692d9a4d07afd8d9ecc2cb07926622, since they have already been merged into master (and don't contribute to the merge commit)

**Comment by Technius** [comment]
That wouldn't make this a proper merge, though.

**Comment by rolandlo** [comment]
Ok, then please proceed without dropping them.

**Comment by Technius** [comment]
Rebased to latest master; this should be fast-forwardable assuming no more commits are pushed to master.

**Pull request merged**
