### PR TITLE
Fixes zoomFitValue update hindering scrolling

### LINKED ISSUE #2138: Not able to scroll notes until I change the zoom
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: Official Windows release

**Describe the bug**
When I open a saved file .xopp there is no way to scroll pages until I change zoom.

**To Reproduce**
With Xournal++ closed, open a saved .xopp file and try to scroll up/down.

**Expected behavior**
I would like to scroll pages without need changing zoom.

**Screenshots of Problem**
This is the default zoom grade when program opens up
image

Decreasing or increasing zoom allows me to scroll pages
image

### LINKED ISSUE #2318: Go back to 'Normal Drawing'
Hi,
when I draw an object (a circle, a box..) I cannot find a fast way to go back to 'normal drawing' (without stroke recognition).
I usually click 'Ctrl+1' two times, but maybe a more direct way exists... if so, please tell me!
Using 'Default Tool' is another possibility but resets also color and pen size
I would suggest adding an entry 'Normal Drawing' in the 'Shape' list, with an associated shortcut

Thanks,
pnc

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #2138 (and its duplicates #1699 and #2066)

The cause of the problem was that for the users that reported the problem the allocation width that was passed to `updateZoomFitValue` did not match with the width of the visible rectangle, which made the zoomFitValue alternate in rapid succession between two different values, which invoked `XournalView::scrollTo` method to keep the top part of the current page visible (if the whole page did not fit on the screen).

It must be checked carefully if we don't reintroduce a bug (#1139, #1132 ) that has been fixed in #1213. So far it seems, it doesn't reintroduce these bugs.

### CODE REVIEW

**Comment by tattsan** [comment]
> Fixes # 2318 (and its duplicates # 1699 and # 2066)
Is #2318  a typo for #2138 ?

**Comment by rolandlo** [comment]
> > Fixes # 2318 (and its duplicates # 1699 and # 2066)
> 
> Is #2318 a typo for #2138 ?

Yes, thanks for pointing it out! I corrected it.

**Comment by Technius** [comment]
Seems like this would also fix the alternating/jumpy zoom problem with pages of different size (#1660, which was previously patched with a hotfix). Do you know if it does?

**Comment by rolandlo** [comment]
I don't know. I can try removing the hotfix and see how it goes.

**Comment by rolandlo** [comment]
I have removed the hotfix and don't get any crashes. The behavior is still the same. In zoomFitMode when scrolling from one page to the other page of different width (which changes the zoom) the page is still scrolled to the top (if it is not fully visible). The comes from the fact that in `XournalView::zoomChanged()` we call `scrollTo(currentPage)` in case of zoomFitMode.

**Comment by Febbe** [comment]
I don't see any crashes, but the Rectangle returned by `getVisibleRect()` seems to be wrong.
I think that was the reason I decided to use the `GdkRectangle` instead of the `getVisibleRect()` function.


To reproduce the behavior: 
maximize the window with view100%, then minimize, then move the mouse into the window: Layout resizes to a wrong layout.

**Comment by rolandlo** [comment]
> I don't see any crashes, but the Rectangle returned by `getVisibleRect()` seems to be wrong.
> I think that was the reason I decided to use the `GdkRectangle` instead of the `getVisibleRect()` function.
> 
> To reproduce the behavior:
> maximize the window with view100%, then minimize, then move the mouse into the window: Layout resizes to a wrong layout.

Not for me. It seems for me `getVisibleRect` always reports the same width and height like the `GdkRectangle` does. Can you create a little gif showing the difference?

**Comment by Febbe** [comment]
Ok seems like I still had the Gtk-Touch-Workaround enabled.
But we want to remove that.

**Comment by rolandlo** [comment]
@Febbe So can I merge it then?

**Comment by Febbe** [comment]
It would be cleaner to remove getVisibleRect and use the correct allocation function however, but that might be to intruding / complicated to fix.

**Comment by Febbe** [comment]
Ok rechecked it on Windows. There, the bug still occur.

**Comment by Febbe** [comment]
bug

**Comment by rolandlo** [comment]
Sorry, but the less dirty hack doesn't work at all (right now). Try inserting pages.

**Comment by Febbe** [comment]
That's strange, I testet exactly that on my Windows machine. I'm gonna take a Look.

**Comment by rolandlo** [comment]
Ok, scrolling after inserting a page works again. But the UI becomes unresponsible (I can't draw for a while) after inserting a few pages.

**Comment by Febbe** [comment]
blocked by #2435

**Comment by Febbe** [comment]
@rolandlo can you review my part. I think we can merge it after #2435 if everything is alright.

**Review by Febbe — APPROVED** [review]

**Comment by rolandlo** [comment]
@Febbe Since #2577 contains this fix wouldn't it be better to close this PR and just proceed with PR #2577

**Comment by Febbe** [comment]
I would do it the other way around. I also think that your and my commits require each other

**Comment by rolandlo** [comment]
What do you mean with "the other way round"? First merge this PR, then PR #2577?

**Comment by Febbe** [comment]
Since both PRS contain the Same content, merge this PR and ignore the new

**Comment by rolandlo** [comment]
They do not contain the same content. This one is just a part of the new one. It contains less additions and deletions, and it doesn't work.

**Comment by Febbe** [comment]
Ok somehow the push didn't work over the git gui, or I made something wrong. Now they are the same. Thanks for the catch.

**Comment by rolandlo** [comment]
Ok, I will review your changes then.

**Comment by rolandlo** [comment]
@Febbe I am happy with your changes. Only minor nitpick: The last comment in `Layout.h` seems incomplete (and contains a typo: `laotPages`)

I have tested the PR on my laptop and on my Pinephone. Even on the Pinephone (with 2 GB RAM) it ran pretty smoothly and things like inserting pages, changing page layout or paper format worked fine.

**Comment by Febbe** [comment]
Merged because @personalizedrefrigerator agreed to rebase his work.

**Pull request merged**
