### PR TITLE
rename PDF Presentation Mode to Progressive Mode

### PR DESCRIPTION
**Pull request by sanette**
due to conflict with other presentation mode.

see https://github.com/xournalpp/xournalpp/pull/2589#issuecomment-751785476

### CODE REVIEW

**Review by Technius — APPROVED** [review]

**Comment by rolandlo** [comment]
@sanette You should rebase on current master and fix the conflicts.

**Comment by mjg** [comment]
> @sanette You should rebase on current master and fix the conflicts.

Let me emphasize: rebase `6dcb6b` onto master; do not merge master into you feature branch. That is, reset your branch to `6dcb6b` (the commit before your merge) and rebase onto master.

**Comment by sanette** [comment]
@mjg sorry I didn't see your post when I was struggling with git... I ended up resetting my branch and manually copying the changes... Is this working?

**Comment by mjg** [comment]
> @mjg sorry I didn't see your post when I was struggling with git... I ended up resetting my branch and manually copying the changes... Is this working?

No problem, I just meant to save you some work. I'm sure the result is fine either way.

**Pull request merged**
