### PR TITLE
Fix text snapping issue

### LINKED ISSUE #3352: Cannot add texts near each other due to snap
**Affects versions :**
- NixOS Linux
- Xournalpp 1.0.20 and 1.1.0
- LibGTK 3.24.30
- nixos packages (`nix-shell -p xournalpp`, `nix-shell -I nixpkgs=channel:nixpkgs-unstable -p xournalpp` for 1.1.0).

**Describe the bug**
Possibly related to [overly snappy behavior](https://github.com/xournalpp/xournalpp/issues/3107), I noticed since a while that snap is applied when placing text as well and it's not possible anymore to place two texts nearby. It seems there is no way to disable this snapping behavior.

**To Reproduce**
1. Open a new document,
2. write a line of text,
3. try inserting a text *just below it*, so that space between the lines is basically non-existing,
3. snap will select the text above instead of adding a new text in the document.

**Expected behavior**
 - Snap doesn't get in the way of creating new texts, 
 - and/or a button allows to disable snap when adding text.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
This issue makes hard to fill forms when lines are nearby each other, especially because while it's possible to modify the font size, it's AFAIK not possible to change the line height. My current workaround is to write lines where possible, then export the document as PDF, open it again and add missing lines so snap doesn't go in the way.

### PR DESCRIPTION
**Pull request by ronandalton**
Fixes #3352.

### CODE REVIEW

**Comment by ronandalton** [comment]
Accidentally included my the commit for the other issue sorry.

**Comment by personalizedrefrigerator** [comment]
> Accidentally included my the commit for the other issue sorry.

Please [`git rebase -i HEAD~2`](https://medium.com/@praveenmuth2/interactive-rebase-the-ultimate-git-superpower-d43b94afbf01) and delete the line with `Fixed 'PDF background missing'...` (then push). Thank you for your contribution!

**Comment by ronandalton** [comment]
Okay I think I finally got it fixed. It took a bit of messing around because I had merged remote changes but it *should* be good now.

**Comment by personalizedrefrigerator** [comment]
This looks good to me! A quick note: This doesn't seem to be an issue with snapping to grid, just with snapping focus to a near-ish textbox.

**Comment by personalizedrefrigerator** [comment]
Merging in 48 hours if there are no objections.

**Pull request merged**
