### PR TITLE
Add CLI option to open PDF in attach mode

### LINKED ISSUE #5223: Relative path (attach mode) for PDF selectable from commandline
### Is Your Feature Request Related to a Problem?

 Relative path (attach mode) has been fixed in PR #2106 . 

### Feature Description

It would be helpful if I can open a PDF-File in attach mode from the filemanager, not only from inside of xournalpp.

With a commandline switch, I can make a second .desktop-Files on Linux  for pdf-Files:

```
[Desktop Entry]
Type=Application

Name=Annotate PDF with Xournal++
Comment=Take handwritten notes

Exec=xournalpp SWITCH-ATTACHMODE %f 
SingleMainWindow=false
StartupWMClass=com.github.xournalpp.xournalpp
Terminal=false
StartupNotify=true
MimeType=application/pdf;
Icon=com.github.xournalpp.xournalpp
Categories=Office;GNOME;GTK;

```

We use xournalpp at school. This feature would make the life  of students and teachers easier a lot.

### Alternative Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes  #5223

### CODE REVIEW

**Comment by rolandlo** [comment]
@helge This PR needs some refinement in the messaging, but should basically do what you requested in #5228. Could you please download the (Linux) installer above and try it with the new `attach-mode` command line option? Example:
```term
xournalpp --attach-mode input.pdf
```

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg1ODkvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg1ODkvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg1ODkvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg1ODkvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 22.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg1ODkvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMi4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by tobiasBora** [comment]
I'm lost, I also really need this (quite old) PR, but I can't find it in the recent releases even if they are present in master… What's happening?

**Comment by rolandlo** [comment]
Recent releases like 1.2.4 are not based on master, but on 1.2.0 plus some bugfixes. So it's only in the nightly build, not in the stable version yet.

**Comment by tobiasBora** [comment]
I see, thanks!

**Pull request merged**
