### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by rolandlo**
This is #2689 squashed into one commit and rebased. Some small problems in `es_ES.po` had to be fixed.

### CODE REVIEW

**Comment by Technius** [comment]
Do we also want to handle #3049 here?

**Comment by rolandlo** [comment]
> Do we also want to handle #3049 here?

As of now I deleted the `it_IT.po` file, but that doesn't prevent it from being regenerated.

**Comment by rolandlo** [comment]
#3049 has been fixed on Crowdin via Language mappings. Now there won't be `it_IT`, but only `it` (which was outdated and is now up to date).  Same for German, Czech, Polish and Chinese simplified. There may be other languages that should maybe be treated like that, though, like for example French (`fr_FR`, which should simply be `fr`, I think).

**Comment by rolandlo** [comment]
Here is my suggestion on how to use language and regional codes and on what to remove:

Remove those with 0% translations (from Crowdin):
en_US.po (US English)
af_ZA.po (Afrikaans)
sr_SP.po   (Serbian)
tlh_AA.po (Klingon)
uk_UA.po  (Ukrainian)
sat_IN.po (Santali)  
sl_SI.po  (Slovenian)

Already renamed to language code only:
pl.po  (Polish)
it.po  (Italian)
cs.po   (Czech)
de.po  (German)       
zh.po  (Chinese simplified)

Rename to language code only:
hr_HR.po   -> hr.po (Croatian)
no_NO.po  -> no.po (Norwegian)
ar_SA.po  -> ar.po (Arabic)
es_ES.po  -> es.po (Spanish)
hu_HU.po  -> hu.po (Hungarian)
ca_ES.po -> ca.po (Catalan)      
eu_ES.po  -> eu.po (Basque)
id_ID.po  -> id.po (Indonesian)
sv_SE.po  -> sv.po (Swedish)
fi_FI.po -> fi.po (Finnish) 
th_TH.po  -> th.po (Thai)
fr_FR.po  -> fr.po (French)
ja_JP.po -> ja.po (Japanese)
da_DK.po  -> da.po (Danish)      
gl_ES.po  -> gl.po (Galician)
ko_KR.po  -> ko.po (Corean)
ro_RO.po  -> ro.po (Romanian) 
tr_TR.po   -> tr.po (Turkish)
he_IL.po -> he.po (Hebrew)   
ru_RU.po   -> ru.po (Russian)
el_GR.po  -> el.po (Greek)       
hi_IN.po  -> hi.po (Hindi)
nl_NL.po -> nl.po (Dutch) 
vi_VN.po -> vi.po (Vietnamese)

Leave with language and regional code:
pt_BR.po   (Portuguese, Brazilian)
pt_PT.po   (Portuguese)
zh_HK.po (Chinese Traditional, Hongkong)
zh_TW.po (Chinese Traditional)

**Comment by rolandlo** [comment]
@Technius @LittleHuba 
Any opinion on my suggestion above to rename the .po-files (via language mapping in Crowdin) and remove .po-files without translations?
It is based on the observations that .mo-files usually are stored without country codes (see for example [Inkscape repo](https://gitlab.com/inkscape/inkscape/-/tree/INKSCAPE_0_92_3/po) and loook at the contents of `/usr/share/locale/` on your own Linux system)

**Comment by LittleHuba** [comment]
There should be a flag in Crowdin that automatically uses the translations of a dialect for the main language if there are none specified for the main language. Possibly this setting also creates the correct filenames?

Should this not be the case, I'm not really happy with this "fix" as it will lead to major problems should we ever get translations for any two different dialects of a language.

**Comment by rolandlo** [comment]
> There should be a flag in Crowdin that automatically uses the translations of a dialect for the main language if there are none specified for the main language. Possibly this setting also creates the correct filenames?
> 
> Should this not be the case, I'm not really happy with this "fix" as it will lead to major problems should we ever get translations for any two different dialects of a language.

It's vice versa. You must mean this flag:
grafik

I think it wouldn't make sense to merge several dialects into the main language.

We already have different dialects of a language, like `Portuguese (40% translated)` and Portuguese, Brazilian` (99% translated). 
Also we have Chinese simplified (100% translated), Chinese traditional (22% translated), and Chinese traditional, Hongkong (27% translated). It's always possible to change back the language mapping. What scenario are you thinking about, that would lead to major problems?

**Comment by LittleHuba** [comment]
Ah yeah that was the one I had in mind. Unfortunately not correctly as it seems.

Simply changing the mapping can become problematic once we actually get into the area of different translations for different dialects. I'm not quite sure if that will ever be the case. Hence, I would like a better solution if there is one. 

As I do not know such a solution (except the one that was obviously wrong) I give my okay for the mapping if nobody else comes up with a better solution.

Another problem is that we need to keep this additional step in mind for every new language we unlock...

**Comment by rolandlo** [comment]
> Another problem is that we need to keep this additional step in mind for every new language we unlock...

That's true, but even if we forget it once, we can still do it later.

**Comment by rolandlo** [comment]
This is now the list of languages:

grafik

Merging in 24 hours, if no objections are raised.

**Pull request merged**
