### PR TITLE
prfreeze: Apply clang format on project

### PR DESCRIPTION
**Pull request by lehmanju**

### CODE REVIEW

**Comment by lehmanju** [comment]
well nvm, better do this at the end

**Comment by veecue** [comment]
I have the impression, we should do this before the major code refactors because the clang format applied pipeline will fail otherwise

**Comment by Febbe** [comment]
Nah we can ignore the pipeline till the end and apply the format afterwards

**Comment by Febbe** [comment]
We also need to discuss, how the format shall look like.

**Pull request closed without merging**
