### PR TITLE
More natural ctrl+scroll zooming

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
## Summary
 * Ctrl+scroll and step part of @redweasel's #2837

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
@rolando Do you think this should go into 1.1.1 or 1.2.0? It's not quite a new feature, but it does change the behavior of an existing tool.

**Comment by rolandlo** [comment]
> @rolando Do you think this should go into 1.1.1 or 1.2.0? It's not quite a new feature, but it does change the behavior of an existing tool.

I would rather include it in 1.1.1.

**Comment by personalizedrefrigerator** [comment]
Merging in 48 hours unless there are objections.

**Review by LittleHuba — CHANGES_REQUESTED** [review]
Please remove the code duplication.

**Review by LittleHuba — APPROVED** [review]

**Comment by LittleHuba** [comment]
LGTM. Merge in 24 hours.

**Pull request merged**
