### PR TITLE
chore: Replace `sprintf` with `PlaceholderString` in `AboutDialog.cpp`

### PR DESCRIPTION
**Pull request by hyperupcall**
Removes another instance of using raw C arrays

### CODE REVIEW

**Review by rolandlo — APPROVED** [review]
LGTM

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised.

**Comment by rolandlo** [comment]
> Why not replace with libfmt alltogether? Or are we waiting for C++20 `std::format`?

I think waiting for C++20 `std::format` is preferable, since adding a dependency tends to create issues.

**Comment by Technius** [comment]
I disagree with waiting for C++20; I think fmtlib is pretty popular and should be available on most distros. In contrast, it will take a while for all compilers to fully support C++20. It may make sense to add fmtlib for 1.3.0.

**Comment by rolandlo** [comment]
Thanks @hyperupcall for the PR. 
We will discuss if we should add fmtlib for 1.3.0. First there is 1.2.0 to come.

**Pull request merged**
