### PR TITLE
Select the language from settings

### PR DESCRIPTION
**Pull request by aDogCalledSpot**
If the user hasn't set up locales properly, or wants a different language due to any reason, it would be easiest if they can select their preferred language from a drop-down menu.

This PR:
 - adds a GUI for selecting the language (depicted below)
 - searches  for the available languages by searching any directories in PACKAGE_LOCALE_DIR for xournalpp.mo files
 - writes the selected language to the config
 - automatically sets the previously selected language as the default in the menu

image
image

Currently untested on macOS and working on a few banal translations (as not offering translations for the language settings would be a bit ironic).

Currently available translations:
 - German
 - Russian
 - Spanish
 - French

Should help in cases such as https://github.com/xournalpp/xournalpp/issues/2181.

### CODE REVIEW

**Comment by aDogCalledSpot** [comment]
If someone could make sure this works on macOS, that would be fantastic!

**Comment by MichelReims** [comment]
It's not for windows ?

**Comment by aDogCalledSpot** [comment]
> It's not for Windows?

Of course it's for Windows. Why do you believe it isn't?

**Comment by MichelReims** [comment]
Because I have compiled the last version of xournalpp and there is not the language menu

**Comment by aDogCalledSpot** [comment]
> Because I have compiled the last version of xournalpp and there is not the language menu

This is a pull request. Maintainers of this repository will have a look over it and will decide to include this code into the application if it suits them. They may still want me to change some things first.

You can either wait a few days until it is merged into the master branch, or if you want to try it out quickly or provide feedback for me you can clone the branch in which I am working on this. For this you would go to the directory where you have cloned this repo and do the following:

```
git remote add aDogCalledSpot git@github.com:aDogCalledSpot/xournalpp.git
git checkout aDogCalledSpot/language_select
```
and recompile.

You may want to read up pull requests in general here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests.

**Review by LittleHuba — APPROVED** [review]
Looks good to me!
If you do not have anything you want to fix before we merge it I think this is good to go!

**Comment by aDogCalledSpot** [comment]
I think it's ready

**Comment by Febbe** [comment]
The code look very good to me, I just have to test it this time.

**Comment by Febbe** [comment]
Also @LittleHuba I think the .po files do not belong to the commits arent they?

**Comment by LittleHuba** [comment]
If I remember correctly it doesn't matter. Crowd in should update the database accordingly as soon as the files are committed.

**Comment by LittleHuba** [comment]
But maybe it is better to remove them and do this in crowdin.

**Comment by aDogCalledSpot** [comment]
I dropped the commit with the translations. How should I go about adding them back?

**Comment by Febbe** [comment]
Your code or automatic generated translations?

**Comment by MichelReims** [comment]
I have used an automatic compilation

**Comment by aDogCalledSpot** [comment]
> Your code or automatic generated translations?

My own few translations for the new selection (which are no longer part of the PR).

**Comment by Febbe** [comment]
If you force pushed they are gone😕

**Comment by MichelReims** [comment]
I don't know how to push

**Comment by MichelReims** [comment]
The last automatic nightly release has the same problem

**Comment by aDogCalledSpot** [comment]
> If you force pushed they are goneconfused

I still have them locally, don't worry.

**Comment by aDogCalledSpot** [comment]
I've signed up for the Crowdin project and everything looks really straightforward :sweat_smile: 

I'll make sure to update the translations I had there as soon as this is merged.

**Comment by Febbe** [comment]
Ok I just tried to test this on windows. Currently it does not work when executet in the build directory. Also I think the error, when the directory could not be opened should be displayed in a text field below the language selection not as popup. 
Or it should be only displayed with a g_warning. The warning on top does not tell me whats effected of the error.

**Comment by Febbe** [comment]
Ok, tested it after installation and it worked fine, but a restart is required. Can this be changed?

**Comment by aDogCalledSpot** [comment]
I don't think it would be possible without restarting as some translated strings are either used in constructors (e.g. ButtonConfigGUI or PageTypeHandler). Even in cases where such things can be changed (ToolMenuHandler::initToolItems) you would need access to the corresponding object which would be an unnecessary passing through of various handles for a very small gain at best and breaks encapsulation at worst.

Also the things which are handled by glib don't seem to be affected; things like "OK" and "Cancel" will stay in the previous language even when the rest of the dialogue is in the new language.

Saving the one restart seems like very little gain for a large amount of work which may not even work properly in the end.

**Comment by Febbe** [comment]
Then maybe it would be good to show a hint to the user. Either over an popup or a text field.

**Comment by aDogCalledSpot** [comment]
It says it above the dropdown "Select language (requires restart)" and can be seen in my screenshots. I could also put change it to just say "Select language" and then have the field underneath say "Language (requires restart)" instead of just "Language" if you think that would be clearer.

**Comment by Febbe** [comment]
Yes that's fine :). Can you clean up your history? I think we can merge it now. You can also add yourself to the list of authors if you want.

**Comment by aDogCalledSpot** [comment]
Ready for merge.

**Comment by Febbe** [comment]
Thank you fer that PR it was an issue for many people :).

**Pull request merged**
