### PR TITLE
Downsize all action icons via svgo

### LINKED ISSUE #3224: regression when window switching/rescaling
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 20.04 LTS
 - (Linux only) Desktop environment: I3-X11
 - Which version of libgtk do you use 3.22.30 /(3.24.20 when built from source)
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     1a60605e(nightly build 11 july 2021)
 - Installation method: appimage

**Describe the bug**
using I3 as my WM I have noticed some massive lags with switching to and from the latest version of nightly. 
It takes about a second to load the window when switching to it. the same goes if it's re-scaled(closing another window beside it).
I can also produce it by force-closing the about menu(clsing it by keyboard comand, not be close button), but not while opening it. 
note moving it around the same workspace(without changing the size) works without a problem. 

I experience similar issues while switching to and from graphics heavy games, that aren't really made for re-scaling their windows.

this behavior was introduced between nightly 20210615 and the latest one(20210711)

**To Reproduce**
1) open latest nightly in I3
2a) remove windows on the same workspace.
2b) open the about menu and then close it again.
2c) switch to the workspace xournalpp is on from a different one.
3) see xournalpp behaving slowly. and leaving black bars for a couple of seconds.

**Expected behavior**
Xournalpp should immediately rescale windows and update it's content. 
the corect behaviour is already happening in stable as well as in nightly 20210615(and before)

**Screenshots of Problem**

**Additional context**
I would be happy to try all the nightly build between 6 of june and today to find the one that introduced the problem, should that be needed.

### PR DESCRIPTION
**Pull request by rolandlo**
The action icons were downsized using the command
svgo -f ./actions ./actions_new

Fixes #3224 and related performance issues

@Fatih20 As noticed in #3224 the large file sizes of the action icons resulted in performance problems on some systems. Using the tool [svgo](https://github.com/svg/svgo#why) reduced the file sizes drastically. For instance the 64 scalable action icons in the dark theme folder combined went down in file size from 13 MB to 375 KB, which is less than 3% of the original size. As you see from the screenshots below, there is no noticeable difference/quality loss from reducing the file size. Moreover the original icons will always remain in the commit history, if they should be needed again. So please tell me, are you fine with the downsizing?

Original:
dark_original

Downsized:
dark_svgo

Original:
light_original

Downsized:
light_svgo

Original:
page-spinner_original

Downsized:
page-spinner_svgo

### CODE REVIEW

**Comment by Technius** [comment]
Looks fine to me; I would just merge this as-is since it's a technical and not an artistic change.

**Comment by rolandlo** [comment]
@Technius One question though:Would it be advantageous to use the `--pretty` option to have the svg's more readable (while not loosing too much in file size compression):

As an example: `xopp-document-save.svg`

with `--pretty` option: 
```svg
<svg viewBox="0 0 5.821 5.821" height="22" width="22" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="g">
            <stop offset="0" style="stop-color:#fff;stop-opacity:1"/>
            <stop offset=".2" style="stop-color:#fff;stop-opacity:.23529412"/>
            <stop offset=".783" style="stop-color:#fff;stop-opacity:.15686275"/>
            <stop offset="1" style="stop-color:#fff;stop-opacity:.39215687"/>
        </linearGradient>
        <linearGradient id="e">
            <stop offset="0" style="stop-color:#3689e6;stop-opacity:1"/>
            <stop offset="1" style="stop-color:#64baff;stop-opacity:1"/>
        </linearGradient>
        <linearGradient id="a">
            <stop offset="0" style="stop-color:#3689e6;stop-opacity:1"/>
            <stop offset="1" style="stop-color:#64baff;stop-opacity:1"/>
        </linearGradient>
        <linearGradient id="f">
            <stop offset="0" style="stop-color:#f4f4f4;stop-opacity:1"/>
            <stop offset="1" style="stop-color:#dbdbdb;stop-opacity:1"/>
        </linearGradient>
        <linearGradient id="d">
            <stop offset="0" style="stop-color:#efdfc4;stop-opacity:1"/>
            <stop offset="1" style="stop-color:#e9c998;stop-opacity:1"/>
        </linearGradient>
        <linearGradient id="c">
            <stop style="stop-color:#f9f9f9;stop-opacity:1" offset="0"/>
            <stop style="stop-color:#d8d8d8;stop-opacity:1" offset="1"/>
        </linearGradient>
        <linearGradient id="b">
            <stop style="stop-color:#efdfc4;stop-opacity:1" offset="0"/>
            <stop style="stop-color:#e7c591;stop-opacity:1" offset="1"/>
        </linearGradient>
        <linearGradient gradientTransform="translate(144.694 200.32) scale(.35276)" gradientUnits="userSpaceOnUse" y2="-20.602" x2="-12.979" y1="18.4" x1="-12.979" id="i" xlink:href="#e"/>
        <linearGradient xlink:href="#g" id="j" x1="140.116" y1="192.258" x2="140.116" y2="198.872" gradientUnits="userSpaceOnUse"/>
        <linearGradient xlink:href="#e" id="h" gradientUnits="userSpaceOnUse" gradientTransform="translate(144.694 200.32) scale(.35276)" x1="-12.979" y1="18.4" x2="-12.979" y2="-20.602"/>
        <clipPath clipPathUnits="userSpaceOnUse" id="k">
            <path style="fill:url(#h);fill-opacity:1;stroke-width:.0110013" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z"/>
        </clipPath>
    </defs>
    <path style="fill:url(#i);fill-opacity:1;stroke-width:.0110013" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z" transform="translate(-136.94 -192.787)"/>
    <path d="M138.198 193.052v1.448c0 .073.059.139.137.139h2.9a.14.14 0 0 0 .138-.139v-1.448h-1.938z" style="fill:#fafafa;fill-opacity:1;stroke:none;stroke-width:.264583;stroke-miterlimit:4;stroke-dasharray:none" transform="translate(-136.94 -192.787)"/>
    <path style="fill:none;fill-opacity:1;stroke-width:.26458333;stroke:#0d52bf;stroke-opacity:1;stroke-miterlimit:4;stroke-dasharray:none" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z" transform="translate(-136.94 -192.787)"/>
    <path d="M138.198 198.343v-1.53a.14.14 0 0 1 .137-.138h2.9a.14.14 0 0 1 .138.139v1.53h-1.938z" style="fill:#fafafa;fill-opacity:1;stroke:none;stroke-width:.264583;stroke-miterlimit:4;stroke-dasharray:none" transform="translate(-136.94 -192.787)"/>
    <path d="M138.198 198.343v-1.53a.14.14 0 0 1 .137-.138h2.9a.14.14 0 0 1 .138.139v1.53h-1.938z" style="fill:none;fill-opacity:1;stroke:#0d52bf;stroke-width:.264583;stroke-miterlimit:4;stroke-dasharray:none" transform="translate(-136.94 -192.787)"/>
    <path d="M138.198 193.052v1.448c0 .073.059.139.137.139h2.9a.14.14 0 0 0 .138-.139v-1.448h-1.938z" style="fill:#fafafa;fill-opacity:1;stroke:#0d52bf;stroke-width:.264583;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" transform="translate(-136.94 -192.787)"/>
    <path style="fill:none;fill-opacity:1;stroke-width:.52916666;stroke:url(#j);stroke-opacity:1;stroke-miterlimit:4;stroke-dasharray:none" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z" clip-path="url(#k)" transform="translate(-136.94 -192.787)"/>
</svg>
```

without `--pretty` option (it's just one long line of text, 4193 bytes compared to 4632 bytes with the `--pretty` option)

```svg
<svg viewBox="0 0 5.821 5.821" height="22" width="22" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g"><stop offset="0" style="stop-color:#fff;stop-opacity:1"/><stop offset=".2" style="stop-color:#fff;stop-opacity:.23529412"/><stop offset=".783" style="stop-color:#fff;stop-opacity:.15686275"/><stop offset="1" style="stop-color:#fff;stop-opacity:.39215687"/></linearGradient><linearGradient id="e"><stop offset="0" style="stop-color:#3689e6;stop-opacity:1"/><stop offset="1" style="stop-color:#64baff;stop-opacity:1"/></linearGradient><linearGradient id="a"><stop offset="0" style="stop-color:#3689e6;stop-opacity:1"/><stop offset="1" style="stop-color:#64baff;stop-opacity:1"/></linearGradient><linearGradient id="f"><stop offset="0" style="stop-color:#f4f4f4;stop-opacity:1"/><stop offset="1" style="stop-color:#dbdbdb;stop-opacity:1"/></linearGradient><linearGradient id="d"><stop offset="0" style="stop-color:#efdfc4;stop-opacity:1"/><stop offset="1" style="stop-color:#e9c998;stop-opacity:1"/></linearGradient><linearGradient id="c"><stop style="stop-color:#f9f9f9;stop-opacity:1" offset="0"/><stop style="stop-color:#d8d8d8;stop-opacity:1" offset="1"/></linearGradient><linearGradient id="b"><stop style="stop-color:#efdfc4;stop-opacity:1" offset="0"/><stop style="stop-color:#e7c591;stop-opacity:1" offset="1"/></linearGradient><linearGradient gradientTransform="translate(144.694 200.32) scale(.35276)" gradientUnits="userSpaceOnUse" y2="-20.602" x2="-12.979" y1="18.4" x1="-12.979" id="i" xlink:href="#e"/><linearGradient xlink:href="#g" id="j" x1="140.116" y1="192.258" x2="140.116" y2="198.872" gradientUnits="userSpaceOnUse"/><linearGradient xlink:href="#e" id="h" gradientUnits="userSpaceOnUse" gradientTransform="translate(144.694 200.32) scale(.35276)" x1="-12.979" y1="18.4" x2="-12.979" y2="-20.602"/><clipPath clipPathUnits="userSpaceOnUse" id="k"><path style="fill:url(#h);fill-opacity:1;stroke-width:.0110013" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z"/></clipPath></defs><path style="fill:url(#i);fill-opacity:1;stroke-width:.0110013" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z" transform="translate(-136.94 -192.787)"/><path d="M138.198 193.052v1.448c0 .073.059.139.137.139h2.9a.14.14 0 0 0 .138-.139v-1.448h-1.938z" style="fill:#fafafa;fill-opacity:1;stroke:none;stroke-width:.264583;stroke-miterlimit:4;stroke-dasharray:none" transform="translate(-136.94 -192.787)"/><path style="fill:none;fill-opacity:1;stroke-width:.26458333;stroke:#0d52bf;stroke-opacity:1;stroke-miterlimit:4;stroke-dasharray:none" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z" transform="translate(-136.94 -192.787)"/><path d="M138.198 198.343v-1.53a.14.14 0 0 1 .137-.138h2.9a.14.14 0 0 1 .138.139v1.53h-1.938z" style="fill:#fafafa;fill-opacity:1;stroke:none;stroke-width:.264583;stroke-miterlimit:4;stroke-dasharray:none" transform="translate(-136.94 -192.787)"/><path d="M138.198 198.343v-1.53a.14.14 0 0 1 .137-.138h2.9a.14.14 0 0 1 .138.139v1.53h-1.938z" style="fill:none;fill-opacity:1;stroke:#0d52bf;stroke-width:.264583;stroke-miterlimit:4;stroke-dasharray:none" transform="translate(-136.94 -192.787)"/><path d="M138.198 193.052v1.448c0 .073.059.139.137.139h2.9a.14.14 0 0 0 .138-.139v-1.448h-1.938z" style="fill:#fafafa;fill-opacity:1;stroke:#0d52bf;stroke-width:.264583;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" transform="translate(-136.94 -192.787)"/><path style="fill:none;fill-opacity:1;stroke-width:.52916666;stroke:url(#j);stroke-opacity:1;stroke-miterlimit:4;stroke-dasharray:none" d="M137.45 193.051c-.126 0-.25.09-.25.203v4.877c0 .12.1.212.226.212h4.85c.126 0 .226-.099.226-.212v-4.301a.216.216 0 0 0-.067-.152l-.596-.57a.17.17 0 0 0-.136-.057z" clip-path="url(#k)" transform="translate(-136.94 -192.787)"/></svg>
```

**Comment by Fatih20** [comment]
I don't see any problem with this.

**Comment by Technius** [comment]
> @Technius One question though:Would it be advantageous to use the `--pretty` option to have the svg's more readable (while not loosing too much in file size compression):

I don't think it matters; almost no one is going to be opening up the svg source, and anyone who does will probably be prepared to use some sort of formatter anyways.

By the way, I noticed that most of the file size bloat is due to an excessive number of gradients. It looks like svgo is able to reduce file sizes so drastically by combining similar gradients together.

**Comment by rolandlo** [comment]
> I don't see any problem with this. You should probably still have the original in the repo, so any future contributor can work with the original unoptimized icon. Only after that the svg is optimized for the end-user.

Yes, the original will still be in the commit history. Merging in 24 hours if no objections are raised.

**Comment by rolandlo** [comment]
By the way it turns out that the lag on MacOS BigSur is also related to the icons rendering. If I choose the empty toolbar there is no significant lag. So this PR will also benefit BigSur users. There is still some lag, but it is definitely quite a bit smaller.

**Pull request merged**
