### PR TITLE
Misspell

### PR DESCRIPTION
**Pull request by MisterDA**
Hi! Passing by, I’m just fixing some misspellings.

### CODE REVIEW

**Comment by rolandlo** [comment]
Thanks for fixing misspellings. Take care to keep consistency throughout the files. Currently it does not compile:
```
../src/util/audio/VorbisProducer.cpp: In lambda function:
../src/util/audio/VorbisProducer.cpp:30:32: error: ‘class AudioQueue<float>’ has no member named ‘aquire_lock’; did you mean ‘acquire_lock’?
         auto lock = audioQueue.aquire_lock();
```

**Comment by rolandlo** [comment]
Is this PR ready or did you want to add more to it?

**Comment by MisterDA** [comment]
I believe that the PR is ready, I’m sorry I let that compilation failure slip in.

**Review by rolandlo — APPROVED** [review]
LGTM

**Comment by rolandlo** [comment]
Ok, I have merged it. Thanks again.

**Pull request merged**
