### PR TITLE
Add CLI-option to save out.xopp file for in.pdf

### LINKED ISSUE #2204: Add command line option for importing pdf
**Is your feature request related to a problem? Please describe.**

It would be nice to have an option for importing a pdf and saving as a `.xopp` file. I'm grading pdf submissions so I'm dealing with sets of 50+ separate pdfs at a time. For my workflow it would be a lot faster if I could go ahead and save all of them as a xopp file instead of having to import and save 50+ times.

**Describe the solution you'd like**

An application option along the lines of `xournalpp --import-pdf input.pdf output.pdf.xopp` or automatically naming the output to be `{input-filename}.xopp`

**Describe alternatives you've considered**

I guess some option to import all pdfs in a folder and save as a `.xopp` file in the GUI would be fine too, but I feel like that's not worth adding another UI option.

**Additional context**

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #2204

### CODE REVIEW

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg5MjkvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg5MjkvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg5MjkvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg5MjkvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 22.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg5MjkvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMi4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by tmoerschell** [comment]
This is cool!


My  2 cents: 

The option shouldn't have a mandatory argument. If none is provided, simply append .xopp to the input file name. 

Reword the usage/help: currently feels like the option takes two arguments when it really only takes one. Also I'm much more likely going to use: 
```bash
xournalpp FILE.pdf --save-document FILE.xopp  # because input->output from left to right feels more natural to me
```
So for the usage, I'd see something along the lines of:
```bash
  --save-document[=XOPPFILE]        Saves a xopp-file with the background PDF specified as FILE
                                 Usage: xournalpp in.pdf --save-document out.xopp
```


And now a request that could be a little more complex: 
Allow multiple conversions at once, so you could write for example:
```bash
xournalpp *.pdf --save-document
```
and not care about bash loops anymore. Then in turn if you accept multiple input file names, you'd need multiple output file names... The most simple option would be to ignore the output file name and stick with the default when multiple input files are given.

**Comment by rolandlo** [comment]
> The option shouldn't have a mandatory argument. If none is provided, simply append .xopp to the input file name.
> 
> Reword the usage/help: currently feels like the option takes two arguments when it really only takes one. Also I'm much more likely going to use:
> 
> ```shell
> xournalpp FILE.pdf --save-document FILE.xopp  # because input->output from left to right feels more natural to me
> ```
> 
> So for the usage, I'd see something along the lines of:
> 
> ```shell
>   --save-document[=XOPPFILE]        Saves a xopp-file with the background PDF specified as FILE
>                                  Usage: xournalpp in.pdf --save-document out.xopp
> ```
> 
> And now a request that could be a little more complex: Allow multiple conversions at once, so you could write for example:
> 
> ```shell
> xournalpp *.pdf --save-document
> ```
> 
> and not care about bash loops anymore. Then in turn if you accept multiple input file names, you'd need multiple output file names... The most simple option would be to ignore the output file name and stick with the default when multiple input files are given.

Your ideas are interesting, but I think that this PR should implement a command line option that works consistently with `export-pdf` and `export-img`. They also have a mandatory file argument. Also it's not clear if `foo.pdf` should be saved to `foo.pdf.xopp` by default or to `foo.xopp`.

Furthermore currently `xournalpp` only accepts one filename as an input file and it would be strange to have this changed just for `--save-document` (which I renamed to `--save` in the meantime).

If multiple input file names should be supported, then not only with `--save`, but also with other options (and without option).

I have adjusted the help entry, mostly following your suggestion and trying to be consistent with the `export-pdf` and `export-img` options.

grafik

**Comment by tmoerschell** [comment]
LGTM. The last commit doesn't look directly related did it slip onto the branch or was it intentional?

**Comment by rolandlo** [comment]
Thanks for the review @tmoerschell 
I dropped the last commit and will open a PR with it based on release-1.2.

Merging in 48 hours if no objections are raised.

**Comment by jonjampen** [comment]
Thanks for implementing this useful feature!
Are there any news on when this feature will be included in an official release?

**Pull request merged**
