### PR TITLE
[luaAPI] add a declaration file

### PR DESCRIPTION
**Pull request by atticus-sullivan**
The declaration file can be used with
[luaLS](https://github.com/LuaLS/lua-language-server)

See #5555 for previous discussion and short example of usage in neovim.

TODOs:
- [ ] do we really want to place the file side-by-side with the implementation of the API?
- [ ] note about this on the website -> will be a PR on the other repository (also note that this is not the proper/complete documentation, for this one needs to have a look at the (comments in the) API implementation)
- [ ] Check out how to configure this generally

### CODE REVIEW

**Comment by atticus-sullivan** [comment]
About configuration:

I just checked placing
```json
{
  "workspace.library": ["../../src/core/plugin/luapi_application.def.lua"],
}
```
as `.luarc.json` in the directory of the plugin. Turns out this is working, at least for me (in neovim).

The thing I'm really unsure about is what the term `workspace` refers to.
1. In **neovim** a language server is associated with a `root directory` which I believe to be the same as the `workspace` referenced in the [luaLS documentation](https://github.com/LuaLS/lua-language-server/wiki/Settings#workspacelibrary) but I'm not completely sure.
I'm setting this via `root_dir = function(fname) return util.root_pattern('main.lua')(fname) or util.find_git_ancestor(fname) end` but others might set it differently (or don't use `main.lua`) which would result in different (relative) paths.
2. In **vscode** the workspace maybe is something like the path where you opened the project (I really have no experience with vscode)? This also would result in different paths, as someone just working on a plugin might just open the directory of the plugin while others open the directory of the whole project.

So maybe the best way is to explain how to set this config, not provide a default one in the example plugin and also not add the configs to git (-> `gitignore`).

Can someone test the paths with vscode? (or knows it since I think the term workspace comes from the vscode world here)

**Comment by atticus-sullivan** [comment]
> Also, there must already be such a script out there...

I'd expect one as well, but on my first fast research I didn't found one (yet). Maybe people are only using such a script in other projects and don't publish it as separate script.

But I agree, such an extraction script would make keeping declaration file and source in sync much easier.

**Comment by rolandlo** [comment]
> > * do we really want to place the file side-by-side with the implementation of the API?
> 
> If we add the comments to the luapi_application.h in the somewhat standard format we have in parts of the code, e.g.
> 
Would the examples we have for applying the Lua library functions go into the @brief then? Or would you throw them away?

**Comment by atticus-sullivan** [comment]
Just tried naively running doxygen to parse the doc-comments and get the result in a machine readable format. The output for one function looks something like this:

<details><summary>doxygen xml</summary>

```xml
      <memberdef kind="function" id="luapi__application_8h_1a3fb533faf6fe9e9a8daf0c47ad5f0507" prot="public" static="yes" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>int</type>
        <definition>static int applib_getImages</definition>
        <argsstring>(lua_State *L)</argsstring>
        <name>applib_getImages</name>
        <param>
          <type>lua_State *</type>
          <declname>L</declname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para>Puts a Lua Table of the Images (from the selection tool / selected layer) onto the stack. Is inverse to app.addImages</para>
<para>Required argument: type (&quot;selection&quot; or &quot;layer&quot;)</para>
<para>Example: local images = app.getImages(&quot;selection&quot;)</para>
<para>return value: { { [&quot;x&quot;] = number, [&quot;y&quot;] = number, [&quot;width&quot;] = number, (width when inserted into Xournal++) [&quot;height&quot;] = number, (height when inserted into Xournal++) [&quot;data&quot;] = string, [&quot;format&quot;] = string, [&quot;imageWidth&quot;] = integer, [&quot;imageHeight&quot;] = integer, }, { ... }, ... } </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="src/core/plugin/luapi_application.h" line="2633" column="12" bodyfile="src/core/plugin/luapi_application.h" bodystart="2633" bodyend="2691"/>
      </memberdef>
```

</details>


<details><summary>for the following doc-comment</summary>

```cpp
/**
 * Puts a Lua Table of the Images (from the selection tool / selected layer) onto the stack.
 * Is inverse to app.addImages
 *
 * Required argument: type ("selection" or "layer")
 *
 * Example: local images = app.getImages("selection")
 *
 * return value:
 * {
 *     {
 *         ["x"] = number,
 *         ["y"] = number,
 *         ["width"] = number,    (width when inserted into Xournal++)
 *         ["height"] = number,   (height when inserted into Xournal++)
 *         ["data"] = string,
 *         ["format"] = string,
 *         ["imageWidth"] = integer,
 *         ["imageHeight"] = integer,
 *     },
 *     {
 *         ...
 *     },
 *     ...
 * }
 * @param type string "selection" or "layer"
 * @return {path:string, data:string, x:number, y:number, maxHeight:number, maxWidth:number, aspectRatio:boolean}[] images
 */
```

</details>

Issues:
- `@return` and `@param` don't seem to be recognized.

Most probably doxygen tries to link the doc-comment to the code, but the arguments do not match.

----

So then maybe I'd go the way of manually writing some sort of parser which checks for the functions found by e.g.
```bash
sed -n '/static const luaL_Reg applib/,${/applib_.*/{s/^[[:space:]]*{"\(.*\)",[[:space:]]*\(applib_.*\)},/\1\t\2/p}}' src/core/plugin/luapi_application.h
```

Searching for the functions which shall be checked isn't too hard (assuming `static const luaL_Reg applib` is always almost at the bottom of the file) using shell utilities like `sed`.
The next step I think would be to obtain the lines/the comment preceeding the respective function declaration which we are able to simply copy to the declaration file (if we write this doc-comment the right way). A single pass over the lines checking for `/**`, collecting following lines until `*/` and checking if the next line declares a function which occurred in the result of above.

Would using python be ok for you at this point ((compatible, no zsh etc) shells are always lacking the datastructures needed for this task)? We could make a task which automatically runs the script when pushing a change to `luapi_application.h` (I only have experience with github actions though and xournalpp uses azure runners).


---

Note: I'm really not good at writing parsers, so no hard feelings if you decide to do it differently / on your own ^^

**Comment by rolandlo** [comment]
> Would using python be ok for you at this point

Sure. We have some python-scripts in the `scripts` folder of the repository already.

**Comment by atticus-sullivan** [comment]
Since writing a script to generate the declaration/definition file is different than just kinda hardcoding it, I'm opening another PR #5572 for this. The PR is still a draft, since there are a few things (mainly organizational stuff) to talk about before merging, but from the coding part it should be already complete.

**Pull request closed without merging**
