### PR TITLE
Fixed several bugs in Layout::layoutPages(),

### PR DESCRIPTION
**Pull request by Febbe**
Replaced the NULL makro with nullptr,
replaced some auto deducible types with auto,
corrected a spelling mistake

Signed-off-by: Fabian Keßler <fabian_kessler@gmx.de>

### CODE REVIEW

**Comment by andreasb242** [comment]
Hi @Febbe 

I like contribution, but please don't do that big refactoring in one Pull Request, it's really hard to review them. And there were already much smaller changes, which break some stuff, which was hardly to see.

I see you have fixed e.g. the formatting of "Control::clipboardPasteTex", which was not like the coding convention said. But you have also broken it, e.g. "MetadataManager::storeMetadata", Line 276 or "Layout::layoutPages" Line 226. or Line 244.

But there are also things which I really don't understand what you are doing, e.g.
Control::loadMetadata, Line 2223

data->md = std::move(md); 

md is a Pointer! So why are you doing this?


And you didn't describe the bugs you fixed, even if you are right, I cannot check it. Therefore I don't merge this now.
Additional I'll write you a mail.

**Comment by andreasb242** [comment]
@Febbe do you may have time to create a pull with the layout fixes?

**Comment by andreasb242** [comment]
Oh nice!

Thank you for the info and have fun!
(and may do some advertising for Xournal++ :-))

**Comment by Rmano** [comment]
Also --- at least on Linux with Firefox, if you copy your image in the clipboard, and paste into this box, all is automatic --- the image is uploaded and the correct link is inserted. You can check it in the "preview" tab.

**Comment by andreasb242** [comment]
I'll close this now, but if you have time, create a new pull request. May it's not needed anymore, there was an additional Pull which improves a lot on the layout handling...

**Pull request closed without merging**
