### PR TITLE
Fixed LaTex scaling for long text

### PR DESCRIPTION
**Pull request by luco5826**
Hi!
I managed to downscale the LaTex preview when long strings are inserted.
I still need to change the Dialog entry from a simple one-line entry to a small TextView (is this the right way?), but for now let me know if the scaling works a little better!
(I didn't change .po files, I don't know why they're different)

### CODE REVIEW

**Comment by andreasb242** [comment]
I think you have to merge against the master, then the diffs of the .po files should be gone.

**Comment by luco5826** [comment]
Hi @andreasb242 sorry but I don't understand what should I do! I pushed my changes as I always do

**Comment by andreasb242** [comment]
I thought you are not up-to-date, but you are.
The changes are OK, I did it today, but I don't understand why they are displayed in your pull...

Ignore them, if something will go wrong, this are only two texts... So not a problem, but I don't think so.
If you have tested the scaling, you can merge it.

**Comment by morrolinux** [comment]
fixes #478

**Pull request merged**
