### PR TITLE
update toolbar.ini header

### PR DESCRIPTION
**Pull request by forgottosave**
## What happened?
As discussed in #4413 the `toolbar.ini` and the `TOOLBAR_INI_HEADER` in `ToolbarModel.cpp` were not up to date anymore and needed some catch-up work, which I did in this PR.

## Missing items in the toolbar.ini
- File:
`SAVEPDF,PRINT`
- Edit:
`DELETE_CURRENT_PAGE`
- Zoom:
`PRESENTATION_MODE`
- Tools:
`DRAW,MATH_TEX,COMPASS,SELECT_OBJECT,PLAY_OBJECT,DRAW_ELLIPSE,DRAW_RECTANGLE,DRAW_ARROW,DRAW_COORDINATE_SYSTEM,DRAW_SPLINE,AUDIO_RECORDING,AUDIO_SEEK_BACKWARDS,AUDIO_PAUSE_PLAYBACK,AUDIO_STOP_PLAYBACK,AUDIO_SEEK_FORWARDS`
- Tool settings:
`TOOL_FILL,ROTATION_SNAPPING,GRID_SNAPPING,SETSQUARE`

### CODE REVIEW

**Review by rolandlo — CHANGES_REQUESTED** [review]
There is https://github.com/xournalpp/xournalpp/blob/517ce512a709d2951e84d7427a7d5399959270f2/src/core/gui/toolbarMenubar/ToolMenuHandler.cpp#L377-L578 as source of truth (as a basis). In `ToolbarModel.cpp` and `toolbar.ini` there are some inconsistencies. For example menu `Journal` is not listed and `INSERT_NEW_PAGE` is under (menu) `Edit` and `RULER` is under `Tool settings` instead of `Tools`. 

Would you mind rewriting both `ToolbarModel.cpp` and `toolbar.ini`  such that they conform to `ToolMenuHandler.cpp` (same menus, same order etc.) So it would start with `File: NEW, OPEN, SAVE, SAVEPDF, PRINT` and then `Edit: UNDO, REDO, CUT, COPY, PASTE, SEARCH, DELETE, ROTATION_SNAPPING, GRID_SNAPPING` 
Here I see that `SETSQUARE`, `COMPASS` are misplaced. They should be under menu `Tools` in all 3 files. So if you see any items that are not under the right menu (compared with the menus you see when opening Xournal++) please correct them.

Also `SPACER` and `SEPARATOR` should be mentioned.
The comment `NB: QUESTO FILE SI TROVA IN /home/morro/xournalpp/ui/toolbar.ini` should be removed.

By the way, if you haven't noticed, you can generate the section in `toolbar.ini` from the section in `ToolbarModel.cpp` by deleting/renaming the file `~/.config/xournalpp/toolbar.ini` and customizing a toolbar that gets saved into a new copy of `toolbar.ini`)

**Comment by forgottosave** [comment]
Sure, I can do that :)

**Review by rolandlo — CHANGES_REQUESTED** [review]
Looks mostly good to me. But still some changes as highlighted in the individual files are required.

**Review by rolandlo — APPROVED** [review]
LGTM, thanks! Please squash into one commit and rebase on current master.

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised.

**Comment by rolandlo** [comment]
Thanks for the contribution @forgottosave ! I just merged it. Always welcome!

**Pull request merged**
