### PR TITLE
Fix border artefacts when writing close to the edge of a Graph background

### PR DESCRIPTION
**Pull request by bhennion**
Fixes this:

https://user-images.githubusercontent.com/17818041/209571911-38219acd-8f84-4a77-9548-67cb8445d401.mp4

Merging in 24 hours unless an objection is raised.

### CODE REVIEW

**Comment by Technius** [comment]
Does this fix #4490?

**Comment by bhennion** [comment]
I don't think so: I don't see any reason why this could fix something like #4490 (but I can't know for sure, I failed to reproduce #4490).

**Comment by tattsan** [comment]
#4490  appears even after applying this PR.  It doesn't appear very often, so I can't do bisection.

**Review by Technius — APPROVED** [review]
Code LGTM, didn't try it though.

**Pull request merged**
