### PR TITLE
Fix null pointer dereference when no page spinner is used

### LINKED ISSUE #3114: Xournal++ crash
**Affects versions :**
 - OS: Linux Mint 20.1
 - (Linux only) Desktop environment: X11
 - libgtk  3.24.20

 - Version of Xournal++: xournalpp - 1.1.0+dev~202105130555~ubuntu20.04.1
   
 - Installation method:  PPA

Xournal++ crashes on start since version 20210507.....

**To Reproduce**
1. Launch Xournal++

**Expected behavior**
Software opens a window
[errorlog.20210513-160741.log](https://github.com/xournalpp/xournalpp/files/6474167/errorlog.20210513-160741.log)

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Terminal output:

[term_output.txt](https://github.com/xournalpp/xournalpp/files/6474190/term_output.txt)

### PR DESCRIPTION
**Pull request by Technius**
Fixes #3114. I've only tested this on Linux but I believe it should also work for Windows.

### CODE REVIEW

**Review by rolandlo — APPROVED** [review]
The fix works, I don't get a segfault on MS Windows any more. I customized the toolbar and moved the page spinner around. No crash and everything seems to work. Some warnings appeared though:

When the page spinner is used on the floating toolbox:
```` 
(xournalpp.exe:13344): Gtk-WARNING **: 20:06:06.740: Allocating size to floatingToolbox 000001a3eaa74a60 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```` 
And earlier when moving the page spinner around (I think):

```` 
(xournalpp.exe:13344): Gtk-WARNING **: 20:00:49.924: GtkToggleButton 000001a3eaeebeb0 is drawn without a current allocation. This should not happen.

(xournalpp.exe:13344): Gtk-WARNING **: 20:00:49.944: GtkToggleButton 000001a3eaeebeb0 is drawn without a current allocation. This should not happen.

(xournalpp.exe:13344): Gtk-WARNING **: 20:00:51.771: GtkToggleButton 000001a3eaeebeb0 is drawn without a current allocation. This should not happen.

(xournalpp.exe:13344): Gtk-WARNING **: 20:00:51.792: GtkToggleButton 000001a3eaeebeb0 is drawn without a current allocation. This should not happen.

(xournalpp.exe:13344): Gtk-WARNING **: 20:01:03.263: (../gtk3/gtk/gtkcssgadget.c:689):gtk_css_gadget_get_preferred_size: runtime check failed: (*minimum <= *natural)

(xournalpp.exe:13344): Gtk-WARNING **: 20:01:03.263: GtkToolbar 000001a3eaff06d0 reported min size 51 and natural size 15 in get_preferred_width(); natural size must be >= min size
```` 
Do we need to take actions on those warnings or is that fine?

**Comment by Technius** [comment]
I think it's fine for now as long as it doesn't cause a crash or impair usability. The floating toolbox is still experimental and definitely needs some polishing.

**Comment by rolandlo** [comment]
Ok, let's merge it then.

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised.

**Pull request merged**
