### PR TITLE
Make use of clang-format #1250

### PR DESCRIPTION
**Pull request by Febbe**
Added clang-format configuration file

### CODE REVIEW

**Comment by LittleHuba** [comment]
Please change `MaxEmptyLinesToKeep: 1` to `MaxEmptyLinesToKeep: 2` for better formating of code sections. Except that small issue everything else looks good to me.
Please also update the Coding conventions in the wiki, so we do not have two different versions running around. You should also point out that people should run their changes once through clang-format before providing a PR.

**Comment by Febbe** [comment]
Ok, I updated the coding conventions already. Shall I delete the old Coding Style instructions completely?

**Comment by LittleHuba** [comment]
We should also schedule a PR freeze sometime in the future to run `clang-format` once on all the sources. But that has to wait until we have all the big PRs merged in.

There are a lot of conventions that are not handled by clang-format. You'll have to be careful what to remove and what to keep.

**Comment by LittleHuba** [comment]
While I'm thinking about it I'll add a small automated check that makes sure people have formated their PRs before submitting them.

**Comment by Febbe** [comment]
> We should also schedule a PR freeze sometime in the future to run clang-format once on all the sources. But that has to wait until we have all the big PRs merged in.

Definitely i had that problem before, resulting in a big chaos.  

> There are a lot of conventions that are not handled by clang-format. You'll have to be careful what to remove and what to keep. 

Ok, then I'll remove everything which is handled by ClangFormat.

> While I'm thinking about it I'll add a small automated check that makes sure people have formated their PRs before submitting them.

Great :)

**Pull request merged**
