### PR TITLE
Fix possible bug in edge pan timer destruction

### LINKED ISSUE #3618: Frequent crash at saving xopp file
Hi. I'm encountering random and frequent crashes (shut down) when I save the xopp file by pressing ctrl+s.
I use large paper format as width 60, height 60 with a lot of attached screenshot images on those large papers.
Can this large paper with a lot of attached images cause the crash?

I'm using 1.1.0+dev, built on Nov 23 2021 on Ubuntu 20.04.3 LTS

Error log is as following

```
Date: Thu Nov 25 08:42:05 2021
Error: signal 11
[bt]: (0) xournalpp(+0xbb300) [0x5644b18b4300]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1a9c3d2210]
[bt]: (2) xournalpp(_ZN11XojPageView10getXournalEv+0x4) [0x5644b1977274]
[bt]: (3) xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x37) [0x5644b195fb47]
[bt]: (4) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7f1a9ca98be8]
[bt]: (5) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f1a9ca9804e]
[bt]: (6) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7f1a9ca98400]
[bt]: (7) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f1a9ca984a3]
[bt]: (8) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f1a9ccdbfe5]
[bt]: (9) xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x5644b18b5261]
[bt]: (10) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1a9c3b30b3]
[bt]: (11) xournalpp(_start+0x2e) [0x5644b18b3bee]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0xbb79c) [0x5644b18b479c]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1a9c3d2210]
??:0
[bt] #3 xournalpp(_ZN11XojPageView10getXournalEv+0x4) [0x5644b1977274]
??:0
[bt] #4 xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x37) [0x5644b195fb47]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52be8) [0x7f1a9ca98be8]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14e) [0x7f1a9ca9804e]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7f1a9ca98400]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f1a9ca984a3]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f1a9ccdbfe5]
??:0
[bt] #10 xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x5644b18b5261]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1a9c3b30b3]
??:0
[bt] #12 xournalpp(_start+0x2e) [0x5644b18b3bee]
??:0
```

### PR DESCRIPTION
**Pull request by Technius**
An attempt to fix #3618.

### CODE REVIEW

**Comment by Technius** [comment]
@youngminpark2559 could you test if this PR fixes your issue? I'm unable to reproduce the bug, but I suspect the fix here addresses the true cause of the issue.

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc4NDUvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc4NDUvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc4NDUvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 18.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc4NDUvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0xOC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMTc4NDUvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by youngminpark2559** [comment]
@Technius Sure, I'll test and report

**Comment by Technius** [comment]
Since this patch fixes an actual problem in the code, I'll assume it fixes the crashing issue. Merging in 24 hours unless there are objections.

**Comment by youngminpark2559** [comment]
@Technius Yes, the crash error haven't occurred yet. Since I also didn't know what action exactly made the crash, I have been observing if the crash comes, but no crash yet. Thanks for resolving the error.

**Pull request merged**
