### PR TITLE
Configurable alternative foreground colors for dark backgrounds

### PR DESCRIPTION
**Pull request by robinp7720**
This adds configurable alternative foreground colors to "pagetemplates.ini" to all views which are used if the background is darker then middle gray. #2055 did this for the graph view, however it also stopped configurable foreground colors from working specifically on that view. 

Template options `af1` and `af2` are used as alternative dark colors respectively instead of `f1` and `f2` with dark background colors.

### CODE REVIEW

**Review by LittleHuba — APPROVED** [review]
Nice solution with the alternativeColor Wrapper. LGTM!

**Comment by rolandlo** [comment]
Can you rebase your PR on the current master and solve the merge conflicts? Then I can take one more look at it and merge it, if there is nothing to complain about.

**Comment by robinp7720** [comment]
Since I deleted the original fork where I had the changes, and github doesn't recognize the branch when I push it to a new repo with the same name, I'll have to create a new pull request. Is that ok?

**Comment by rolandlo** [comment]
That's OK for me. Once you have created the new PR you can close this one.

**Comment by robinp7720** [comment]
Closed in favor of #2352

**Pull request closed without merging**
