### PR TITLE
Enabled newlines in Latex

### PR DESCRIPTION
**Pull request by nicolae-stroncea**
User can now use \newline,\\\,  etc, to write on a new line in Latex Mode. Previously, all text would go in 1 single line and fill the entire width, so user would have to start a new TexMode if equation was getting too long

### CODE REVIEW

**Comment by Technius** [comment]
Thanks for the PR, but we're currently working on getting 1.0.14 released so we can't merge this PR until afterwards.

**Comment by nicolae-stroncea** [comment]
Do you have a timeline in mind for this? I was looking into other minor bug fixes/ or adding other features. Is it better to wait for 1.0.14 to be released before I proceed with this?

**Comment by LittleHuba** [comment]
The problem is that part of 1.0.14 is applying clang-format and some other changes to the code which apply to high percentages of the files. To preserve our git history and be able to check where a bug originated we want to do this in one go and not spread it.
So you should definitely wait since most likely your PRs you do now will not be mergable after these changes without a lot of manual modifications.

We hope to be finished with all this work within the week, but we have to make sure that a few changes don't mess up the systems of users. Especially one change in this release has the potential to break a lot of desktop environments so we might need some more time.

**Comment by LittleHuba** [comment]
@nicolae-stroncea we will lift the PR-freeze shortly but we are not quite done yet. Please check out the main github page, in a week or so. We will remove the message about the PR-freeze as soon as we are done. Thanks in advance for all the work!

**Pull request merged**
