### PR TITLE
Removed the "DeleteRect" if the hand tool is selected

### PR DESCRIPTION
**Pull request by Jared234**
This is an attempt to fix the bug mentioned in #4367.
The user who created this issue wanted to be able to use the hand tool to delete a selected item by clicking on the delete rectangle next to it. However, the hand tool should not be able to do this in the first place.
Still, I feel that the delete rectangle right next to the element can be a bit misleading. So I decided (as discussed in #4367) to simply not draw the "DeleteRect" when the hand tool is selected.

### CODE REVIEW

**Review by rolandlo — CHANGES_REQUESTED** [review]
Thank you for your contribution. 
I think the anchors (for resizing and rotation) should also not be drawn when the hand tool is used, since they also can't be used with that tool.

**Comment by Jared234** [comment]
Thanks for the review. I agree. 👍

**Review by rolandlo — APPROVED** [review]
LGTM, thanks!

Merging in 24 hours if no objections are raised.

**Comment by bhennion** [comment]
Let's maybe wait until #4455 is merged before merging this.

**Pull request merged**
