### PR TITLE
circular array based audio queue

### PR DESCRIPTION
**Pull request by morrolinux**
It basically worked on the first attempt, so I wasn't really spurred to do better anything in particular.
Please feel free to point out if you find anything stupid ;-)

### CODE REVIEW

**Comment by Technius** [comment]
For future reference, this appears to be a fix for #1458.

**Comment by LittleHuba** [comment]
@morrolinux is this included in #1520?

**Comment by Febbe** [comment]
There are several things I don't like. 
I would rather use a std::array instead of a plain old c-array.
The objects in the queue aren't destructed, only overridden.
You don't use rangebased for loops.
You use some sort of pointer arithmetic.
The ringbuffer is still not accessed in a thread safe way. The bug could still happen, just not as often than before.

I would rather use the version from before with an write/shared read mutex and/or boost circular buffer.

**Comment by morrolinux** [comment]
> @morrolinux is this included in #1520?

I must have branched out #1520 from this so that's not really intentional.. I'm gonna remove it from #1520 now.

> I would rather use the version from before with an write/shared read mutex and maybe with boost circular buffer.

Yeah sure no problem. As I said, I just needed something working ASAP since I'm very busy with classes right now. You can implement it your way, I like it more as well, no offence is taken :)

**Comment by morrolinux** [comment]
> The ringbuffer is still not accessed in a thread safe way. The bug could still happen, just not as often than before.

I'm not sure about that, becuase the reader only reads and the writer advance the pointer once the write has finished, and no resources are accessed for write by two different threads. Or am I missing something?

**Comment by LittleHuba** [comment]
Ringbuffers in itself are not necessarily thread-safe, but this specific implementation in this usecase should be thread-safe. The important part is that we only have one writer and one reader, and size is incremented after the buffer is written.

So in essence this is a valid solution, but all other problems mentioned by @Febbe stand and therefore I would stick to the Deque. Additionally I'm still not sure if a fixed buffer size is a good thing for all hardwares. I had some problems when I wrote this up since my desktop PC was way faster than my laptop.

Still thanks for the PR @morrolinux

**Pull request closed without merging**
