### PR TITLE
Add more toolbar icons needed for dark themes.

### PR DESCRIPTION
**Pull request by badshah400**
Add icons which were missing from the iconsDark ensemble:
* presentation-mode
* tool_math_tex.
These icons are generated from the default icons for the same buttons
by changing the stroke colour to white instead of black to make them
more clearly visible when xournalpp is launched in a DE using a dark
theme (e.g. Adwaita:dark).

### CODE REVIEW

**Comment by badshah400** [comment]
Sorry, this is still WIP. I am updating the dark theme icons as and when I find them missing.

**Comment by badshah400** [comment]
This should be all. Sorry for the multiple commits, should have done them in one go. Feel free to squash them during merge if you accept this PR.

**Comment by Technius** [comment]
I'll review this after I get the mac builds fixed.

**Comment by Technius** [comment]
Fixing the mac builds doesn't matter for this change (it doesn't touch code). Everything LGTM. Is there anything else you want to add before I merge this?

**Comment by badshah400** [comment]
No, I don't have anything more I find necessary to add. Thank you.

**Comment by Technius** [comment]
Cool, thanks for the PR!

**Pull request merged**
