### PR TITLE
Update to version 1.0.19

### PR DESCRIPTION
**Pull request by Technius**
Backport recent bugfixes, CI configuration, and readme updates to our stable `1.0.x` branch in preparation for a `1.0.19` release.

The release will be made by the end of this weekend, unless there are objections.

### CODE REVIEW

**Comment by Technius** [comment]
Looking to merge this within the next two weeks. The remaining work is:
* [ ] Cherry pick a few more bugfixes
* [ ] Update changelog again
* [ ] Investigate AppImage issues (#1978, #2200 #2096)

**Comment by rolandlo** [comment]
Maybe PR #2182 about text dpi sacling (and search mark) without the line spacing fix (which is not working properly yet due to a pango bug, it seems) should also be merged? This is a pretty fundamental bug. All font sizes are wrong unless the selected dpi calibration is 72. For instance on my convertible correct dpi callibration is 210 and all font sizes are off by a factor of 2.9. I could make it ready.

**Comment by Technius** [comment]
I can't figure out the AppImage issues, so I'm just going to merge and push out the release within the next few days.

AppImage will be "demoted" to experimental status.

**Comment by Technius** [comment]
Release is slated for Oct 13 unless there are any objections.

**Comment by rolandlo** [comment]
I think the list of authors should be updated. It's 2020 now.

**Comment by rolandlo** [comment]
I would recommend to make the new input system enabled by default. It seems way less buggy than the old input system.
	`this->experimentalInputSystemEnabled = true;`

**Comment by rolandlo** [comment]
Sorry for the late question, but shouldn't  #1819, #2106, #2131, #2135, #2136 and  #2269 get backported as well?

**Comment by Technius** [comment]
Whoops, I accidentally force pushed that last author list update with the wrong set of commits!

All of the backports that I did previously should be fixed now. I don't want to include any more last minute changes in case I make another mistake...

I've been very busy this week, so I need to delay the release to this weekend.

**Comment by Technius** [comment]
Better late than never.

**Pull request merged**
