### PR TITLE
fix selection cursor update for vertical scaling

### LINKED ISSUE #2458: Problem resizing a selection if I use the handle at the bottom of the selection
Xournal ++ version : xournalpp-1.1.0.dev-nightly.20201124-windows

I create a rectangle and then I select it.
I click on the right sizing handle of the selection. So I can stretch the rectangle without any problem.
I click on the resize handle at the bottom of the selection. So the resizing is done but taking a lot of time.

Note: This problem does not appear in Xournalpp 1.0.19

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #2458

### CODE REVIEW

**Comment by MichelReims** [comment]
Thank you

**Comment by MichelReims** [comment]
There is no problem with the top handle ?

**Comment by rolandlo** [comment]
There was, but not after this PR.

**Comment by MichelReims** [comment]
I have compiled your PR on windows 10. It works. Thanks

**Pull request merged**
