### PR TITLE
Merge release 1.1

### PR DESCRIPTION
**Pull request by Febbe**

### CODE REVIEW

**Comment by Febbe** [comment]
@LittleHuba @rolandlo @bhennion can you check your changes pls.

**Comment by LittleHuba** [comment]
cbc29af9e8a9a38614f08438405dc3a61e653887 should be dropped

**Comment by rolandlo** [comment]
> @LittleHuba @rolandlo @bhennion can you check your changes pls.

Commit https://github.com/xournalpp/xournalpp/pull/3599/commits/412fc8e188a3f49a182feb472527278ad260cc7c is fine. There are no more changes from my side.

**Comment by LittleHuba** [comment]
All my other changes seem to be okay.

**Comment by bhennion** [comment]
LGTM!

**Comment by Febbe** [comment]
> cbc29af should be dropped
So don't even bump to 1.1.1+dev ? (changed the ~ to +)

**Comment by Febbe** [comment]
Will merge this after pipeline succeds.

**Comment by LittleHuba** [comment]
> > cbc29af should be dropped
> 
> So don't even bump to 1.1.1+dev ? (changed the ~ to +)

No, as we have not yet released 1.1.1 the current nightly can not be based on this release.

**Comment by LittleHuba** [comment]
> > > cbc29af should be dropped
> > 
> > So don't even bump to 1.1.1+dev ? (changed the ~ to +)
> 
> No, as we have not yet released 1.1.1 the current nightly can not be based on this release.

@Febbe ?!

**Comment by Febbe** [comment]
@LittleHuba, I removed it.

**Pull request merged**
