### PR TITLE
Disable pen cursor

### PR DESCRIPTION
**Pull request by chentangchu**
Pen cursor in a tablet might not be necessary, so disable it if blankPenCursor is set true in the setting xml file.

### CODE REVIEW

**Comment by Technius** [comment]
Thanks for the PR! You have a merge conflict in `src/gui/Cursor.cpp`, so you'll need to fix that before we can start reviewing.

**Comment by LittleHuba** [comment]
Before merging this I'd like to add a better representation in the settings. Drop-down menu and everything.

**Comment by JJones780** [comment]
The highlight option should still produce an effect (in this case, leaving just the highlight).

For the big pen/none maybe switching to a  drop down box to select from competing pointer images.
We could add in some other options here too - crosshairs, system pointer, lefthanded arrow, etc.

**Comment by LittleHuba** [comment]
@Technius will you implement the changes I mentioned or should somebody else take over the PR?

**Comment by Technius** [comment]
@chentangchu Are you still willing to make a dropdown menu, like @LittleHuba requested? If not, we can let someone else handle it.

**Comment by JJones780** [comment]
I'll look into incorporating this.

**Comment by JJones780** [comment]
Sorry... haven't had time for Xournal++ lately... still planning to get to this... soon.

**Comment by JJones780** [comment]
Upon further reflection , I believe this feature should be part of a larger feature which would allow the user to define a customized cursor (including a blank one ).  The single dot cursor ( which changes to a normal cursor when the mouse is moved ) should suffice for the time being.

**Pull request closed without merging**
