### PR TITLE
 Fix some blank messageboxes that shows no context except the 'OK' button

### PR DESCRIPTION
**Pull request by VivekThazhathattil**
This is a solution to one of the issues mentioned in #3104. The reason why the message box was empty was because `g_markup_escape_text()` wasn't called on the message strings before passing it to `gtk_message_dialog_set_markup()`.
Before:
image
After:
image

### CODE REVIEW

**Review by Technius — COMMENTED** [review]
Thanks for the PR! Just one problem: `g_markup_escape_text` will allocate new strings, so they need to be freed with `g_object_unref`.

**Comment by VivekThazhathattil** [comment]
@Technius Should I use `g_free` or `g_object_unref`?

**Comment by Technius** [comment]
Either one works, but `g_object_unref` is less error prone since it only decreases the ref count (which will trigger a free anyway if the new ref count is 0).

**Comment by VivekThazhathattil** [comment]
using `g_object_unref(formattedMsg)` crashes xournalpp for some reason :(

**Review by Technius — APPROVED** [review]
Ah, I was mistaken; glib strings are not reference counted. So `g_free` should be used in this context (and `g_object_ref`/`unref` should _not_ be used).

I have tested the PR and the fix appears to work correctly.

Merging in 24 hours if there are no objections.

**Comment by VivekThazhathattil** [comment]
Hi @Technius, will this PR be merged soon?

**Comment by Technius** [comment]
Yes, thanks for the reminder.

**Pull request merged**
