### PR TITLE
Performance gdkeventguard

### PR DESCRIPTION
**Pull request by Febbe**
The previous PR'S are still in this PR, so I had better profiling information.

### CODE REVIEW

**Comment by Febbe** [comment]
@rolandlo you may want to test the performance now on macOs

**Comment by Technius** [comment]
The next release is very close, so let's delay the merge of such nontrivial refactoring to after the release.

**Comment by rolandlo** [comment]
I have let build this PR on Azure Pipelines and compared it to the latest nightly release. On my MacBook there is still significant lag in both builds when using a toolbar (I used the portrait toolbar). Using my Wacom Intuos Pro M tablet I can't write normally and big circles I draw (with normal speed) become very edgy (maybe 8-10 edges for one circle). Without toolbar handwriting looks acceptable on both versions and circles I draw look more like circles (around 20-24 edges).
I don't observe a performance gain from this PR on my MacBook. Comparing results it looks more like the opposite, although the decisive factor is having the toolbar displayed or not. There may be Mac users that will report otherwise (for one user with an M1 chip the toolbar didn't make a difference), but at least this PR doesn't solve the lag issue for all Mac users.

I agree with @Technius that we should delay the merge of this PR.

**Comment by Febbe** [comment]
Damn, than I need you to profile x++ on macOs. 
On X11 I have a large performance gain :)

**Comment by rolandlo** [comment]
> Damn, than I need you to profile x++ on macOs.
> On X11 I have a large performance gain :)

Yes, there is seems to be no way around profiling Xournal++ on MacOS BigSur. On Linux when I draw big circles, they look completely smooth. No edges visible at all. Looking at the `gunzip`-ed .xopp-file a circle-like shape I drew on Linux consists of about 300 points. On MacOS BigSur it's about 30 points, on MacOS Catalina about 85 points. Since I use different laptops on Linux and MacOS it's not directly comparable, but still gives a hint.

**Comment by suisseWalter** [comment]
it seams like this branch causes some crashes for me. (X11+I3,ubuntu20.04)
one of the errorlogs created is attached bellow. 
the crashes can happen at any point. but I can provoke them by moving the window around in I3 and it most often crashes as soon as the window is next to the left edge of my display. But I was also able to cause the crash by just writing on it. 
I compiled all 4 different commits in this PR. and it's only the last one that causes the problem, so the gtkeventguard stuff. 
(I just compiled the febbe/xournalpp fork, I hope this is correct. but it seams like this is the only difference to master) 
the console output before crashing was the following:
```
xournalpp: /home/username/Documents/sandbox/xournalbug/xournalpp/src/gui/LayoutMapper.cpp:171: std::optional<long unsigned int> LayoutMapper::at(const GridPosition&) const: Assertion `index < rasterToPage.size()' failed.

** (xournalpp:101914): WARNING **: 20:02:10.230: [Crash Handler] Crashed with signal 6

** (xournalpp:101914): WARNING **: 20:02:10.231: [Crash Handler] Wrote crash log to: /home/username/.cache/xournalpp/errorlogs/errorlog.20210720-200210.log

** (xournalpp:101914): WARNING **: 20:02:10.430: Trying to emergency save the current open document…

```

[errorlog.20210720-191819.log](https://github.com/xournalpp/xournalpp/files/6850170/errorlog.20210720-191819.log)

the reason for me compiling this fork was to figure out if it may contain a alternative fix for #3224 (was curious about the X11 callback part), but it does not.

**Comment by Febbe** [comment]
@suisseWalter Thanks for testing, the crash happens, because I assumed, that the structure I refactored is not called with an illegal argument. Just like calling the vectors subscription operator with an out of bounds index.

But, when it does not crash, it also hadn't a performance gain?

**Comment by Febbe** [comment]
> I compiled all 4 different commits in this PR. and it's only the last one that causes the problem, so the gtkeventguard stuff.

It crashes because bac6746 not the gdk_event_guard.

**Comment by Febbe** [comment]
> 
> 
> > I compiled all 4 different commits in this PR. and it's only the last one that causes the problem, so the gtkeventguard stuff.
> 
> It crashes because [bac6746](https://github.com/xournalpp/xournalpp/commit/bac6746ed86f5ff8613bab91af4d7e2cb9121e7e) not the gdk_event_guard.

It crashes here: 
https://github.com/xournalpp/xournalpp/commit/bac6746ed86f5ff8613bab91af4d7e2cb9121e7e#diff-e21b577a460a5ce8a9cab36f500fd33d7c17414dcc50a06d0bbc73c898596405R171

**Comment by suisseWalter** [comment]
> But, when it does not crash, it also hadn't a performance gain?

I'm running on linux, with a rather powerfull laptop. so even if there would be a expected performance increase it probably wouldn't be significant and therefore it wouldn't be noticable. but no, I'm not noticing a performance increase. where should I notice it? as I wasn't testing it in use, for obvious reasons, just switching it between workspaces etc. if you would like to, I could compile it to a appimage and then test it on a old laptop(year2012) and see if I can spot a visible difference. 

> It crashes because bac6746 not the gdk_event_guard.

weird, thought I had compiled with that and it didn't cause the problem. but if you found the problem I was probably wrong.

**Comment by rolandlo** [comment]
@Febbe So what to do about the crash noticed by @suisseWalter ?
The performance issue on MacOS is partly fixed now (in #2729). Even on BigSur drawing is now fluent if using the empty toolbar, or the minimal left toolbar from PR #3267. The problems have to do with bad performance of the Quartz backend used on MacOS. Rendering Cairo surfaces is expensive on MacOS, and the cost depends pretty much on the size of  the rectangles that are renderd. It will apparently improve considerably with Gtk 4, but for now we can't expect the same performance on MacOS like on Linux with respect to the rendering.

Your changes make sense to me. If you can avoid the crash and rebase on current master, I can test once more on MacOS, Windows and Linux. I'm not sure how to measure the performance exactly though. How did you measure the performance gain mentioned in https://github.com/xournalpp/xournalpp/pull/3221#issuecomment-881739943?

**Comment by Febbe** [comment]
I am on vacation in Sweden, since we are here with a Camper, I don't have much power for my laptop and only mobile internet.

**Comment by Febbe** [comment]
@rolandlo, I would change the assert to an regular if

**Comment by Febbe** [comment]
Done. I would merge this into the new release branch

**Comment by LittleHuba** [comment]
> Done. I would merge this into the new release branch

Please merge it into a feature-branch, so we can take another look into that crash noticed by @suisseWalter

**Comment by Febbe** [comment]
The crash is fixed already

**Comment by LittleHuba** [comment]
Then we can merge this directly with `master`.

**Comment by Febbe** [comment]
This is rather a bugfix, than a refactoring

**Comment by LittleHuba** [comment]
But is it a bugfix that requires the release of a hotfix?

**Comment by Febbe** [comment]
Here is the question how fine-grained our release cycles should be. I would release it with 1.1.x and not 1.2.x a hot fix is something like 1.1.1.x (for me) since it "fixes" a critical in a release

**Comment by LittleHuba** [comment]
Let's move this discussion to Gitter.

**Comment by rolandlo** [comment]
I have trouble checking this PR out. When I do
```
 git fetch upstream pull/3236/head:febbe
git checkout febbe
git log
```
I don't see the 4 commits introduced in this PR, but only
```
8430f45516181f1fdbb106be0972c1ee1291ee54 (grafted, HEAD -> febbe, Febbe/performance_gdkeventguard) Optimize GdkEventGuard
```
Why does that happen? Is that because @Febbe's [master branch](https://github.com/Febbe/xournalpp) already contains changes that are not in the main repo master?

**Comment by Febbe** [comment]
have you tried `gitk --all`?

**Comment by rolandlo** [comment]
> have you tried `gitk --all`?

I didn't know about that tool. That's how the graph looks like:
grafik

**Comment by Febbe** [comment]
Ah, you checked out my commit, without feching the history. So the commit is "unrelated". But it contains all previous commits.

**Pull request merged**
