### PR TITLE
Preparation for 1.1.1 release

### PR DESCRIPTION
**Pull request by Technius**
@xournalpp/core Please check if there is anything missing in the changelog.

* [x] Cherry pick #3747
* [x] Update changelog with latest changes (no more changes will make it in, except for #3776)
* [x] Merge #3776
* [x] Changelog summarized for `debian/changelog`
* [x] Merge this PR
* [ ] Run release scripts, push to GitHub.
* [ ] Monitor CI, and approve upload of draft release to GitHub.
* [ ] Release notes written and release published.

### CODE REVIEW

**Comment by LittleHuba** [comment]
You'll have to post the same changelog in `debian/changelog`

**Comment by Technius** [comment]
This needs to be updated with the latest merged changes.

**Comment by LittleHuba** [comment]
I removed all the merging tasks, as part of the normal release cycle is to merge the release back into `master`. #3428 is now merged directly into the release so there should be no requirement to cherrypick anything from `master`. Though 5eb00d71165fd4290a81fe564f31011984512835 still stands for discussion. While it is an improvement for some people, it does not really fix the bug itself. It is more a really crude way of patching it. I'd be happier if we actually got a real fix released.

**Comment by Technius** [comment]
I forgot to merge #3747 into 1.1.x so we'll have to cherry-pick it into 1.1.x.

**Comment by Technius** [comment]
Updated changelog as far as [`9f66a83`](https://github.com/xournalpp/xournalpp/commit/9f66a83e0063f3ffd5ba89d8eee7e862de4fbb3c). I also added #3761 preemptively since it should be merged soon.

**Comment by Technius** [comment]
@xournalpp/core Please check the changelog one last time. I will be making the release after I merge #3776.

**Comment by Technius** [comment]
Thanks for the proofreading. I merged #3776, rebased, and amended the changelog with your suggestions. I'll run the release scripts & finish the release cycle tomorrow morning.

**Pull request closed without merging**
