### PR TITLE
Fixup ffa681e8ad17ef242c427c0b1f48a18d602ac5bd

### LINKED ISSUE #3795: Textmarker with fill has a cutout at starting point
**Affects versions :**
 - OS: Linux, Ubuntu 20.04 LTS
 - (Linux only) Desktop environment: Gnome
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
When using Textmarker with options fill and rectangle or ellipse the starting points have a cutout. 

**To Reproduce**
1. Choose Textmarker 
2. Choose Draw Rectangle or ellipse
3. Choose Fill
4. Draw

**Expected behavior**
A rectangle with rounded corner or an ellipse fully filled

**Screenshots of Problem**
grafik

### PR DESCRIPTION
**Pull request by danemtsov**
Fixes #3795.

See https://github.com/xournalpp/xournalpp/issues/3795#issuecomment-1034554545

### CODE REVIEW

**Comment by bhennion** [comment]
LGTM. Will merge in 12 hours if noone has done so by then.

**Comment by Technius** [comment]
Is this also a problem in 1.1.0? If not, this is a regression caused by #3326.

**Comment by danemtsov** [comment]
Yes, it's a regression from #3326

**Comment by Technius** [comment]
Thanks for identifying the issue and providing a fix. I see no reason to delay the merge.

**Pull request merged**
