### PR TITLE
Update desktop files

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by rolandlo** [comment]
Thanks @ovari for this update. The changes look fine. One point to consider though:The package description was unified in 
- `README.md`, 
- `package_description`, 
- `debian/control` and 
- `desktop/com.github.xournalpp.xournalpp.appdata.xml`. 

You only modify the last one of these files. They got out of sync recently with #3670. Could you unify the package descriptions in the four files again while merging the changes from #3670 with your changes?

**Comment by ovari** [comment]
@rolandlo can you please merge this before it gets out of sync? Thank you

**Comment by rolandlo** [comment]
> @rolandlo can you please merge this before it gets out of sync? Thank you

Sure. But please first 
- remove the line break at the very end of `package_description`. This file is included via `CmakeLists.txt` and the line break makes the `.deb` package building fail, as I remember.
- rebase on `upstream/master` and solve the merge conflict.
- squash your commits into one

**Comment by ovari** [comment]
> * remove the line break at the very end of package_description. This file is included via CmakeLists.txt and the line break makes the .deb package building fail, as I remember.

Done

> * rebase on upstream/master and solve the merge conflict.

Sorry, don't know how to do

> * squash your commits into one

Sorry, don't know how to do

**Comment by ovari** [comment]
FYI, this is all done in the Firefox web browser.

**Comment by rolandlo** [comment]
I will see if I can do it for you (as long as I can force-push to this branch, it is no problem). Otherwise I will instruct you how to do it.

**Comment by ovari** [comment]
Hope it won't take too long as it's bedtime

**Comment by rolandlo** [comment]
Sorry, I cannot force push on the branch. I could open a new PR and make you a coauthor. Otherwise it's getting a bit complicated. Would that be fine for you?

**Comment by ovari** [comment]
> Sorry, I cannot force push on the branch. I could open a new PR and make you a coauthor. Otherwise it's getting a bit complicated. Would that be fine for you?

Yes, do whatever needs to be done. Thank you

**Comment by rolandlo** [comment]
Ok, see PR #3803.

**Comment by rolandlo** [comment]
Closing this PR in favor of #3803

**Comment by ovari** [comment]
Should a `Translations` section be added to the README?

So translators know to update the following:
* README.md,
* package_description,
* debian/control and
* desktop/com.github.xournalpp.xournalpp.appdata.xml.

Thank you

**Pull request closed without merging**
