### PR TITLE
Merge release branch into master

### PR DESCRIPTION
**Pull request by bhennion**

### CODE REVIEW

**Comment by bhennion** [comment]
This PR proposes merging the release branch into to master branch.

I checked the modifications I made in TextEditor.

For what remains: @rolandlo could you confirm that [6f1d90d](https://github.com/xournalpp/xournalpp/pull/4175/commits/6f1d90d9d7f259b7beeead9ed8eb2bf318f741cb) and [f076c16](https://github.com/xournalpp/xournalpp/pull/4175/commits/f076c1676a9ffc17acb93f6e5e7a280b59dadfff) are also needed on the master branch?

**Comment by rolandlo** [comment]
> This PR proposes merging the release branch into to master branch.
> 
> I checked the modifications I made in TextEditor.
> 
> For what remains: @rolandlo could you confirm that [6f1d90d](https://github.com/xournalpp/xournalpp/pull/4175/commits/6f1d90d9d7f259b7beeead9ed8eb2bf318f741cb) and [f076c16](https://github.com/xournalpp/xournalpp/pull/4175/commits/f076c1676a9ffc17acb93f6e5e7a280b59dadfff) are also needed on the master branch?

The first commit was already merged into master in faa0888c482d131171ed72ca98d66037cef71e6a. The second commit was only needed for `release-1.1`.

**Comment by bhennion** [comment]
Oh. I see. So I reverted the changes of @rolandlo's two commits after the merge commit.
Not sure how to keep the git tree as clean as possible.

**Comment by bhennion** [comment]
Alright. I merged this directly in the terminal, to keep the commit tree clean.

**Pull request closed without merging**
