### PR TITLE
Streamline package descriptions and update appdata xml

### PR DESCRIPTION
**Pull request by rolandlo**
We have four variants of a package description in Xournal++
1. the one from the `package_description` file
2. the one in the `README.md`
3. the one in `debian/control`
4. the one in the `com.github.xournalpp.xournalpp.appdata.xml` file (that is used for the `flatpak`). 

I streamlined them and made them all equal up to formatting details. I have also updated the appdata xml-file to some degree.

The appdata xml-file refers to four images, which are already seven years old, i.e. pretty outdated. We should create new images, that show how Xournal++ looks now and what we can do with it now.  Has anybody a nice .xopp-file that could be used to create such an image?

I think we need at least:
- an image for notetaking, maybe with multiple layers
- an image for PDF-annotation
- an image for using LaTeX formulas, maybe something showing off the power we gained with the customizable template, like code-highlighting or drawing with `TikZ` or function graphs via `TikZ/pgfplots`
- maybe something with customizable toolbars or floating toolbox (although that is not new)

Any suggestions?

Three of the 7-year old images that are currently referred to are located on [imgur.com](https://imgur.com/). Is that a good place for these images or should be include the new images in the repository or somewhere else? Note that these images will be shown to tons of Linux users when looking for Xournal++ in the software center or on the flathub website.

### CODE REVIEW

**Comment by rolandlo** [comment]
I have created 3 xopp-files and taken screenshots, that could be uploaded and linked to in the `com.github.xournalpp.xournalpp.appdata.xml`

**For note-taking:**
note-taking

**For pdf annotation:**
pdf_annotation

**For LaTeX and customized preamble:**
LaTeX_with_customized_preamble

Any oppinion @Technius @Febbe @idotobi ?

**Comment by Technius** [comment]
Looks awesome! If you want to show them on Flatpak store or whatever, you can just directly use the link generated by GitHub since GitHub will need to store the images for your comment. We'll need somewhere else to store the xopp files though.

**Comment by rolandlo** [comment]
> Looks awesome! If you want to show them on Flatpak store or whatever, you can just directly use the link generated by GitHub since GitHub will need to store the images for your comment. We'll need somewhere else to store the xopp files though.

Thanks! The pdf background and the LaTeX preamble used will have to be stored along with the xopp-files, I think. These should probably be stored within the repository. I don't see a folder where it belongs, but I could create a new one.

**Comment by Technius** [comment]
I would put the resources in another repository instead (e.g. `xournalpp-examples` or something), unless we're also going to use them for unit tests.

**Comment by rolandlo** [comment]
> I would put the resources in another repository instead (e.g. `xournalpp-examples` or something), unless we're also going to use them for unit tests. Besides that, everything looks good to me.

Done! I have subtracted the resources from this PR and added them to a `xournalpp-examples`repository.

Merging in 24 hours if there are no objections.

**Pull request merged**
