### PR TITLE
GMenu: Use GMenu in some dynamically generated submenus

### PR DESCRIPTION
**Pull request by bhennion**
This is part of #4372 and based on #4441.

This PR refactors the content of the dynamically generated submenus File->Recent Files, View->Toolbar and Plugin so that is uses GMenu and no longer explicitely relies on GtkMenuItem's.

- [x] Merge #4441 and rebase.

### CODE REVIEW

**Comment by rolandlo** [comment]
For some reason (that I don't understand yet) accelerators for plugin callback functions do not work. Those callback functions can only be activated through the menu.

**Comment by bhennion** [comment]
> For some reason (that I don't understand yet) accelerators for plugin callback functions do not work. Those callback functions can only be activated through the menu.

Good catch! I think I know where it comes from.

**Comment by rolandlo** [comment]
Suggested edit:
```diff
diff --git a/src/core/control/Control.cpp b/src/core/control/Control.cpp
index f5b311c72..dc756ca77 100644
--- a/src/core/control/Control.cpp
+++ b/src/core/control/Control.cpp
@@ -163,7 +163,7 @@ Control::Control(GApplication* gtkApp, GladeSearchpath* gladeSearchPath): gtkApp
 
     this->fullscreenHandler = new FullscreenHandler(settings);
 
-    this->pluginController = new PluginController(this);
+    this->pluginController = new PluginController(this, gtkApp);
     this->pluginController->registerToolbar();
 }
 
diff --git a/src/core/plugin/Plugin.cpp b/src/core/plugin/Plugin.cpp
index ec89e9943..79943cb21 100644
--- a/src/core/plugin/Plugin.cpp
+++ b/src/core/plugin/Plugin.cpp
@@ -71,7 +71,7 @@ void Plugin::registerToolbar() {
     inInitUi = false;
 }
 
-size_t Plugin::populateMenuSection(GtkApplicationWindow* win, size_t startId) {
+size_t Plugin::populateMenuSection(GtkApplicationWindow* win, size_t startId, GApplication* gtkApp) {
     if (menuEntries.empty() || !this->enabled) {
         // No entries - nothing to do
         return startId;
@@ -93,6 +93,8 @@ size_t Plugin::populateMenuSection(GtkApplicationWindow* win, size_t startId) {
 
         if (!m.accelerator.empty()) {
             g_menu_item_set_attribute_value(entry.get(), "accel", g_variant_new_string(m.accelerator.c_str()));
+            const char* accels[] = {m.accelerator.c_str()};
+            gtk_application_set_accels_for_action(GTK_APPLICATION(gtkApp), actionName.c_str(), accels);
         }
 
         g_menu_append_item(menuSection.get(), entry.get());
diff --git a/src/core/plugin/Plugin.h b/src/core/plugin/Plugin.h
index 1cca8c157..a21a42095 100644
--- a/src/core/plugin/Plugin.h
+++ b/src/core/plugin/Plugin.h
@@ -78,7 +78,7 @@ public:
      * @param startId next available id
      * @return next available id after this menu is populated
      */
-    size_t populateMenuSection(GtkApplicationWindow* win, size_t startId);
+    size_t populateMenuSection(GtkApplicationWindow* win, size_t startId, GApplication* gtkApp);
 
     /// Get a model for the GMenu section for the plugin
     inline GMenuModel* getMenuSection() const { return G_MENU_MODEL(menuSection.get()); }
diff --git a/src/core/plugin/PluginController.cpp b/src/core/plugin/PluginController.cpp
index f43cc76d0..ed43b8a1e 100644
--- a/src/core/plugin/PluginController.cpp
+++ b/src/core/plugin/PluginController.cpp
@@ -96,7 +96,7 @@ auto emplace_sorted_if_not_exists(std::vector<std::unique_ptr<Plugin>>& plugins,
 #endif
 
 
-PluginController::PluginController(Control* control): control(control) {
+PluginController::PluginController(Control* control, GApplication* gtkApp): control(control), gtkApp(gtkApp) {
 #ifdef ENABLE_PLUGINS
     // Todo(fabian) move those search paths into PathUtils
     auto searchPath = control->getGladeSearchPath()->getFirstSearchPath();
@@ -143,7 +143,9 @@ PluginController::PluginController(Control* control): control(control) {
 
 void PluginController::registerToolbar() {
 #ifdef ENABLE_PLUGINS
-    for (auto&& p: this->plugins) { p->registerToolbar(); }
+    for (auto&& p: this->plugins) {
+        p->registerToolbar();
+    }
 #endif
 }
 
@@ -160,7 +162,7 @@ auto PluginController::createMenuSections(GtkApplicationWindow* win) -> std::vec
     size_t id = 0;
     std::vector<GMenuModel*> sections;
     for (auto&& p: this->plugins) {
-        id = p->populateMenuSection(win, id);
+        id = p->populateMenuSection(win, id, gtkApp);
         auto* section = p->getMenuSection();
         if (section) {
             sections.emplace_back(section);
diff --git a/src/core/plugin/PluginController.h b/src/core/plugin/PluginController.h
index d08896a13..7d2a93581 100644
--- a/src/core/plugin/PluginController.h
+++ b/src/core/plugin/PluginController.h
@@ -24,7 +24,7 @@ class Control;
 
 class PluginController final {
 public:
-    explicit PluginController(Control* control);
+    explicit PluginController(Control* control, GApplication* gtkApp);
 
 public:
     /**
@@ -54,6 +54,11 @@ private:
      */
     Control* control;
 
+    /**
+     * The gtk application used for setting accelerators
+     */
+    GApplication* gtkApp = nullptr;
+
     /**
      * All loaded Plugins, sorted by name and path
      * Todo: replace with boost::flat_map

```

**Comment by bhennion** [comment]
Oh, I didn't see your patch. I pushed a similar fix (except we can get the GtkApplication from the GtkWindow).

**Comment by bhennion** [comment]
I noticed a bug though, when the path of a recently opened file contains special characters (e.g. `'`), the app crashed on startup.

**Comment by bhennion** [comment]
> Oh, I didn't see your patch. I pushed a similar fix (except we can get the GtkApplication from the GtkWindow).

Wait, no. My fix does not work for some reason.

**Comment by bhennion** [comment]
Alright, both issues are fixed now, I think.

**Review by rolandlo — APPROVED** [review]
Looks good to me. I have only one question about when to return `PDF_FILE_TYPE` and one comment about a misplaced comment.
I have also tested it on MacOS. It works fine there as well.

In the commit description "forbiden" should be "forbidden", but I guess you will clean up the commit history anyway.

**Comment by bhennion** [comment]
Thanks for the review @rolandlo!
I implemented the changes you proposed and squashed the commits.

Merging in 48 hours unless an objection is raised.

**Pull request merged**
