### PR TITLE
Fixed Undefined Behaviour in ColorToolItem.cpp:142

### PR DESCRIPTION
**Pull request by Febbe**
Will merge after I found out, if this also happens in the newest release

### CODE REVIEW

**Comment by Febbe** [comment]
Since this is a regression, I will merge it. There are other cases of UB I want to fix directly after this.

**Comment by idotobi** [comment]
Thanks for the fix :pray: 
Could you give me a pointer why this was undefined behaviour? Just so I don't do it again :sweat_smile:

**Comment by Febbe** [comment]
> Thanks for the fix :pray: 
> Could you give me a pointer why this was undefined behaviour? Just so I don't do it again :sweat_smile: 

You returned a string by value, not by const reference. Then, you called cstr on it, without keeping the string value. The cstr ptr was then a dangling pointer.

**Comment by idotobi** [comment]
I see :bulb:  Thanks for explaining.
 I'll check the my `c_str` usage in the upcomming PR. Might very well have used it too liberally elsewhere.

**Comment by Febbe** [comment]
You could also compile xournalpp with `-g -O1 -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefinded`. This will automatically crash the app, when such an error occurs.

**Pull request merged**
