### PR TITLE
Updated spec file

### PR DESCRIPTION
**Pull request by luyatshimbalanga**
Here is the updated spec file. 
Also add ` https://copr.fedorainfracloud.org/webhooks/github/27610/d8866b0a-4783-4d65-a0e4-0d46f0961d12/ ` in the webhook so the build will sync with  the commit. See 
Screenshot from 2022-03-06 11-36-08

### CODE REVIEW

**Comment by Technius** [comment]
Does #3896 fix the gtest issues?

**Comment by luyatshimbalanga** [comment]
> Does #3896 fix the gtest issues?

gtest support is disabled as a workaround. You can turn it on once the codes from #3896 are merged.

**Comment by Technius** [comment]
Merging in 24 hours if there are no objections. (By the way, I merged #3896, so you may want to rerun the build just to check).

TODO:
* [ ] Enable webhook as suggested in the OP

**Comment by luyatshimbalanga** [comment]
The [build is successful](https://copr.fedorainfracloud.org/coprs/g/design-suite/xournalpp/build/3707080/) with the recent commit using the gtest system.

**Comment by Technius** [comment]
Thanks for testing!

**Pull request merged**
