### PR TITLE
Fix spelling in README.md

### PR DESCRIPTION
**Pull request by mb720**
Hi and thanks a lot for Xournal++!

I'd like to offer a few improvements to the readme with regards to spelling, punctuation, and wording.

### CODE REVIEW

**Comment by bhennion** [comment]
Hey! Thanks a lot for this. This looks good! Merging it right now.

**Comment by rolandlo** [comment]
The package description was unified in `README.md`, `package_description`, `debian/control` and `desktop/com.github.xournalpp.xournalpp.appdata.xml` before. Now it has only  been improved in `README.md`. 
@mb720 Would you have time to create a PR that adds these changes to the package description in the other three files?

**Comment by bhennion** [comment]
Ah sorry, I merged this to soon!

**Comment by mb720** [comment]
> The package description was unified in `README.md`, `package_description`, `debian/control` and `desktop/com.github.xournalpp.xournalpp.appdata.xml` before. Now it has only been improved in `README.md`. @mb720 Would you have time to create a PR that adds these changes to the package description in the other three files?

I don't have much time on my hands at the moment, sorry.

Is there a way to reduce duplication and maybe have `README.md` generated in parts from the contents of `package_description`, for example?

**Comment by rolandlo** [comment]
@mb720 It would be possible to write a script that synchronizes the files. That requires some work though. Direct inclusion is probably not possible.

**Pull request merged**
