### PR TITLE
Changing the console encoding to utf-8 on windows

### LINKED ISSUE #2395: Under windows there is something wrong with the terminal messages:
Under windows there is something wrong with the terminal messages: 
grafik

_Originally posted by @rolandlo in https://github.com/xournalpp/xournalpp/issues/2391#issuecomment-726762477_

### PR DESCRIPTION
**Pull request by Febbe**
- This only works for windows v. >= 1804

Fixes #2395

### CODE REVIEW

**Comment by Febbe** [comment]
This is only a Quick fix. In my opinion, all `»` and `«` should be replaced by upper `"`, which are more internationally. 
`»` and `«` are mostly used in middle Europe. And there they are used differently: By France and Switzerland `«text»`. In Germany and Austria »text«.

**Comment by Technius** [comment]
> This only works for windows v. >= 1804

If this is the case, it would be better to just replace the double angle bracket characters with double quotes. There's no reason to break compatibility so significantly for such a trivial issue (99% of Windows users will not care about console output).

**Comment by Febbe** [comment]
The thing is, that this would break all translations with those "Guillemets".

**Comment by Febbe** [comment]
> > This only works for windows v. >= 1804
> 
> If this is the case, it would be better to just replace the double angle bracket characters with double quotes. There's no reason to break compatibility so significantly for such a trivial issue (99% of Windows users will not care about console output).

I think xournalpp will still run, but the console output just does not change to utf-8.

**Review by rolandlo — APPROVED** [review]
Console messages look fine with this PR on Windows.

**Comment by LittleHuba** [comment]
Will merge tomorrow if nobody has an issue with it.

**Pull request merged**
