### PR TITLE
Add minimal toolbar

### PR DESCRIPTION
**Pull request by rolandlo**
For performance reasons #3242 (on MacOS BigSur), for having a distraction-free toolbar for basic needs (see https://github.com/xournalpp/xournalpp/discussions/3262) and for devices with a low screen-resolution (such as the pinephone #2139) I am adding this minimal toolbar. It looks like this (with low screen resolution):
grafik

For everything else the menubar can be used. It's easy for users to create a customized toolbar that extends on this one.

### CODE REVIEW

**Comment by rolandlo** [comment]
Actually for the Pinephone it would be better to have the same tools horizontally (top toolbar). Maybe add a horizontal minimal toolbar as well.

**Review by Technius — COMMENTED** [review]
I really like this, although I feel like it would be better if there were more zoom options.

**Comment by rolandlo** [comment]
> I really like this, although I feel like it would be better if there were more zoom options.

I can add the zoom slider. There are marks for the distinguished zoom levels. My goal was that the toolbar fits onto my screen when I use 200% scaling on my 2560x1440 screen (so effectively 1280x720 resolution). It won't fit with the zoom slider (or with any other additional tool), but it will still fit on a slightly larger screen, which is good enough for MacOS users.

What do you think about the idea of adding a `Minimal Left` and a `Minimal Top` toolbar with the same tools (one of them with the tools on the left, the other with the tools on the top)?

**Comment by rolandlo** [comment]
This toolbar fits with 1600x900 resolution.
grafik

On the top it fits on even smaller screen resolutions (like 1280x720, with Gnome dock on the left).
grafik

**Comment by Technius** [comment]
This looks good for a default. Users with more exotic devices will probably customize the toolbar anyways.

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised.

**Pull request merged**
