### PR TITLE
Merge release branch into master

### PR DESCRIPTION
**Pull request by bhennion**
The only conflicts were around the changes of #5583. I think I got it right but better safe than sorry.

@febbe @rolandlo @c-ola could you please check that your changes were merged as expected?

### CODE REVIEW

**Comment by Febbe** [comment]
My changes look good

**Comment by c-ola** [comment]
My changes look good as well.

**Review by rolandlo — COMMENTED** [review]
My changes have been merged as expected, but:

- Can the warnings https://github.com/xournalpp/xournalpp/pull/5599#issuecomment-2037624420 be fixed before merging back? They are really annoying.
- In #5583 we added quite some debug messages for console output. Do we really want to keep them?
- In #5583 I found one case for MacOS where there is an inconsistency between icons and background: When `GTK_THEME` is set to a light theme, but MacOS uses dark theme. Then the background is light and the icons are dark. The wrong icons are used. There is an easy fix, so would you allow me to push it before merging back? Sorry for not noticing earlier.

**Comment by rolandlo** [comment]
> @rolandlo The warnings from #5599 are already on master (this PR was merged to master). This has nothing to do with merging the release branch.

Ok, I see. The pipeline is failing for some (unrelated) reason though.

**Pull request merged**
