### PR TITLE
Allow the default LaTeX text when inserting to be configurable

### LINKED ISSUE #4251: Change Latex default text x^2
Hi, is there a way to set the default Latex text different from `x^2`. I have a use case where I would like to insert current date easily and clicking on the Latex button with a default `$\today` would be helpful.

### PR DESCRIPTION
**Pull request by hyperupcall**
Closes #4251. Modeled after the "genCmd" setting key.

Verification:
	- Manual testing

### CODE REVIEW

**Comment by rolandlo** [comment]
Thanks for the contribution. The `xournalpp.pot` file (which is auto-regenerated after the merge) should be removed.

**Comment by hyperupcall** [comment]
Fixed by latest changes :+1:

**Review by rolandlo — APPROVED** [review]
Thanks again for this PR. Looks good codewise and works fine.
Merging in 24 hours if no objections are raised.

**Comment by bhennion** [comment]
Thanks a lot for the great work!

**Pull request merged**
