### PR TITLE
New Layout possibility, and new Layout system

### LINKED ISSUE #2700: Suggest new default layout for the lesson note
Hi to every body
I've been a user of yours for some time now
I want propose to you, my custom layout for the note during lesson.
I hope you decide tu add it to the default layotu to help other out of me

Best reguard
Emanuele

```
[Right hand Note Taking Copy]
toolbarTop1=SAVE,NEW,OPEN,SEPARATOR,CUT,COPY,PASTE,SEPARATOR,UNDO,REDO,SEPARATOR,PEN,ERASER,HIGHLIGHTER,IMAGE,TEXT,HAND,MATH_TEX,SEPARATOR,DEFAULT_TOOL,SEPARATOR,INSERT_NEW_PAGE,DELETE_CURRENT_PAGE,SEPARATOR,GOTO_BACK,GOTO_FIRST,GOTO_LAST,GOTO_NEXT,SELECT_REGION,SEPARATOR,VERTICAL_SPACE,SELECT_RECTANGLE,SEPARATOR,CUSTOMIZE_TOOLBAR
toolbarLeft1=COLOR(0xffffff),COLOR(0xffff00),COLOR(0xff8000),COLOR(0xff00ff),COLOR(0x00ff00),COLOR(0x00c0ff),COLOR(0x808080),COLOR(0x008000),COLOR(0xff0000),COLOR(0x3333cc),COLOR(0x000000),COLOR_SELECT,SEPARATOR,PRESENTATION_MODE,ZOOM_100,ZOOM_FIT,ZOOM_IN,ZOOM_OUT,ZOOM_SLIDER,PAIRED_PAGES
toolbarLeft2=VERY_FINE,FINE,MEDIUM,THICK,SEPARATOR,VERY_THICK,TOOL_FILL,SEPARATOR,DRAW_CIRCLE,DRAW_RECTANGLE,RULER,DRAW_COORDINATE_SYSTEM,DRAW_ARROW,DRAW_SPLINE,SHAPE_RECOGNIZER,ROTATION_SNAPPING,GRID_SNAPPING,SEPARATOR
name=Note for lesson (dextrose)

```

### PR DESCRIPTION
**Pull request by Alfystar**
Closes #2700 

Hi to every body,
i want propose to you this modification of the code to add the possibility to implement layout with more than one of the same object on the screen ( in particular, to have the floating toolbox, with the duplicates of the buttons)

The necessity was felt after i tried to add 3 new layout, and i encounter this limit, so i decided to solve it with this solution.
I think is elegant, and in all my test, the functionality are the same as before, with the obvious improvements. 

I hope my work like you, if there are any problem, i'm here to correct their.

### CODE REVIEW

**Comment by rolandlo** [comment]
Thanks for the PR. I had only a brief look. When moving the zoom slider in one of your toolbar layouts Xournal++ was crashing sometimes (see error log below). There were warnings like
`(xournalpp:88603): Gtk-WARNING **: 13:26:07.908: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton`

Moreover I am missing the font select button (compared to the Xournal++ toolbar).

<details>
<summary> Error log </summary>

```
Date: Tue Feb  2 13:22:28 2021
Error: signal 11
[bt]: (0) build/src/xournalpp(+0x1fb33b) [0x55b97b93133b]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7fe694cbc950]
[bt]: (2) build/src/xournalpp(_ZN11ZoomControl18updateZoomFitValueEm+0xc2) [0x55b97b884a02]
[bt]: (3) build/src/xournalpp(+0x14ed6e) [0x55b97b884d6e]
[bt]: (4) build/src/xournalpp(+0x2052f2) [0x55b97b93b2f2]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x31fbd) [0x7fe69593dfbd]
[bt]: (6) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x15f) [0x7fe6962353df]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x53788) [0x7fe696235788]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fe696235853]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1cd) [0x7fe69565a54d]
[bt]: (10) build/src/xournalpp(_ZN11XournalMain3runEiPPc+0x4d2) [0x55b97b813452]
[bt]: (11) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7fe694ca3cb2]
[bt]: (12) build/src/xournalpp(_start+0x2e) [0x55b97b7ea90e]


Try to get a better stracktrace...
[bt] #1 build/src/xournalpp(+0x1fb8bf) [0x55b97b9318bf]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7fe694cbc950]
??:0
[bt] #3 build/src/xournalpp(_ZN11ZoomControl18updateZoomFitValueEm+0xc2) [0x55b97b884a02]
??:0
[bt] #4 build/src/xournalpp(+0x14ed6e) [0x55b97b884d6e]
??:0
[bt] #5 build/src/xournalpp(+0x2052f2) [0x55b97b93b2f2]
??:0
[bt] #6 /usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x31fbd) [0x7fe69593dfbd]
??:0
[bt] #7 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x15f) [0x7fe6962353df]
??:0
[bt] #8 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x53788) [0x7fe696235788]
??:0
[bt] #9 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fe696235853]
??:0
[bt] #10 /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1cd) [0x7fe69565a54d]
??:0
[bt] #11 build/src/xournalpp(_ZN11XournalMain3runEiPPc+0x4d2) [0x55b97b813452]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7fe694ca3cb2]
??:0
[bt] #13 build/src/xournalpp(_start+0x2e) [0x55b97b7ea90e]
??:0
```
</details>

**Comment by Alfystar** [comment]
> There were warnings like
(xournalpp:88603): Gtk-WARNING **: 13:26:07.908: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

About this warning, i need same help... I don't undestand how to remove the precedent menù to add the new one... any idea?

> When moving the zoom slider in one of your toolbar layouts Xournal++ was crashing sometimes (see error log below).

About this now i start to reproduce the error with GDB to find the problem

> Moreover I am missing the font select button (compared to the Xournal++ toolbar).

About this, now I'll copy/paste the old default layout, there should have been error during test :sweat_smile:

**Comment by Alfystar** [comment]
I solve all the issue exept the 
> There were warnings like
(xournalpp:88603): Gtk-WARNING **: 13:26:07.908: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

For the zoom the problem was in the destructor of the object, it didn't remove the pointer to a third list.

about this warning, please help me... is my limit but i don't know well the gtk tecnology...

**Comment by personalizedrefrigerator** [comment]
It would be really nice to have this! I hope it can be reviewed/merged soon!

**Comment by LittleHuba** [comment]
This needs some additional work. There are comments within the code that refer to `TODOs`. These TODOs would lead to bugs later on if we do not handle them within this PR.

**Review by LittleHuba — CHANGES_REQUESTED** [review]
This needs some additional work. There are comments within the code that refer to TODOs. These TODOs would lead to bugs later on if we do not handle them within this PR.

**Comment by Alfystar** [comment]
Hello, I'm here

Where you talk? The todo are in my job or in all the fork?

**Comment by LittleHuba** [comment]
Sorry I misread some comments please forget my previous comment. You have many typos in your changes. I'll go over your work once more and propose some changes.

I also feel that we should split up this PR into multiple smaller ones. One PR just for the changes to allow multiple similar tool buttons. And a separate PR for each new layout.

**Comment by Alfystar** [comment]
There isn't problem
For me is OK to sub-split the PR, tell me how

The Only, until this 15 October I'm busy because I have to graduate in my university, but for sure I'll try to help and follow you in my free time

**Comment by LittleHuba** [comment]
No worries there is no hurry in this.

Please separate the PR as follows:
1. One PR should contain all changes that enable multiple ToolButtons of the same type
2. An additional PR **per** new toolbar layout

**Comment by Alfystar** [comment]
> No worries there is no hurry in this.
> 
> Please separate the PR as follows:
> 
> 1. One PR should contain all changes that enable multiple ToolButtons of the same type
> 2. An additional PR **per** new toolbar layout

I'm finally free!!! 
Now i want restart to help with my contributes :smile: 

How i can divide the pull request? In my repository the code is all together, what steps i'll have to walk?

**Comment by LittleHuba** [comment]
How I understand your issue, the simplest way will be to restart. First give us some PRs that provide all the prerequisites you require for your work. Once those are merged, create one PR that just introduces your new feature.

That should give us decently sized units we can merge.

**Comment by Alfystar** [comment]
Hello every one, sorry for that another delay, 
i was started in that days my new job, and honestly first days was more hard that i thinked.
Any way, as @LittleHuba asked me, now i have divided my pull request in 2 steps

I realy hope now is the end of the pull fase, and  and I really can't wait to see my work in mainline

Have a nice Holliday :smile: 
Emanuele

**Pull request closed without merging**
