### PR TITLE
Fix sidebar page preview stuck and not responding

### LINKED ISSUE #3585: Sidebar page preview stuck and not responding
**Affects versions :**
I guess all versions.

**Describe the bug**
When annotating a pdf with the same amount of pages as the document edited before the sidebar page preview is stuck and does not respond on clicking on page previews.

**To Reproduce**
1. Open a fully new Xournalpp instance
2. Annotate any pdf with exactly one page

### PR DESCRIPTION
**Pull request by fabian-thomas**
- fixed a bug where the sidebar page preview was stuck and not responding (closes #3585)

### CODE REVIEW

**Comment by Febbe** [comment]
This is actually a fix for release1.1, can you cherry-pick this?

**Comment by fabian-thomas** [comment]
> This is actually a fix for release1.1, can you cherry-pick this?

Like that?

**Comment by Febbe** [comment]
Yes like that. 

Actually the code you removed makes a bit sense, no recreation of dynamic objects if the size did not change.
This means your change has some performance implicattions for large files. It enforces a complete recreation of all `SidebarPreviewBaseEntry`s. Isn't it possible to fix them instead of reallocating all? (Using a `std::vector<SidebarPreviewBaseEntry>` instead of std::vector<SidebarPreviewBaseEntry*> may kill the overhead here.)

Also I don't see, why there should be a problem with the mutex behavior. That is correct here (unlock locked mutex on return).

**Comment by fabian-thomas** [comment]
> Yes like that.
> 
> Actually the code you removed makes a bit sense, no recreation of dynamic objects if the size did not change. This means your change has some performance implicattions for large files. It enforces a complete recreation of all `SidebarPreviewBaseEntry`s. Isn't it possible to fix them instead of reallocating all? (Using a `std::vector<SidebarPreviewBaseEntry>` instead of std::vector<SidebarPreviewBaseEntry*> may kill the overhead here.)

Yeah, that's true. But when and how often is this function actually called? I've attached a debugger and tried to trigger updatePreviews. After 2 minutes of testing it was only called when creating a new document.

Could you evaluate your idea with `std::vector<SidebarPreviewBaseEntry>` further?
The only solution I see is that we pass a boolean value to `updatePreviews` which gives information about a full document change. We just don't have that information in that function.

> 
> Also I don't see, why there should be a problem with the mutex behavior. That is correct here (unlock locked mutex on return).

The inner block is totally fine but don't needed anymore if we remove the if condition.

**Comment by Febbe** [comment]
> Could you evaluate your idea with std::vector<SidebarPreviewBaseEntry> further?
Currently, all SidebarPreviewBaseEntry`s may have a random position on the heap and must be freed, allocated every run.
But by dropping the pointer, all SidebarPreviewBaseEntry's are located next to each other, also the space is not allocated on each insertion, since vectors won't shrink. This is then nearly equal to just updating the Elements.
[It also is faster, because it removes one indirection step and increases locality](https://en.wikipedia.org/wiki/Locality_of_reference)

> The inner block is totally fine but don't needed anymore if we remove the if condition.

Ah, thought, that the discussion in your other thread over g_mutex is because of this issue. Never mind then.

> Yeah, that's true. But when and how often is this function actually called? I've attached a debugger and tried to trigger updatePreviews. After 2 minutes of testing it was only called when creating a new document.

Then we should just merge your fix and leave the Pointer removal to your refactoring?

**Comment by Febbe** [comment]
Thank you for your work!

**Pull request merged**
