### PR TITLE
Add gtk3-immodules for generating AppImages.

### LINKED ISSUE #5493: IME on Linux don't work
### Operating System

Windows

### (Linux only) Distribution

Manjaro

### (Linux only) Desktop Environment

MATE

### (Linux Only) Display Server

None

### Installation Method

Appimage

### Xournal++ Version

1.2.2

### libgtk Version

3.24.20

### Bug Description

IME like fcitx don't work.

### Expected Behaviour

It works.

### Steps to Reproduce

1. Press the shortcut of activation “Ctrl+Space” for fcitx.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tattsan**
Fixes #5493.

### CODE REVIEW

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjk4MTMvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjk4MTMvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjk4MTMvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjk4MTMvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 22.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjk4MTMvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMi4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by tattsan** [comment]
How can I test the AppImage binary with this PR generated on GitHub?

**Comment by tattsan** [comment]
OK! `fcitx` and `ibus` are successfull, but `uim` is not. ‘gcins‘ has not been tested yet.

**Comment by tattsan** [comment]
`gcin` seems to work well. 

As for `uim`,  if I extract the AppImage under `/tmp` and modify `immodules.cache` as following:
```
--- squashfs-root/usr/lib/gtk-3.0/3.0.0/immodules.cache.orig    2024-02-25 16:09:30.595139722 +0900
+++ squashfs-root/usr/lib/gtk-3.0/3.0.0/immodules.cache 2024-02-25 16:10:05.578137649 +0900
@@ -43,7 +43,7 @@
 "im-ti-et.so"
 "ti_et" "Tigrigna-Ethiopian (EZ+)" "gtk30" "/usr/share/locale" "ti"

-"im-uim.so"
+"/tmp/squashfs-root/usr/lib/gtk-3.0/3.0.0/immodules/im-uim.so"
 "uim" "uim" "uim" "/usr/share/locale" "ja:ko:zh:*"

 "im-viqr.so"
```
then `uim` works well. But `immodules.cache` is a generated file, and should not be modified manually.  Or if I copy the module `im-uim.so` on my local machine to
`/tmp/squashfs-root/usr/lib/gtk-3.0/3.0.0/immodules/`, `uim` also works well. I feel this is an upstream issue.

**Comment by tattsan** [comment]
Since `uim` is legacy and has few users (but I'm one of them :smile:), I think it is a low priority. On the other hand, there is a possibility that uim will be improved on the Ubuntu side, so I would like to leave `im-uim.so` undeleted.

**Comment by rolandlo** [comment]
Is it possible that the package `uim-mocz` is missing? During the installation `uim-mozc, uim-anthy, uim-skk` were listed as suggested (but not installed) packages.

**Comment by tattsan** [comment]
> Is it possible that the package `uim-mocz` is missing? During the installation `uim-mozc, uim-anthy, uim-skk` were listed as suggested (but not installed) packages.

Both `skk/uim` and `anthy/uim` works under the 'immodules.cache hack' mentioned in https://github.com/xournalpp/xournalpp/pull/5520#issuecomment-1962849477 without `uim-skk` or `uim-anthy` , it should work without those packages.

**Comment by rolandlo** [comment]
Thanks @tattsan for the fix. Merging in 24 hours if no objections are raised.

**Comment by tattsan** [comment]
Thanks!
Now I'm preparing a PR for the master to add gtk4-immodules. Currently, gtk4 is only supported by `fcitx5` and `ibus`. Is it possible to also use gtk3-immodule with Xournal++ 1.3.x ?

**Pull request merged**
