### PR TITLE
Update changelog to prepare for 1.1.0

### PR DESCRIPTION
**Pull request by rolandlo**
This is  #2839 squashed and rebased. While fixing the merge conflict I added the (second last) line about fixing the BigSur startup crash and removing the integration into the Mac menu bar.

### CODE REVIEW

**Comment by rolandlo** [comment]
@Technius In my opinion this PR is ready to be merged. Any objections?

**Comment by Technius** [comment]
LGTM.
* If MSYS updated in time, I would add a line referring to the GTK dependency update.
* I would add a line to "Breaking Changes" explaining that the old input system has been removed, which may affect some users.

**Comment by rolandlo** [comment]
> LGTM.
> 
>     * If MSYS updated in time, I would add a line referring to the GTK dependency update.
Unfortunately, MSYS2 on Azure Pipelines only updated from `mingw-w64-x86_64-gtk3-3.24.29-1` to `mingw-w64-x86_64-gtk3-3.24.29-2` (3 days ago). That won't contain the improved input handling on Windows.
> 
>     * I would add a line to "Breaking Changes" explaining that the old input system has been removed, which may affect some users.
Ok, I will amend it to the current commit.

**Comment by rolandlo** [comment]
Ok, done!

**Pull request merged**
