### PR TITLE
Select correct tool when selecting default tool

### PR DESCRIPTION
**Pull request by p3tkovicn**
Bug fix attempt for selecting correct tool when Tools->Default Tools is selected.

### CODE REVIEW

**Comment by rolandlo** [comment]
Please add a precise description of the bug you attempt to fix, ideally as an Issue on the [issue tracker](https://github.com/xournalpp/xournalpp/issues/). If an issue already exists, link it to this PR.

**Comment by p3tkovicn** [comment]
Thank you for your answer. Issue already exists and link to issue is
https://github.com/xournalpp/xournalpp/issues/3918

**Review by rolandlo — APPROVED** [review]
LGTM. Fixes #3918 

Merging in 24 hours if no objections are raised.

**Comment by rolandlo** [comment]
I forgot about the branch you'd like to merge the fix. Since it is a bugfix of an issue that is present in release 1.1.1 already, it should be rebased on the `release-1.1` branch.

**Comment by rolandlo** [comment]
@p3tkovicn In case you need help: One way to rebase on `release-1.1` is the following (after checking out your branch and adding the remote upstream pointing to https://github.com/xournalpp/xournalpp.git):
```term
git reset dcad9363071a067481bd525fc4c05cf3117ad31c
git stash
git reset --hard upstream/release-1.1
git stash pop
```
and then `add` and `commit` your changes and `push` with the `--force` option.

The direct way (`git rebase upstream/release 1.1`) of doing the same thing would confront you with a lot of merge conflicts and cannot be recommended in this case.

**Comment by p3tkovicn** [comment]
@rolandlo Thank you very much. 
I was trying to do it direct way and every time I had some type of problem. I tried few approaches but none of them succeeded. Eventually when I would run out of options i would ask for help, but this was opportunity for me to dive deeper into problems that arise when rebasing. 

Hopefully i will have time to do this today.

Once more, thank you.

**Comment by rolandlo** [comment]
Thanks for the fix! I'm merging.

**Pull request merged**
