### PR TITLE
UI multiple items

### PR DESCRIPTION
**Pull request by Alfystar**
#2735

Second pull request to add the new UI manager system

### CODE REVIEW

**Comment by rolandlo** [comment]
@Alfystar Thanks for contributing. Please rebase on current master and solve the merge conflicts.

**Comment by Alfystar** [comment]
Hi @rolandlo 
I'll try, but honestly after 1 year from my original contribution i don't think is even more possible merge the code.
After my first merge try, i see there are too much differents (376 commit in master) and for that reason one of my change is now inside a file  deleted.

For what i can see, probably my contribution now is lost because the intentiion to merge it in mainline there was accepted too late and the project is too different now. 
I'm displease because i havn't the time to do AGAINE this work, and onestly i don't undestandy why there was so big delay, my change liked a lot, and  it would not have been difficult to add it at the time.
If some ones of you have one idea to help me, my mind is open, but onestly i think the only solution is do agane the work from the current project state, but now i have a lot of things to do and isn't one of my priorities.

Have a nice holliday
Alfystar

**Comment by rolandlo** [comment]
> For what i can see, probably my contribution now is lost because the intentiion to merge it in mainline there was accepted too late and the project is too different now. I'm displease because i havn't the time to do AGAINE this work, and onestly i don't undestandy why there was so big delay, my change liked a lot, and it would not have been difficult to add it at the time. If some ones of you have one idea to help me, my mind is open, but onestly i think the only solution is do agane the work from the current project state, but now i have a lot of things to do and isn't one of my priorities.

I'm sorry for the work you invested that may be lost now and understand your disappointment. As for the reasons of the delay:
- the floating toolbox was in a bad shape code-wise and several issues had to be fixed, which were in conflict with your PR
- memory management for the toolbar is kind of delicate (we had several sources for potential memory leak) and it required a lot of experience to review your PR
- there were some open issues with your PR. For instance the warning ```(xournalpp:88603): Gtk-WARNING **: 13:26:07.908: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton``` was never fixed. You needed some help there, but apparently nobody new the answer off hand
- there are always other open tasks and other duties. We all contribute to this project in our free time, which is quite limited at times.

I hope you understand. If someone will do something along your ideas he or she will certainly look at your code and benefit from it. 
Wish you nice holidays as well.

**Comment by rolandlo** [comment]
Closing the PR, since there is no intention to work on it.

**Pull request closed without merging**
