### PR TITLE
Fix long text being truncated in LaTeX tool

### PR DESCRIPTION
**Pull request by tattsan**
This change was proposed in #3293.  Based on release-1.2.

### CODE REVIEW

**Comment by rolandlo** [comment]
Can you please elaborate why you prefer `varwidth=false` to `varwidth=\maxdimen` as was suggested in https://github.com/xournalpp/xournalpp/issues/3293#issuecomment-1619194026?

**Comment by tattsan** [comment]
Note that no `varwidth` option is equivalent to `varwidth=false`.
We can see the difference between  `varwidth=false` and `varwidth=\maxdimen` when a TeX code contains  paragraph skips. Consider the following 3 sources.

1. 
```
a\)\(b
```
2.
```
a\)
\(b
```
3.
```
a\)

\(b
```
First two contain no paragraph skip, and the result is same for both `varwidth` option.

1. 
AB_H_nonSP

2. 
AB_H_withSP

The third code contains a paragraph skip. If you use `varwidth=false`, the result is the same as 2. If you use `varwidth=\maxdimen`, the result is the following:

3. when `varwidth=\maxdimen`
AB_V

If you want to write a code which exit math mode like above,  `varwidth=\maxdimen` is preferable. However, if you want to create paragraphs, I think it's better to explicitly use the minipage environment.

**Comment by tattsan** [comment]
The above result shows `varwidth=false` is incompatibile with the current version.
However `varwidth=\maxdimen` is also incompatible in that it changes the value of `\linewidth`.

* With `varwidth=true/false` the code `\the\linewidth` shows the value `345.0pt`,
* With `varwidth=\maxdimen` the code `\the\linewidth` shows the value `16383.99998pt`.

For those who have been using the ‘\linewidth`'s value, this is inconvenient.

**Comment by tattsan** [comment]
If `varwidth=false`, the `varwidth` package will not be loaded and you will not be able to use the `varwidth` environment.
So we should add `\RequirePackage{varwidth}` in this case.

**Comment by tattsan** [comment]
The `\linewidth`  is essentially meaningless, since we are trying to eliminate width limitations for TeX objects. 
On the other hand, however, some of you who have been inserting coherent texts in the minipage environment, 
for example, may have specified the size in multiples of `\linewidth`. This can be reconciled by changing the value of
 `\linewidth` in the middle. This does not affect the width limit of the TeX object.
```
\begin{document}
  \setlength{\linewidth}{345.0pt}%
  % Check if the formula is empty
  \settoheight{\pheight}{\getstored[1]{preview}}%
  \ifthenelse{\pheight=0}{\GenericError{}{xournalpp:blankformula}{}{}}

  % Render the user input
  \textcolor{xpp_font_color}{\getstored[1]{preview}}
\end{document}
```

However, it is not a good idea to write a magic number of 345.0pt (the default value of `\linewidth` of the article.cls), 
so it is better to refer to some value (such as the setting of standalone.cfg or the size of the background paper in Xournal++).

**Comment by tattsan** [comment]
I have tried to keep compatibility with the previous version and set varwidth near to maxmum.
If the value of varwidth is `\maxdimen`, an error occurs when the width of the content is close to `\maxdimen`, 
so I set it to `0.999\maxdimen`.  The `\textwidth`, `\linewidth`, and `\columnwidth`, which may be referred to as text width,
are the same values as before. The upper limit of `varwidth` matches  the value of`\hsize`.

**Comment by tattsan** [comment]
> If the value of varwidth is \maxdimen, an error occurs when the width of the content is close to \maxdimen,

This error occurs because the width of the box becomes `\maxdimen + 2*border` .

> so I set it to 0.999\maxdimen

So this can be maximized by the following:
```
\makeatletter
  \setlength{\hsize}{\maxdimen}%
  \addtolength{\hsize}{-\sa@border@left}%
  \addtolength{\hsize}{-\sa@border@right}%
}
\makeatother
```
which should be executed  after `\begin{document}`.

**Review by rolandlo — APPROVED** [review]
LGTM

Merging in 24 hours if no objections are raised.

**Comment by tattsan** [comment]
Thanks!

**Comment by rolandlo** [comment]
Thanks @tattsan for this fix!

**Pull request merged**
