### PR TITLE
Highlight cursor position - added

### LINKED ISSUE #786: Big Cursor with yellow opaque circle
Dear authors,
for screen-cast it would be great to have a "big cursor" with a yellow/red/whatever opaque circle. Since you overwrite the normal cursor-scheme DMZ-highlight is not working in Xournalpp. Joerg

### PR DESCRIPTION
**Pull request by luco5826**
Hi! I added the feature requested in #786 .
Now under Preferences -> View you can enable the highlighting option.
Right now I made it available only when in "Big Cursor" mode, but if you think that it should be available without that mode too, no problem, we only need to move one if outside a block ;)
Fixes #786

### CODE REVIEW

**Comment by JoergBitzer** [comment]
Thanks a lot. Just checked it out and it looks good. IMHO it would be better to have this option in both modes (small and big cursor). . However, at the moment the first item "Highlight cursor" depends on the second "big cursor". The view in preferences|view|cursor suggest that they are mutual independent.
 And since you said it is easily done. Your fast response is very appreciated. Thanks again!

**Comment by campos20** [comment]
Is there an option the make the highlighting always on? And not just when we are writing?

**Comment by campos20** [comment]
nvm

https://github.com/xournalpp/xournalpp/issues/1290#issuecomment-505781950

Thank you for your great work!

**Comment by LittleHuba** [comment]
Not that I know of currently. But you can create a feature request if there is none already.

**Pull request merged**
