### PR TITLE
fix the page is scrolling to the wrong position

### PR DESCRIPTION
**Pull request by peetCreative**
Fixes for me issue #416

### CODE REVIEW

**Comment by andreasb242** [comment]
For me the Zoom is not not working correct anymore, neither by touch nor by mouse.

@luco5826 or @morrolinux can you recheck?

**Comment by andreasb242** [comment]
@peetCreative Is this really working for you? How did you test this?

Even with the mouse and with the touch it doesn't work.
If I do a review, I look at code, like possible crashes, something which looks really wrong or so, and I probably don't see a bug.

If I analyze it now in detail, the only relevant change you did is:
zoomWidgetPosX and zoomWidgetPosY is scaled.

But this are coordinates which are on the widget side, not on the document side, therefore are independent of the zoom.

With your change now: the document moves down/right if I zoom in, or up/left if I zoom out.

**Comment by luco5826** [comment]
I can only test by zooming via CTRL+Scroll and it always zooms to the top left corner of the document

**Comment by andreasb242** [comment]
Ok. Thank you. I'll revert this commit.

**Pull request merged**
