### PR TITLE
Fix touch enabling on quit, remove timeouts when touch disabling is turned off and remove dead code

### LINKED ISSUE #4343: Freeze or crash, if 'pen input' -> Ctrl-S -> Ctrl-Q succesively.
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11
 - libgtk: 3.24.34
 - Version of Xournal++: Master (freeze) , release-1.1.2 (crash)
 - Installation method: buit from source(master), Arch Linux package (release)

**To Reproduce**
1. Write something with a pen.
2. Use keyboard shortcut 'Ctrl-s' (save) without delay.
3. Use keyboard shortcut 'Ctrl-q' (exit) without delay.

Then you'll see crash message if you use 'release',
and you'll be faced with freeze if you use 'master'.

**Expected behavior**
No crash or freeze.

**Additional context**
The edited .xopp files seems to be correctly saved. So this crash is not so critical, but annoying.

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes  #4343

- [x]  rebase on `release-1.1`.

### CODE REVIEW

**Comment by rolandlo** [comment]
@tattsan Coudl you please try the PR, both with hand recognition turned off and turned on?

**Comment by rolandlo** [comment]
@LittleHuba Coudl you please take a look as well?
You introduced the `TouchDisableGdk` class with the new input system, but in the same PR #1070 you disabled it again (in 0be0ab7e419fb8009181f65e27f41b177d5727da). Since it was not used for more than 3 years, and most likely didn't work as intended, I suggest to remove it. Do you have any objections to that?

**Comment by tattsan** [comment]
Thanks for the fix!
I've tried the PR on three different devices, and several combinations of settings on `Tochscreen` tab in the preferences.
Everything works well! :+1:

**Comment by rolandlo** [comment]
Thanks a lot for testing @tattsan 
I rebased on `release-1.1`. This is ready from my side.

**Review by Technius — APPROVED** [review]

**Comment by rolandlo** [comment]
Merging in 24 hours, if no objections are raised.

**Pull request merged**
