### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by LittleHuba**
Enjoy!

### CODE REVIEW

**Comment by JJones780** [comment]
Gee. I was all excited to read the new Klingon...  a bit misleading Mr. @LittleHuba!
I guess these are blanks to allow @JasMich and others to do the translating... I look forward to Klingon braggin' rights.

Qapla'!

_(I had to look that up... but it does sound scarily familiar... ;)_

**Comment by LittleHuba** [comment]
There is something very wrong with Crowdin... Take a look at the diff of the german translation... It essentially removes all translations?!

**Comment by LittleHuba** [comment]
> I guess these are blanks to allow @JasMich and others to do the translating...
Yeah you have to activate the languages before they can be translated.

**Comment by LittleHuba** [comment]
> There is something very wrong with Crowdin... Take a look at the diff of the german translation... It essentially removes all translations?!

Ahh found the problem... Crowdin does only include approved translations. Will approve all currently existing translations.

**Pull request closed without merging**
