### PR TITLE
Fixed hang error for LaTeX preview

### PR DESCRIPTION
**Pull request by DUOLabs333**

### CODE REVIEW

**Review by rolandlo — COMMENTED** [review]
I think the `-halt-on-error` should be before the `'{}'`

**Comment by DUOLabs333** [comment]
Xournal says it's fine, but just to be on the safe side.

**Comment by DUOLabs333** [comment]
@rolandlo Fixed it.

**Review by rolandlo — APPROVED** [review]
LGTM
I will (squash and) merge this in 22 hours, if there are no objections.

**Comment by rolandlo** [comment]
Fixes #2922

**Review by Technius — APPROVED** [review]

**Comment by rolandlo** [comment]
Thanks @DUOLabs333, just merged it.

**Pull request merged**
