### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by LittleHuba**
Enjoy!

### CODE REVIEW

**Comment by fitojb** [comment]
Is it possible to merge these Crowdin PRs squashed? It generates a lot of commits as I edit the file and the Git log gets spammy IMO.

**Comment by LittleHuba** [comment]
I forgot to change to squashed mode for the last update. Sorry! Will squash this one before merging it.

**Comment by Technius** [comment]
Is this PR still relevant?

**Comment by LittleHuba** [comment]
Yes it is. The crowdin PRs are always relevant, as they are autogenerated based on the master branch.

If a Crowdin PR has for some reason merge conflicts (somebody updated the translations manually) just close it and Crowdin will create a new one based on master again.

**Pull request merged**
