### PR TITLE
Refactor layout & resizing routine

### PR DESCRIPTION
**Pull request by LittleHuba**
Original work done by @Febbe in #1213.

TODO:
- [x] Memory leak fixes
- [x] Remove auto typing

### CODE REVIEW

**Comment by LittleHuba** [comment]
OT:

@Febbe please create an account on Gitter so we can write with you via PM. Thanks!

**Comment by Febbe** [comment]
Found some memory leaks by compiling xournal with clang++ and -fsanitize=address.
I drawed some strokes on new pages and deleted the whole pages i also deleted some strokes with the eraser .

/home/fabian/CLionProjects/xournalpp/cmake-build-debug/src/xournalpp
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map

(xournalpp:12069): Gtk-CRITICAL **: 14:29:35.304: gtk_widget_queue_resize: assertion 'GTK_IS_WIDGET (widget)' failed

** (xournalpp:12069): WARNING **: 14:29:35.339: Error calculating zoom value

(xournalpp:12069): Gtk-WARNING **: 14:29:35.340: Theme parsing error: <data>:1:22: Junk at end of value for font-family
** Message: 14:30:42.958: MemoryLeak: sum 0 objects.

=================================================================
==12069==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x7fcc6cc95b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fcc6c3aa968 in g_malloc (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51968)

Direct leak of 7168 byte(s) in 11 object(s) allocated from:
    #0 0x7fcc6cc95f40 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef40)
    #1 0x7fcc66b1b998  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d998)

Direct leak of 4608 byte(s) in 18 object(s) allocated from:
    #0 0x7fcc6cc95b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fcc66b1b8ed  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d8ed)

Indirect leak of 16960 byte(s) in 530 object(s) allocated from:
    #0 0x7fcc6cc95b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fcc66b09fef  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbfef)

Indirect leak of 8893 byte(s) in 677 object(s) allocated from:
    #0 0x7fcc6cc2e538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x7fcc66b1b2f4 in FcValueSave (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d2f4)

Indirect leak of 6752 byte(s) in 211 object(s) allocated from:
    #0 0x7fcc6cc95d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fcc66b1bfd8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1dfd8)

Indirect leak of 4736 byte(s) in 148 object(s) allocated from:
    #0 0x7fcc6cc95d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fcc66b1b5c4  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d5c4)

Indirect leak of 1152 byte(s) in 36 object(s) allocated from:
    #0 0x7fcc6cc95d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fcc66b1b440  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d440)

Indirect leak of 288 byte(s) in 6 object(s) allocated from:
    #0 0x7fcc6cc95b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fcc66b15acd in FcLangSetCreate (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x17acd)

SUMMARY: AddressSanitizer: 66941 byte(s) leaked in 1638 allocation(s).

Process finished with exit code 1

**Comment by Technius** [comment]
How does this relate to #1249? Is this still being worked on?

**Comment by Febbe** [comment]
This is a finished partial fix.
Improved the resize and the repaint routine

**Comment by lehmanju** [comment]
Any objections? Needs to be merged for #1411

**Comment by LittleHuba** [comment]
Just fixed the issue I had 😉

**Comment by Febbe** [comment]
I think we can merge this now. I tested it enough. @lehmanju can you readd the code in your pr which you removed, like I explained you☺️.

**Comment by Febbe** [comment]
I'll merge this tomorrow CET 17:00 if no one complains.

**Pull request merged**
