### PR TITLE
Add undo action for selection moved with keyboard

### LINKED ISSUE #4835: Undo Doesn't Undo Moving Annotations
**Affects versions :**
 - OS: Linux (Manjaro 22.1)
 - (Linux only) Desktop environment: KDE Plasma 5 (Qt 5, KDE Frameworks 5, X Window System, Wayland)
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++: 1.1.3+dev (4c8acc1d)
 - Installation method: AUR install using yay. Package build attached:
[PKGBUILD.txt](https://github.com/xournalpp/xournalpp/files/11325222/PKGBUILD.txt)

**Describe the bug**
After moving annotations manually (using one of the select tools), the undo button will not restore the annotations to their original position.

**To Reproduce**
1. Select drawn annotations using one of the select tools.
2. Move the selection using the mouse or arrow keys.
3. Click the undo button.

**Expected behavior**
Upon clicking the undo button or hitting control+z, the annotations that have been moved are reverted back to their original position, and the redo button is set to redoing that undone movement.

**Screenshots of Problem**
I have attached a short video to demonstrate my issue:
[Xournal++ Undo Bug.mp4](https://user-images.githubusercontent.com/93878758/234356353-a2744703-0f59-4b3e-ab5d-6a2d4b64843e.mp4)

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #4835

### CODE REVIEW

**Review by bhennion — APPROVED** [review]
LGTM!

As a general remark: please avoid applying clang-format to the entire files, but rather just to the actual diff (via `git-clang-format`). It clutters the diff a bit, making it harder to know if chunks of the patch are actual changes or simple clang-formatting changes.

**Comment by rolandlo** [comment]
> As a general remark: please avoid applying clang-format to the entire files, but rather just to the actual diff (via `git-clang-format`). It clutters the diff a bit, making it harder to know if chunks of the patch are actual changes or simple clang-formatting changes.

I can undo those formatting changes. Seems I need to set up VS Code slightly differently so that it doesn't happen again.

**Comment by rolandlo** [comment]
The formatting changes are undone. 

Merging in 24 hours if no objections are raised.

**Review by Technius — APPROVED** [review]
LGTM.

Why does the bug result for keyboard movement but not mouse movement?

**Comment by rolandlo** [comment]
> LGTM.
> 
> Why does the bug result for keyboard movement but not mouse movement?

For mouse movement `EditSelection::mouseUp()` is called during the (mouse) button release event, after which `EditSelectionContents::updateContent` takes care of adding an undo action for the appropriate `CursorSelectionType`.

**Comment by rolandlo** [comment]
Thanks for the review @Technius 
I have incorporated your suggestions, but modified the description of the `addUndoAction`.

**Pull request merged**
