### PR TITLE
Cleanup of ZoomControl and fix of Zoom and Scroll

### LINKED ISSUE #1984: Zooming with Ctrl+Scroll scrolls down the page
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
When holding Ctrl and scrolling, zooming in simultanenously scrolls down the page. Conversely, zooming out scrolls up.

**To Reproduce**
1. Hold Ctrl
2. Scroll up/down

Reproduction rate 100%

**Expected behavior**
I expect to zoom in and out of the center of the screen

**Additional context**
I saw that there was an issue of the same problem in version 1.0.16 (#1753) but apparently it had been fixed and closed. I wasn't sure whether to comment on the old one or open a new one. If I did it wrong, I apologize.

### PR DESCRIPTION
**Pull request by Febbe**
Fixes #1984

### CODE REVIEW

**Comment by Febbe** [comment]
The handling of the zoom might still not be correct, since i just adapted the current handling.
In my opinion the zoom and scrolling should be in the same place and should be calculated over "change of basis" from the original scene.

The only relevant informations needed should be the transformation of the drawing rect, relative to the scene, and the bounds of the drawing rect itself. With that the new transformation can be calculated without additional information.

**Comment by ohthehugemanatee** [comment]
significant improvement on zoom UX for me (Manjaro, Swaywm).

But this version fails to load preferences (all fields are empty in the config panes I've seen), and bails out when I try to save preferences (even with no changes). `ERROR:/home/ohthehugemanatee/Projects/personal/xournalpp/src/gui/dialog/DeviceClassConfigGui.cpp:47:void DeviceClassConfigGui::saveSettings(): assertion failed: (deviceClassId != nullptr)`

**Comment by Technius** [comment]
> significant improvement on zoom UX for me (Manjaro, Swaywm).
> 
> But this version fails to load preferences (all fields are empty in the config panes I've seen), and bails out when I try to save preferences (even with no changes). `ERROR:/home/ohthehugemanatee/Projects/personal/xournalpp/src/gui/dialog/DeviceClassConfigGui.cpp:47:void DeviceClassConfigGui::saveSettings(): assertion failed: (deviceClassId != nullptr)`

That's strange, this PR doesn't touch device settings at all. Can you try backing up your settings and then deleting them to see if the problem persists with "fresh" settings?

**Comment by LittleHuba** [comment]
> That's strange, this PR doesn't touch device settings at all. Can you try backing up your settings and then deleting them to see if the problem persists with "fresh" settings?

This is typical if you switch from a too old settings version to a newer one. Just remove them and start from scratch.

**Comment by ohthehugemanatee** [comment]
you're right, the settings issue went away when I killed my `~/.xournalpp`. It also completely fixed the scroll issue from #2031 . So user testing checks out at least. :)

But help me understand: my normal build is 1.0.18, built on April 16. Has the settings storage format really changed so drastically in the last 1.5 months?

**Comment by LittleHuba** [comment]
The problem is whenever somebody adds some stuff to the settings it somehow breaks something else. The settings logic is quite complex and backwards-compatibility is hard to achieve. We'll have to take care of this issue at some point. For now resetting your settings file from time to time is the best thing to do to get rid of some awkward bugs.

**Comment by Technius** [comment]
> But help me understand: my normal build is 1.0.18, built on April 16. Has the settings storage format really changed so drastically in the last 1.5 months?

No, this is just a bug. We'd appreciate it if you could file a bug report with some more information about your crash.

The `1.0.x` series is actually about half a year older than `1.1.0+dev`. We've made numerous changes since then and have only selectively copied some of the bugfixes back.

**Comment by David96** [comment]
I also still encounter quite some laggy zooming behaviour after this commit when using the touch pinch gesture.
I was able to kind of improve the experience by applying this patch on top of this pull request:
```diff
diff --git a/src/gui/inputdevices/TouchInputHandler.cpp b/src/gui/inputdevices/TouchInputHandler.cpp
index af0d598a..a63e90c9 100644
--- a/src/gui/inputdevices/TouchInputHandler.cpp
+++ b/src/gui/inputdevices/TouchInputHandler.cpp
@@ -105,10 +105,8 @@ void TouchInputHandler::zoomStart() {
                            inputContext->getSettings()->getAddHorizontalSpaceAmount() :
                            0;
 
-    auto center = (this->priLastRel + this->secLastRel) / 2.0 - utl::Point<double>{double(hPadding), double(vPadding)};
-
+    this->lastZoomScrollCenter = (this->priLastRel + this->secLastRel) / 2.0 - utl::Point<double>{double(hPadding), double(vPadding)};
     this->startZoomDistance = this->priLastAbs.distance(this->secLastAbs);
-    lastZoomScrollCenter = (this->priLastAbs + this->secLastAbs) / 2.0;
 
     ZoomControl* zoomControl = this->inputContext->getView()->getControl()->getZoomControl();
 
@@ -118,9 +116,7 @@ void TouchInputHandler::zoomStart() {
         zoomControl->setZoomFitMode(false);
     }
 
-    Rectangle zoomSequenceRectangle = zoomControl->getVisibleRect();
-
-    zoomControl->startZoomSequence(center);
+    zoomControl->startZoomSequence(this->lastZoomScrollCenter);
 }
 
 void TouchInputHandler::zoomMotion(InputEvent const& event) {
@@ -137,12 +133,19 @@ void TouchInputHandler::zoomMotion(InputEvent const& event) {
     ZoomControl* zoomControl = this->inputContext->getView()->getControl()->getZoomControl();
     zoomControl->zoomSequenceChange(zoom, true);
 
-    auto center = (this->priLastAbs + this->secLastAbs) / 2;
+    int vPadding = inputContext->getSettings()->getAddVerticalSpace() ?
+                           inputContext->getSettings()->getAddVerticalSpaceAmount() :
+                           0;
+    int hPadding = inputContext->getSettings()->getAddHorizontalSpace() ?
+                           inputContext->getSettings()->getAddHorizontalSpaceAmount() :
+                           0;
+    auto center = (this->priLastAbs + this->secLastAbs) / 2 - utl::Point<double>{double(hPadding), double(vPadding)};
     auto lastScrollPosition = zoomControl->getScrollPositionAfterZoom();
     auto offset = lastScrollPosition - (center - lastZoomScrollCenter);
 
-    zoomControl->setScrollPositionAfterZoom(offset);
-    lastZoomScrollCenter = center;
+
+    //zoomControl->setScrollPositionAfterZoom(offset);
+    this->lastZoomScrollCenter = center;
 }
 
 void TouchInputHandler::zoomEnd() {
```

This makes sure the h/vPadding is always used for the zoom center calculation (I don't know enough about the codebase to know whether that's needed, but I wanted to make the center calculation at least consistent) but it also simply removes the setScrollPositionAfterZoom call because I couldn't figure out how to fix the offset calculation in a way that long PDFs don't jump around in weird ways when scrolling (I regularly use PDFs that are around 100 pages long, if you can't reproduce issues with such PDFs I can capture some short videos to better explain the issues I'm having).
Even after that patch, scrolling in long PDFs is a bit laggy but by far not as much as before.

**Comment by MisterPresident** [comment]
@David96 s fix is improving my zooming a lot. I do not change at least 3 pages on a zoom. However, it's still not correct, sometimes i am moving a little bit to the side or up/down.

**Comment by ohthehugemanatee** [comment]
I have to update my previous testing results.

* I didn't realize that my compiled version was storing it's settings in `~/.config/com.github.xournalpp.xournalpp`, while the installed version was putting it in `~/.xournalpp`... and sometimes maybe a mixture of both? Anyway properly deleting both settings directories made a big difference of course.
* I noticed that the problem behaviors are different based on the display mode: presentation, zoomed-to-fit, or 1:1.

So, after a fresh delete of both config directories, I start the application from inside `build/src`.

In default mode, with fresh document created when I started `xournalpp`:
* zoom and scroll are fine. I see the lag that @David96 is describing but it's not a big deal. 
* No behavior change between dsplay modes

Open a PDF ([Chopin 24 preludes book 2.pdf](https://github.com/xournalpp/xournalpp/files/4742047/Chopin.24.preludes.book.2.pdf)). In default view mode:
* Zoom also scrolls, though I can't predict in which direction or how much it will scroll. 
* Scroll is doing its problematic huge jerky jumping around thing.

Zoom to fit screen:
* zoom works fine, albeit laggy (laggier than with the default empty document)
* scroll is laggy, but works. No big jumps; the page stays "stuck" to the touch point of my finger.

Presentation mode:
* Zoom is non-functional
* Scroll is doing its problematic huge jerky jumping around thing.

**Comment by Febbe** [comment]
@David96 your patch breaks the zoom with the mouse. You should not change code in the TouchInputHandler. I will merge this PR, since it removes at least the scrolling with touch zoom.

**Comment by David96** [comment]
@Febbe Do you have an IRC channel or something similar to discuss this? To me the code in TouchInputHandler looks wrong in some places and still causes lots of scrolling issues in big PDFs for me.

**Comment by Febbe** [comment]
We have gitter and Matrix

**Pull request merged**
