### PR TITLE
Added icons for set square and compass

### PR DESCRIPTION
**Pull request by dreng**
During my tests of the "set square" feature, which is in an early developing stage, I noticed that the icons are barely visible. While discussing some improvements [here](https://github.com/xournalpp/xournalpp/discussions/4254) with Roland I decided to create some new icons.

### CODE REVIEW

**Comment by rolandlo** [comment]
Thanks @dreng for putting your efforts into this. The icons look pretty good and fit very nicely with the existing icon themes. 
We may have to wait though until the Compass is merged or at least until its design is final.

**Comment by rolandlo** [comment]
@dreng The compass is merged now. Can you rebase on master and solve the merge conflict? Let me know if you need help.
Moreover the design of the compass has changed slightly (color of the marked radius from green to blue). So maybe make all 3 radii blue (not just 2 of them).

**Comment by dreng** [comment]
@rolandlo Some help is indeed needed here. If I try to sync the branch in my fork, it says that my commit will be discarded. No chance to priorize one of the conflicting files. I can just use Github's editor in order to resolve the confict text-wise, but this is not what I want. I want to preserve my file. The Github docs didn't help either but left me more insecure than before.

**Comment by rolandlo** [comment]
> @rolandlo Some help is indeed needed here. If I try to sync the branch in my fork, it says that my commit will be discarded. No chance to priorize one of the conflicting files. I can just use Github's editor in order to resolve the confict text-wise, but this is not what I want. I want to preserve my file. The Github docs didn't help either but left me more insecure than before.

One way to achieve the goal (which doesn't require solving conflicts):
1) Make a backup of all the icons in some folder, which is not contained in the root folder (`xournalpp`) of the repository
2) Use 
```term
git reset --hard upstream/master
```
3) Add back the icons to the correct folders and the copyright notice (which you can copy from here), add and commit them
4) Check the log and commit info with
```term
git log
git show
``` 
to see if everything is alright
5) Use
```
git push --force
```
to push the changes to Github.

**Comment by rolandlo** [comment]
> @rolandlo Some help is indeed needed here. If I try to sync the branch in my fork, it says that my commit will be discarded. No chance to priorize one of the conflicting files. I can just use Github's editor in order to resolve the confict text-wise, but this is not what I want. I want to preserve my file. The Github docs didn't help either but left me more insecure than before.

One way to achieve the goal (which doesn't require solving conflicts):
- Make a backup of all the icons in some folder, which is not contained in the root folder (`xournalpp`) of the repository
- Use 
```term
git reset --hard upstream/master
```
Here I am assuming that `upstream` is the remote name for the url `https://github.com/xournalpp/xournalpp.git`
- Add back the icons to the correct folders and the copyright notice (which you can copy from here), add and commit them
- Check the log and commit info with
```term
git log
git show
``` 
to see if everything is alright
- Use
```
git push --force
```
to push the changes to Github.

**Comment by rolandlo** [comment]
Looks like there was some problem. There is a shorter way though, that doesn't require backing files up and adding them manually:

```
git checkout set-square-icons
git reset --hard 593572ee4
git rebase -X theirs upstream/master
git push --force
```
- The first command checks out your feature branch that adds the icons
- The second command goes back to the state you were before trying to rebase on current master.
- The third command rebases on upstream/master keeping the changes from your feature branch for the merge conflict.
- The forth command pushes the changes forcefully to Github

**Comment by dreng** [comment]
Not exactly the way I wanted to go but copying the needed files and re-adding them solved the problem at least.

Git reset --hard somehow didn't work for me. I updated my fork which deleted the file as it stated before. I then rebased the branch and added the previously copied files. Finally I pushed the branch back to my fork.

**Comment by rolandlo** [comment]
Great you figured out a way! There is one issue left: Please delete the two old setsquare and compass icons from the folder `/ui/iconsColor-light/scalabel/actions/`. Otherwise in the light color theme the old icons are shown.

**Comment by dreng** [comment]
Overlooked the old icons. Thanks for watching out.

**Review by rolandlo — APPROVED** [review]
LGTM. I like the new icons. Definitely an improvement over the old ones.
Merging in 24 hours if no objections are raised.

**Comment by rolandlo** [comment]
Thanks again for the icons @dreng ! Just merged them.

**Comment by dreng** [comment]
You're welcome, @rolandlo !

**Pull request merged**
