### PR TITLE
Make Presentation Mode Fill the Screen

### PR DESCRIPTION
**Pull request by reedacartwright**
This pull request makes fullscreen+presentation mode fill the screen but is not ready to be merged yet. I submit it now for review and to give others a chance to properly integrate it into the code base, UI, and UX.

### Outstanding Issues
- [ ] Entering/exiting presentation mode does not automatically hide toolbars, sidebars, etc. or enter fullscreen.
- [x] Padding, shadows, etc. have been disabled completely instead of only being disabled in presentation mode.
- [ ] Search bar defaults to being invisible, and escape no longer cancels search bar visibility.

### CODE REVIEW

**Comment by rolandlo** [comment]
@reedacartwright Could you please explain what you try to achieve with the searchbar? Why was it necessary to make changes there?

**Comment by reedacartwright** [comment]
@rolandlo Taking out all the padding, toolbars, etc. got me to 1920 x 1079. I noticed that I need to press 'ESC' once to get that last row of pixels back. I tracked it down to the search bar which was adding 1 pixel at the bottom and capturing the ESC. So I hid the search bar, and made it not capture the escape.

**Comment by rolandlo** [comment]
Ok, good to know. It is really a very nice fullscreen mode now. Have you check my commits restoring the shadows and paddings when not in presentation mode? Any comments about that?

**Comment by reedacartwright** [comment]
I haven't tried it out locally, but it looks like you got all the spots.

**Comment by stevenbell** [comment]
What needs to happen to get this merged into main, besides a rebase?  I've seen various comments about major rewrites and refactorings which would affect this, but I haven't followed which of those have happened, or are happening.

**Comment by rolandlo** [comment]
@stevenbell I think this PR is far from finished. It would take someone investing work in creating a nice fullscreen presentation mode. Unfortunately I won't find the time for it myself.

**Comment by stevenbell** [comment]
@rolandlo Can you elaborate on what would need to be done?  I might be able to help do it if it's not too major.

I've been using the branch from @reedacartwright as my "daily driver" without any major issues, so I'm not really sure what you mean by "nice fullscreen presentation mode".

**Comment by rolandlo** [comment]
@stevenbell Here is my opinion:

- [ ] Firstly I think that presentation mode should really be a mode that only presents one page (resp. one or two pages in paired mode). Xournal has a one page mode that does the job. In Xournal++ if you have a very wide page followed by a normal page in presentation mode, you will see the second page below the first one when viewing the first page.
- [ ] Make sure that pages of the same size are displayed exactly at the same position in presentation mode.
- [ ] In presentation mode (fullscreen or not) things like menubars and sidebar should be hidden (at least by default, as configured in the view panel in the preferences). Currently that only happens when F5 is pressed.
- [ ] There  is an issue regards to the searchbar mentioned in the PR description https://github.com/xournalpp/xournalpp/pull/2408#issue-743495445
- [ ] There have been suggestions to add a timer for presentation mode. That could be deferred to another PR though.

In future it would nice to have two different displays, one for the presenter, the other one for the viewer. That will take quite some work though.

**Comment by rolandlo** [comment]
Closing this PR, since it is outdated.

**Pull request closed without merging**
