### PR TITLE
Split gui/TextEditor into view and controller

### PR DESCRIPTION
**Pull request by bhennion**
This PR splits gui/TextEditor into control/tools/TextEditor and view/overlays/TextEditionView.

It also:

1. Moves gui/TextEditor to control/tools
2. Moves (most of) the content of PageView::endText() and PageView::startText() to TextEditor's destructor and constructor

### CODE REVIEW

**Comment by bhennion** [comment]
Rebased on master. This is now independent of every other PR of the split-into-controller-and-view series. It can thus be reviewed (although the size of the PR will make the reviewing cumbersome).

**Comment by bhennion** [comment]
Rebased and resolved conflicts

**Comment by bhennion** [comment]
Rebased and resolved conflicts

**Comment by bhennion** [comment]
Rebased on master and adapted to changes from #4382.

**Comment by Technius** [comment]
Can we break this into two PRs, one before the change to the view/overlay system and one after? This is very difficult to review due to its size.

**Comment by bhennion** [comment]
So, it turns out I could split off another big chunk of this PR to facilitate the reviewing. This is now in #4442.

- [ ] Merge #4442 and rebase

**Comment by tattsan** [comment]
As I wrote in https://github.com/xournalpp/xournalpp/pull/4442#issuecomment-1374943461, there is an issue which lead to crash. To reproduce:
* Start texteditor, and input an emoji with an IME.
* Insert a newline and input an emoji with an IME.
* Then the second emoji will be placed at the first line, so the two charactors are displayed overwraped.
* Exit the texteditor, but keep the state texttool.
* Click the overwraped characters, then the app will crash.

Please look in  the attached  errorlog file.
[errorlog.20230109-075107.log](https://github.com/xournalpp/xournalpp/files/10369694/errorlog.20230109-075107.log)

**Comment by rolandlo** [comment]
@bhennion Can you please update the PR description?

**Comment by bhennion** [comment]
> @bhennion Can you please update the PR description?

Done. There isn't much that isn't just the splitting now.

**Review by rolandlo — APPROVED** [review]
Very nice job! The code looks good and it works fine. Repaint ranges are also improved.
Minor nitpick: I found one unused function that could be removed (see in the code).

**Comment by bhennion** [comment]
Thanks for the review (and the catch!) @rolandlo.

Merging in 24 hours unless an objection is raised.

**Pull request merged**
