### PR TITLE
modify Zoomslider behaviour

### PR DESCRIPTION
**Pull request by peetCreative**
- Add logarithmic scale function
- The changes are only every 5th time updated
- One sliding is one sequence

### CODE REVIEW

**Comment by andreasb242** [comment]
Technical working, but way are you updating only every 5 times?
I can change the slider, but the zoom does not change?

**Comment by andreasb242** [comment]
Rendering is already in another thread, and rendering is delayed, as long as the zoom does not match the buffered image is fast scaled with cairo... So there should be no issue.

**Comment by peetCreative** [comment]
Yes you are we kinda right. It's lacking a bit but its better than the not rendering.

**Comment by peetCreative** [comment]
I found another issue, so don't merge... I will come back later with this pull request

**Comment by andreasb242** [comment]
I'll try the performance on a slow notebook, but then I wait until you are finished.

**Comment by peetCreative** [comment]
Mh as I played around with the Zoom calibration, shouldn't we have the min and max zoom depending the 100% zoom?
So minimum Zoom = 0.3 * zoom100 and maximum Zoom = 7 * zoom100

**Comment by peetCreative** [comment]
OK I disabled the percentage which is still faulty. But you can merge or test.

**Comment by andreasb242** [comment]
I'll test this on a high DPI and a standard display...

**Pull request merged**
