### PR TITLE
Versioning for Fedora and MacOS

### LINKED ISSUE #2820: Missing version number in latest macOS download (1.0.20)
**Affects versions :**
 - OS: macOS (https://github.com/xournalpp/xournalpp/releases/download/1.0.20/xournalpp-1.0.20-macos.zip)
 - Version of Xournal++: 1.0.20 
     - can be obtained by running `xournalpp --version` or in the **About** window

**Describe the bug**
The ShortVersionString and BundleVersion keys are missing in the info.plist 

should look like that:

`<key>CFBundleShortVersionString</key>
	<string>1.0.20</string>
…
	<key>CFBundleVersion</key>
	<string>11111</string>
`
image

### PR DESCRIPTION
**Pull request by LittleHuba**
This PR fixes some bugs for specific OSs concerning version information.

- Bump of version information in Fedora build recipe
- Inclusion of version strings in MacOS Info file
- Fix of release helper script to update these values

fixes #2820

### CODE REVIEW

**Comment by rolandlo** [comment]
> > > @rolandlo could you give this another try? Just to make sure that I did not remove something that broke the bundling again.
> > 
> > 
> > The bundling looks all good. I'm just a bit confused of the version information. Wasn't 1.1.1+dev supposed to mean version 1.1.1 published plus development on top?
> 
> Oh dammit. I'll check how that happened. It's the same on `release-1.1`... see_no_evil You are of course right. It should be 1.1.1~dev.

The mistake seems to be happend (manually) in commit cbc29af9e8a9a38614f08438405dc3a61e653887

**Comment by LittleHuba** [comment]
I fixed the messes I made in cbc29af and in the files for MacOS and Fedora. This should be ready to be merged now.

**Comment by LittleHuba** [comment]
@xournalpp/core I'll merge this in 24 hours if there are no objections.

**Comment by rolandlo** [comment]
@LittleHuba Any reason why this PR is not merged yet? I think it should be merged like announced by you on Nov 22.

**Comment by LittleHuba** [comment]
Not that I know of any reason. Most likely it just fell into the time where I was quite busy with other stuff.

**Pull request merged**
