### PR TITLE
Fixed typo in method name

### PR DESCRIPTION
**Pull request by fpesari**
Renamed 

copyToCliboard

to

copyToCli**p**board

### CODE REVIEW

**Comment by fpesari** [comment]
Hello, done

**Comment by rolandlo** [comment]
Sorry, but that's not quite what I said. Please drop the second commit again and rebase the first commit on current master (via `git rebase upstream/master`). There should be only one commit.

**Comment by fpesari** [comment]
Apologies, I should have used the git CLI straight way. Now everything should be in order.

**Review by rolandlo — APPROVED** [review]
LGTM

Merging in 24 hours if no objections are raised.

**Pull request merged**
