### PR TITLE
WIP: Redesign settings

### PR DESCRIPTION
**Pull request by LittleHuba**
This PR includes a revised layout of the settings dialogue that reorderes some settings and makes it overall more beautiful and easier to understand.

@andreasb242 or @luco5826:  Please take a look at the italian translation and update accordingly. All other translations need to be updated as well but I'm not fluent enough in any of them to help. English and German should be up to scratch.

### CODE REVIEW

**Comment by andreasb242** [comment]
I don't speak italian.

@luco5826 or @morrolinux are native ;-)

Please add a Screenshot for such pulls in the future, it's nearly impossible to review the glade file...

But the settings dialog is always a Problem... we did already a lot of improvements, but then we get more and more settings on one place and need to reorganize again etc...

**Comment by LittleHuba** [comment]
Attached you find all the tabs of the settings dialog. Adding new settings to one tab is no issue, we just need to add a scrollview then. The important part is that the settings are sorted in a way that one can easily find them.

@andreasb242 one question for you: In the Touchscreen tab the description for the workaround is not really conclusive for me. Could you elaborate on this? An improved description would fix those issues where people just randomly select this option as their holy grail to get everything working. (e.g. #988)

**Comment by andreasb242** [comment]
Look much better!

**Comment by morrolinux** [comment]
Tonight I'll probably have a look to (and update) the italian translation accordingly

**Comment by LittleHuba** [comment]
@morrolinux I'll merge this branch then you can merge your fixes for the italian translation in an own PR.

**Pull request merged**
