### PR TITLE
Fix UB for BaseShapeHandler when clicking without moving

### PR DESCRIPTION
**Pull request by bhennion**
I let an UB slip in when refactoring the BaseShapeHandler: strokes without any points were created, leading to SegFaults upon calls to Stroke::calcsize. This PR fixes that.

It may as well solve #4316 (I can't know for sure, I can't reproduce the issue).
@tattsan would you mind trying this out and telling if this fixes your issue?

### CODE REVIEW

**Comment by tattsan** [comment]
Sorry, 282843b5e6b098d96a7a9289c007e74a6b4a926f doesn't solve #4316.

**Comment by rolandlo** [comment]
I can reproduce the bug and confirm that https://github.com/xournalpp/xournalpp/commit/282843b5e6b098d96a7a9289c007e74a6b4a926f does not fix it. At least that commit fixes a crash I get otherwise using the Ellipse drawing type while drawing ellipses without moving the cursor.

**Comment by rolandlo** [comment]
The bug from #4316 only appears when I use the stylus (not with the mouse). The lines point to the page origin (top left).

**Comment by bhennion** [comment]
The last commit fixes the "tap" event line bugs, but it is not quite enough:

- Enable grid snapping
- Start drawing an ellipse
- Move the cursor back to the original point
- Release the button
- See the ugly line again.

Using `std::atan2` as @tattsan suggested (https://github.com/xournalpp/xournalpp/pull/4320#discussion_r995688691) would cleverly fix that. I'll wait for us to collegially take a decision about the formulas (see #4320) before doing that.

**Comment by bhennion** [comment]
As this is somewhat independent of the ellipse resolution discussed in #4320, I'll be merging this trivial bugfix in 48 hours, unless someone objects.

**Pull request merged**
