### PR TITLE
Generate portable install for Windows in release pipeline

### LINKED ISSUE #3714: Creating a "portable" Windows version
**Rationale**
I often use `xournal++` to give classes and talks. In several venues, I am forced to use a computer where I can't install any software. It would be nice to have a version of `xournal++` for windows that can run off a pen-drive (a *portable* version, I think it's called in the Windows-land).

**Describe the solution you'd like**
A version of the Windows executable that can just run out of a pen drive, or of a directory without the need for administration rights. 

**Describe alternatives you've considered**
There are really no alternatives... Unfortunately, my knowledge of Windows is nil, so I do not know how difficult this can be.

**Additional context**
An example on GitHub program that has a "portable windows" version: https://github.com/pdfarranger/pdfarranger/releases

### PR DESCRIPTION
**Pull request by Technius**
Partially fixes #3714 (also need to update the deployment steps after this is merged). This PR also updates the Windows CI build to use the `windows-2019` image since the currently used image will be removed next week.

### CODE REVIEW

**Review by LittleHuba — APPROVED** [review]
Cool! Looks good so far. Please also update the release system on Azure and check that the nightlies are still released.

**Comment by Technius** [comment]
I made the adjustments to the pipeline. Will check on it later tonight.

**Comment by Technius** [comment]
Also need to cherry pick to release-1.1 once everything is working.

**Comment by Rmano** [comment]
Thank you!

**Comment by multixrulz** [comment]
Is this usable yet?  I'm currently looking for a portable version too.

**Comment by Rmano** [comment]
If I am not wrong we should wait for the next release... maybe 1.1.2? I do not see the "portable windows" artifacts yet.

**Comment by LittleHuba** [comment]
This is already usable. Please look at the nightly release please.

https://github.com/xournalpp/xournalpp/releases/download/nightly/xournalpp-1.1.1%2Bdev-nightly.20220614-windows-portable.zip

**Comment by multixrulz** [comment]
I finally got to try this out. It works perfectly, thanks!

**Pull request merged**
