### PR TITLE
fix utf8 problems on windows, loading files with special characters

### LINKED ISSUE #2280: Problem with Files names containing accents in Windows 10
OS : Windows 10
Version of Xournalpp : xournalpp-1.1.0+dev-nightly.20200924-windows.exe

Problem :
Under windows 10, when I double-click on a file whose name contains accents the pages are blank.
Under Windows 10, when I open it from menu "File->Open", I have the message "Could not open file"

When I rename the file without accents, there is no problem.

[Corrige.zip](https://github.com/xournalpp/xournalpp/files/5286274/Corrige.zip)

### PR DESCRIPTION
**Pull request by Febbe**
Fixes #2280

### CODE REVIEW

**Comment by MichelReims** [comment]
How can I make to obtain  files for f fix utf8 problems and  compile Xournalpp with this fix ? I whish test it.
Thank you

**Comment by Febbe** [comment]
You can `git clone https://github.com/Febbe/xournalpp.git` and then `git checkout fix_filesystem_utf8`

**Comment by MichelReims** [comment]
Thank you

**Comment by MichelReims** [comment]
I'm not sure, but I think there is the same problem with the annotated pdf files that contain specials characters ; I can save the annotate file with accents, but I can't load it

**Comment by MichelReims** [comment]
I think there are still some issues with loading xopp files related to pdf files containing accents

**Comment by MichelReims** [comment]
I just compiled your last version of xournalpp (under windows 10). Then I chose to do " File->Annoted Pdf" with the filename " C:\temp\TD Ma0101 S1A2 du 07-09-2020 scanné.pdf". I anotate it and save it with the filename "C:\temp\TD Ma0101 S1A2 du 07-09-2020 scanné.xopp".I quit Xournalpp and reopen it ; when I want load "C:\temp\TD Ma0101 S1A2 du 07-09-2020 scanné.xopp", I have the error box below
image

**Comment by Febbe** [comment]
@MichelReims can you retest it, I can't reproduce your issue.
Also, updating MSYS / Mingw64, by calling `pacman -Syuu` twice, could help to solve dependency issues.

**Comment by MichelReims** [comment]
@Febbe You have solved the problem. Thank you for your work.

**Pull request merged**
