### PR TITLE
Fix localizations, update icon and add Lua for MacOS

### PR DESCRIPTION
**Pull request by rolandlo**
This PR makes the localizations work on MacOS. Without this PR the translations (`xournalpp.mo` files) are not included in the `Xournal++.app` bundle and the `PACKAGE_LOCALE_DIR` returns invalid values in the `LanguageConfigGui`.

### CODE REVIEW

**Comment by Febbe** [comment]
I think you can merge this after rebasing.

**Comment by rolandlo** [comment]
There is still an issue with the localizations when running the Azure pipeline (or building on MacOS 10.15; it builds correctly on MacOS 11.2):
```
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/about.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/exportSettings.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/fillOpacity.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/goto.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/images.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/latexSettings.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/main.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/pageTemplate.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/pagesize.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/pdfpages.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/plugin.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/pluginEntry.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/renameLayerDialog.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/settings.glade' extension 'glade' is unknown; will try C
../ui/settings.glade:4625: warning: unterminated character constant
../ui/settings.glade:4718: warning: unterminated character constant
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/settingsButtonConfig.glade' extension 'glade' is unknown; will try C
../ui/settingsButtonConfig.glade:129: warning: unterminated character constant
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/settingsDeviceClassConfig.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/settingsLanguageConfig.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/texdialog.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/toolbarCustomizeDialog.glade' extension 'glade' is unknown; will try C
/Users/xournal-dev/gtk/inst/bin/xgettext: warning: file '../ui/toolbarManageDialog.glade' extension 'glade' is unknown; will try C
```
This results in half-translated stuff.

**Comment by Febbe** [comment]
The files have to renamed into .ui or .xml files

**Comment by rolandlo** [comment]
> ~The files have to renamed into .ui or .xml files~
> Ok somehow xgettext does not get, that those files are glade files. We should try to add `-L Glade` to the xgettext command.
> 
> https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html

Renaming all these file extensions from `.glade` to `.ui` (and the references to the `.glade`-files in the code) sounds like an extreme situation, although it works (just checked it).
I think we already pass the `-L Glade` option to `xgettext`. More precisely we pass `--language Glade` as seen from these lines:

https://github.com/xournalpp/xournalpp/blob/00c2c046807340cb1af9ce9230cc3b426d49cee9/cmake/find/Gettext.cmake#L181-L184

https://github.com/xournalpp/xournalpp/blob/00c2c046807340cb1af9ce9230cc3b426d49cee9/cmake/find/Gettext.cmake#L220-L239

https://github.com/xournalpp/xournalpp/blob/00c2c046807340cb1af9ce9230cc3b426d49cee9/cmake/find/Gettext.cmake#L433-L455

This was also confirmed by a status message I added to the cmake file.

**Comment by rolandlo** [comment]
I'm kind of confused right now, because locally built (via `complete-build.sh`) the problem with `xgettext` and glade files does not appear. Localizations are just fine.

**Comment by Febbe** [comment]
Mhh does mac/the mac pipeline has a buildin xgettext, which is older than our version?

**Comment by rolandlo** [comment]
I really don't get why the `xgettext` command fails for glade files. On my MacBook Pro using the same `xgettext` version 0.20.2 and the same arguments (apart from the exact directory names) it just works.

```
2021-04-05T07:46:42.7394640Z -- xgettext command for glade files: /Users/xournal-dev/gtk/inst/bin/xgettext --package-name;xournalpp;--package-version;1.1.0+dev;--language=C++;-s;--from-code=UTF-8;--keyword=_;--keyword=_F;--keyword=N_;--keyword=C_:1c,2;--keyword=C_F:1c,2;--keyword=NC_:1c,2 --language;Glade;--omit-header -o /Users/runner/work/1/s/build/po/_glade.pot ../ui/about.glade;../ui/exportSettings.glade;../ui/fillOpacity.glade;../ui/goto.glade;../ui/images.glade;../ui/latexSettings.glade;../ui/main.glade;../ui/pageTemplate.glade;../ui/pagesize.glade;../ui/pdfpages.glade;../ui/plugin.glade;../ui/pluginEntry.glade;../ui/renameLayerDialog.glade;../ui/settings.glade;../ui/settingsButtonConfig.glade;../ui/settingsDeviceClassConfig.glade;../ui/settingsLanguageConfig.glade;../ui/texdialog.glade;../ui/toolbarCustomizeDialog.glade;../ui/toolbarManageDialog.glade
```

**Comment by Febbe** [comment]
There is a language=c++ and keywords, which do not occur in glade.

**Comment by Febbe** [comment]
Also, --language;Glade should be --language=Glade

**Comment by Febbe** [comment]
I also think those arguments must not contain `;` at all

**Comment by rolandlo** [comment]
The `;` are only printed because it is a list and I have quoted it in the STATUS `message`. They are not really passed to `xgettext`. 
I think `--language Glade` AND `--language=Glade` should be equivalent, but we can try if it makes a difference.
You are right about the `language=c++` and keywords, which do not occur in glade. I am not sure they make a difference, though.

**Comment by rolandlo** [comment]
So using `language=Glade` instead of `language Glade` did not make any difference. Probably it is a packaging problem like in [this bug report](https://lists.gnu.org/archive/html/bug-gettext/2016-01/msg00003.html). I didn't manage to find out if the Azure Pipelines MacOS 10.15 Image has some version of `xgettext` preinstalled.

**Comment by rolandlo** [comment]
@Febbe Can I merge this PR? The localizations should work fully after the gtk blob has been updated.

**Comment by rolandlo** [comment]
localizations, icon, Lua and plugins installation, LaTeX template all work with this PR.

Merging in 24 hours, if no objections are made.

**Pull request merged**
