### PR TITLE
Force page layout update after inserting page

### LINKED ISSUE #2289: I come back to the top of the document when I add a new page at the end of a document
I work under windows 10 with the nightly-automated release of the 28 september.
Sometimes, when I add a new page at the end of a document, I come back to the top of the document.

### PR DESCRIPTION
**Pull request by rolandlo**
This PR should fix  #2289 and #1926 about focus shift to the beginning of the document after inserting a page. It may also fix the freeze from #2211 and  #2144 when inserting a blank page in a pdf document.

The first commit updates the page layout immediately after inserting the page. This only happens after some time (usually too late) without this fix. It also removes unnecessary calls to `firePageSelected` (which is called from `scrollToPage` anyway) and `layoutPages` which gets triggered after the `gtk_window_move_resize` anyway.
It does not quite solve the problem of scrolling to the new page though, since sometimes scrolling goes to the end of the current page. More work is required.

### CODE REVIEW

**Comment by Rmano** [comment]
Testing. 
BTW, to test PR I do the following: 
```bash 
git fetch origin pull/2312/head:pr-2312
git checkout pr-2312
cd build
make
```
Is this correct? Should I also remove the `build` direectory?

**Comment by Rmano** [comment]
MUCH better now. I didn't manage to make it jump back (congrats!).
It's not perfect though.  Notice in the animation below: 
1 - adding the second page should (in my opinion) scroll to show the new page (probably aligned with the bottom)
2 -adding the third page does not scroll at all, making the new page invisible unless you manually scroll
3 - adding the 4th page show what is in my opinion the correct behavior --- scrolling so that the last page is full on screen.

Peek 2020-10-12 12-30


But nevertheless, this is a nice step forward, thanks to all the contribs that helped find this.

**Comment by rolandlo** [comment]
@Rmano 
Thanks for testing. You observe the same behavior as I do. Let's see if we can make it perfect then.

**Comment by rolandlo** [comment]
Messed it up too much. I will try it with another PR.

**Comment by rolandlo** [comment]
Closed in favor of PR #2346.

**Pull request closed without merging**
