### PR TITLE
add missing drawing tools and German names

### LINKED ISSUE #1829: Spline, graph tool and shape recognition not included in "Right Hand Note Taking"
The three features above are unforunately not included. I am not sure if anything else is missing. I think all of the toolbars should be checked. There are also options like "fixed rotation" and "align at grid" missing in the other toolbars.

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #1829

I have only modified the "Right Hand Note taking" toolbar, adding the missing drawing tools (coordinate system, spline and shape recognizer), paired pages and hand tool. 

Moreover I added the German names for some toolbars.

**Edit:** added hand tool and paired pages.

### CODE REVIEW

**Comment by rolandlo** [comment]
> 
> 
> Fixes #1829
> 
> I have only modified the "Right Hand Note taking" toolbar, adding the missing drawing tools (coordinate system, spline and shape recognizer) and moved the fill tool to the left to have the two bars take equal size.
> 
> Moreover I added the German names for some toolbars.

The suggestion to add the "grid snapping" and "rotation snapping" icons to the Toolbar Left, Toolbar Right and Xournal++ toolbar didn't look good to me, because space is limited on those toolbars.

**Comment by rolandlo** [comment]
Here are some screenshots for the "Right Hand Note taking" toolbars, before and after the changes of this PR:

Before: 
grafik

After:
grafik

Note the 5 icons that have been added (paired pages, hand, coordinate system, spline and shape recognizer)

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised

**Review by Technius — APPROVED** [review]
LGTM. In the future, we'll probably want to use the translations files to autogenerate the language-specific tooltips in `toolbar.ini`.

**Pull request merged**
