### PR TITLE
desktop: added appdata file

### PR DESCRIPTION
**Pull request by muelli**
This addresses https://github.com/xournalpp/xournalpp/issues/1298

It would still be nice to have the releases embedded in this appdata file.

Note that I haven't been able to test the buildsystem whether it installs this file appropriately.

### CODE REVIEW

**Comment by cbm755** [comment]
1.  I tested with `cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local`.  The appdata file installed correctly to `/home/.../.local/share/metainfo/xournalpp.appdata.xml`

2.  I think `<project_group>GNOME</project_group>` should be removed.

3.  I have done OARS for this project, and I got:
```
<content_rating type="oars-1.0"/>
```

This looks good to me, but I gather there are also upstream flathub comments to address?

**Comment by muelli** [comment]
I have addressed the comments on flathub, bar the releases. It would be nice if someone could contribute the `releases` tag.
Bonus points if the appdata file is somehow updated automatically with new releases.

**Comment by cbm755** [comment]
I'll send a pull request for the releases, but not the "bonus points" bit

**Comment by cbm755** [comment]
see https://github.com/muelli/xournalpp/pull/1

**Comment by Technius** [comment]
The git tags are not really update to date right now, but we'll try to update them in the next release (and hopefully keep them updated, _hopefully_ in an automated way, as we make more releases).

**Comment by Technius** [comment]
There's a merge conflict that needs to be resolved.

**Comment by Technius** [comment]
LGTM; there's some additional info we could add but this works for now.

**Pull request merged**
