### PR TITLE
Remove the .xopp~ backup file after a successful save

### PR DESCRIPTION
**Pull request by Luca0208**
This also fixes the problem that after the first save or save as after opening a file on all subsequent saves no backup file was created.

### CODE REVIEW

**Comment by Luca0208** [comment]
I didn't actually change anything about the branches in this PR. You changed the base branch to `xournalpp:release-1.1`, but apparently GitHub doesn't allow you to change the source branch, so I can't correct it to `Luca0208:release-1.1` on which the rebased changes live.

As far as I see you either merge the changes manually or I close this PR and open a new one with `Luca0208:release-1.1` as source branch and `xournalpp:release-1.1` as base branch.

**Comment by LittleHuba** [comment]
There is unfortunately still a case that you missed:

1. Open Xournal++ and create a document
2. Save the document
3. Make some more changes
4. Wait for an autosave file to be generated
5. Use the menubar of Xournal++ to create a new file
6. Save the previously opened document when requested
7. Close Xournal++

**Comment by Technius** [comment]
Hi @Luca0208, what's the status of this PR? If you need help, I can provide some assistance since I'd like this to be merged soon.

**Comment by Luca0208** [comment]
Hi, this kind of slipped under the radar, sorry.
Should be ready to merge now if I didn't miss anything.

**Review by Technius — APPROVED** [review]
Thanks. While I would actually like to see the `shouldCreateBackupOnSave` etc. functions deleted since we always want to create a backup, I'll merge this for now since it fixes the issue at hand. The refactoring can happen in a follow up PR.

**Comment by Technius** [comment]
Note: the autosave and backup features can be tested using inotifywait; we should write integration tests for these types of behaviors.
```
cd /tmp
inotifywait -e create,moved_to,delete . -m

# now open xournalpp and manipulate files in /tmp
```

**Comment by Technius** [comment]
I rebased, squashed, and merged the PR separately. Thanks for the PR!

**Pull request closed without merging**
